[TIMOB-25970] Android: 'postlayout' event not working for Picker with type Titanium.UI.PICKER_TYPE_DATE
appcelerator/titanium_mobile pull request #10005
Opened 2018-04-17 14:20 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25970

**Description:**
Fire `postlayout` event from Picker with type Ti.UI.PICKER_TYPE_DATE on Android.

**Test case:**
_app.js_

```
var win = Ti.UI.createWindow();
picker = Ti.UI.createPicker({type: Ti.UI.PICKER_TYPE_DATE});
picker.addEventListener('postlayout', function() {
    alert('Post layout!');
});
win.add(picker);
win.open();
//picker.showDatePickerDialog();
```

2018-04-17 14:36 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  1 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/ypbnv/titanium_mobile/blob/TIMOB-25970/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10005/1/artifact/dist/mobilesdk-7.2.0.v20180417072218-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-04-17 15:54 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  1 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10005/3/artifact/dist/mobilesdk-7.2.0.v20180417083951-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.Picker | DatePicker postlayout event in layout | 4.05 | Error: timeout of 2000ms exceeded |
| android.Titanium.UI.WebView | userAgent | 10.441 | Error: timeout of 10000ms exceeded |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-04-17 21:34 UTC, lokeshchdhry commented
FR Passed.

`postLayout` event is fired for API 19 & above & once for API below 19.

Studio Ver:     5.1.0.201804161553
SDK Ver:        7.2.0 local build
OS Ver:         10.13.4
Xcode Ver:      Xcode 9.3
Appc NPM:       4.2.13-2
Appc CLI:       7.0.3-master.38
Daemon Ver:     1.1.1
Ti CLI Ver:     5.1.0
Alloy Ver:      1.12.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10
Devices:        ⇨ google Nexus 6P --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1
Emulator: Android 4.2.2

2018-04-30 22:01 UTC, garymathews requested changes

2018-04-30 22:01 UTC, garymathews commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/picker/CustomDatePicker.java
> +		if (this.proxy != null) {
Could consolidate this statement?
```Java
if (this.proxy != null && changed) {
```

2018-05-11 03:02 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  1 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10005/14/artifact/dist/mobilesdk-7.2.0.v20180510194547-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.Picker | DatePicker postlayout event in layout | 2.492 | Error: timeout of 2000ms exceeded |
| android.Titanium.UI.WebView | userAgent | 11.11 | Error: timeout of 10000ms exceeded |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-11 21:40 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  1 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10005/17/artifact/dist/mobilesdk-7.2.0.v20180511142545-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.ScrollableView | moveX-scrollTo | 20.01 | Error: timeout of 20000ms exceeded |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-12 03:41 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  1 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10005/23/artifact/dist/mobilesdk-7.2.0.v20180511202639-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.ScrollableView | moveX-scrollTo | 20.032 | Error: timeout of 20000ms exceeded |
| ios.Titanium.Geolocation | reverseGeocoder | 60.007 | file:///Users/build/Librar |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-16 16:34 UTC, merged