[TIMOB-17235]: iOS Windows in tabGroup flicker on first open
appcelerator/titanium_mobile pull request #10014
Opened 2018-04-26 11:43 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-17235

*Unit test coming*

2018-04-26 11:59 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  1 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/vijaysingh-axway/titanium_mobile/blob/TIMOB-17235/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10014/1/artifact/dist/mobilesdk-7.2.0.v20180426044436-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-04-26 12:39 UTC, hansemannn commented on iphone/Classes/TiUITabProxy.m
> +  [view setFrame:controller.view.bounds];
How about `[TiUtils setView:controller.view positionRect:controller.view.bounds]`? It also respects the center, although it's not as important here.

2018-04-26 13:59 UTC, hansemannn requested changes
It still flickers randomly (both the label and the color behind the tab bottom-bar). Test-case:
```js
Titanium.UI.setBackgroundColor('#000');
 
// create tab group
var tabGroup = Titanium.UI.createTabGroup();
 
 
var win1 = Titanium.UI.createWindow({  
    title:'Tab 1',
    backgroundColor:'#fff'
});
var tab1 = Titanium.UI.createTab({  
    title:'Tab 1',
    window:win1
});
 
var label1 = Titanium.UI.createLabel({
	text:'I am Window 1',
	textAlign:'center',
});
 
win1.add(label1);
 
//
// create base UI tab and root window
//
var win2 = Titanium.UI.createWindow({  
    title:'Tab 1',
    backgroundColor:'#fff'
});
var tab2 = Titanium.UI.createTab({  
    title:'Tab 2',
    window:win2
});
 
var label2 = Titanium.UI.createLabel({
	text:'I am Window 2',
});
 
win2.add(label2);
 
var win3 = Titanium.UI.createWindow({  
    title:'Tab 3',
    backgroundColor:'#fff'
});
var tab3 = Titanium.UI.createTab({  
    title:'Tab 3',
    window:win3
});
 
var label3 = Titanium.UI.createLabel({
	text:'I am Window 3',
});
 
win3.add(label3);
 
//
// create base UI tab and root window
//
var win4 = Titanium.UI.createWindow({  
    title:'Tab 4',
    backgroundColor:'#fff'
});
var tab4 = Titanium.UI.createTab({  
    title:'Tab 4',
    window:win4
});
 
var label4 = Titanium.UI.createLabel({
	text:'I am Window 4',
});
 
win4.add(label4);
 
 
//
//  add tabs
//
tabGroup.addTab(tab1);  
tabGroup.addTab(tab2);  
tabGroup.addTab(tab3);
tabGroup.addTab(tab4);
 
tabGroup.open();
```

2018-04-27 04:16 UTC, vijaysingh-axway commented
@hansemannn  I tried around 20 times on iphone/ipad simulator but unable to reproduce it. I assume you are testing on this PR. If you can share a small video, that would be great. Thanks!

2018-05-02 08:46 UTC, hansemannn approved these changes
Tests passing now, **CR approved**!

2018-05-19 13:44 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10014/8/artifact/dist/mobilesdk-7.3.0.v20180519063107-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-19 14:38 UTC, merged