[TIMOB-26032]
appcelerator/titanium_mobile pull request #10038
Opened 2018-05-11 13:16 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26032

`no tests` because it only refactors existing code. Also requires UI-related interaction (contacts permissions, selecting values from the modal dialog).

2018-05-11 13:34 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10038/1/artifact/dist/mobilesdk-7.2.0.v20180511061842-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-11 15:49 UTC, sgtcoolguy requested changes
The deprecation note on Android has a type in the correct method name. Added suggested fixed text.

2018-05-11 15:49 UTC, sgtcoolguy commented on android/modules/contacts/src/java/ti/modules/titanium/contacts/ContactsModule.java
> +		Log.w(TAG, "getPersonByID has been deprecated in favor of getPersonById (parity)", Log.DEBUG_MODE);
```java
Log.w(TAG, "Ti.Contacts.getPersonByID() has been deprecated in favor of Ti.Contacts.getPersonByIdentifier() for cross-platform parity", Log.DEBUG_MODE);
```

2018-05-11 16:43 UTC, hansemannn commented on android/modules/contacts/src/java/ti/modules/titanium/contacts/ContactsModule.java
> +		Log.w(TAG, "getPersonByID has been deprecated in favor of getPersonById (parity)", Log.DEBUG_MODE);
Updated!

2018-06-25 06:56 UTC, build commented
<!--
  1 failure:  :disappointed_rel...
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.4.0 test /Users/build/jenkins/workspace/dk_titanium_mobile_PR-10038-3MWAUH4WGFM6UMBQUHUHXBKOFS5LTGFT46C3NRGXCUKXMG726EGQ
> grunt

Running "appcJs:src:lintOnly" (appcJs) task

Running "eslint:src" (eslint) task

Running "checkFormat:ios" (checkFormat) task

Running "checkFormat:android" (checkFormat) task
Fatal error: Error: Formatting incorrect on "android/modules/contacts/src/java/ti/modules/titanium/contacts/ContactsModule.java", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='4141' length='0'>&#10;			</replacement>
<replacement offset='4145' length='1'>&#10;			</replacement>
<replacement offset='4270' length='1'>&#10;			</replacement>
</replacements>

npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-25 07:16 UTC, vijaysingh-axway approved these changes
CR passed.
Note - @hansemannn There seems linting issue in Contacts.java as build is failing. Can you fix that.

2018-10-24 23:16 UTC, lokeshchdhry commented
FR Passed.

2018-10-24 23:17 UTC, merged