Add comprehensive unit tests around Ti.UI.convertUnits and fix an iOS bug in the implementation which did not account for conversions with 3x resolutions
appcelerator/titanium_mobile pull request #10080
Opened 2018-05-29 18:57 UTC by sgtcoolguy

**JIRA:** https://jira.appcelerator.org/browse/[TICKET]

**Description:**
- This adds tests for various combinations of unit conversions for Ti.Ui.convertUnits.
- This exposed a bug in iOS where 3x devices gave bad results, so the PR includes the simple fix.
- Added tests for special cases like non-numeric inputs or percentage inputs.

TODO
- Looks like iOS does not consult ti.ui.defaultunit property for converting when input units aren't specified. It assumes "dp", which is the default value placed in tiapp.xml.
- Android appears to not handle the special case of input values as percentages. It should bail early and return 0. The test is skipped there for now.

2018-05-29 19:27 UTC, build commented
<!--
  1 failure:  Tests have failed...
  1 warning:  There is no linke...
  1 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  There is no linked JIRA ticket in the PR body. Please include the URL of the relevant JIRA ticket. If you need to, you may file a ticket on <a href="https://jira.appcelerator.org/secure/CreateIssue!default.jspa">JIRA</a>
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10080/2/artifact/dist/mobilesdk-7.3.0.v20180529121245-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.Layout | systemMeasurement | 2.709 | AssertionError: expected 20 to equal 40 |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-30 14:21 UTC, hansemannn requested changes
One unit test and its outdated docs should be removed. Everything else seems fine.

2018-05-30 14:21 UTC, hansemannn commented on tests/Resources/ti.ui.test.js
> +	it.androidAndIosBroken('.currentWindow', function (finish) {
This property only existed before we removed the `Ti.UI.Window.url` property and was forgotten during the docs update, see [here](https://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI-property-currentWindow) for reference.

2018-05-30 15:54 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10080/4/artifact/dist/mobilesdk-7.3.0.v20180530083538-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-30 16:02 UTC, hansemannn approved these changes

2018-05-30 16:02 UTC, hansemannn commented
Ready to merge once 7_3_X is branched.

2018-06-08 14:33 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10080/6/artifact/dist/mobilesdk-7.4.0.v20180608071448-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-08 14:37 UTC, sgtcoolguy commented
Created tickets for the outstanding bugs found while working on this:
- https://jira.appcelerator.org/browse/TIMOB-26113
- https://jira.appcelerator.org/browse/TIMOB-26114

2018-06-08 14:37 UTC, merged