[TIMOB-26103] iOS 12: Expose new UserNotifications API's
appcelerator/titanium_mobile pull request #10091
Opened 2018-06-06 04:46 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26103

#10088 should be merged before to include the precompile-macro already!

2018-06-06 05:08 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  1 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/hansemannn/titanium_mobile/blob/TIMOB-26103/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10091/1/artifact/dist/mobilesdk-7.3.0.v20180605214915-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-07 23:41 UTC, hansemannn commented
@sgtcoolguy Is it already possible to build with Xcode 10 Beta as of for now? We are 3 months early this time :-).

2018-06-14 12:55 UTC, build commented
<!--
  1 failure:  :disappointed_rel...
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.4.0 test /Users/build/jenkins/workspace/dk_titanium_mobile_PR-10091-NQLIOJABWPMWGT2KS3OAF36QDW5GKWG3XFPYH2JUNWGOMUDEBKCQ
> grunt

Running "appcJs:src:lintOnly" (appcJs) task

Running "eslint:src" (eslint) task

/Users/build/jenkins/workspace/dk_titanium_mobile_PR-10091-NQLIOJABWPMWGT2KS3OAF36QDW5GKWG3XFPYH2JUNWGOMUDEBKCQ/tests/Resources/ti.app.ios.searchquery.test.js
  17:19  error    Expected "finish" callback to be handled  mocha/handle-done-callback
  17:19  warning  'finish' is defined but never used        no-unused-vars
  20:16  warning  A space is required after '['             array-bracket-spacing
  20:66  warning  A space is required before ']'            array-bracket-spacing
  24:18  error    Expected "finish" callback to be handled  mocha/handle-done-callback
  24:18  warning  'finish' is defined but never used        no-unused-vars

/Users/build/jenkins/workspace/dk_titanium_mobile_PR-10091-NQLIOJABWPMWGT2KS3OAF36QDW5GKWG3XFPYH2JUNWGOMUDEBKCQ/tests/Resources/ti.app.ios.test.js
  43:94  error    Trailing spaces not allowed     no-trailing-spaces
  68:14  warning  A space is required after '['   array-bracket-spacing
  68:51  warning  A space is required before ']'  array-bracket-spacing
  88:14  warning  A space is required after '['   array-bracket-spacing
  88:51  warning  A space is required before ']'  array-bracket-spacing

✖ 11 problems (3 errors, 8 warnings)
  1 error, 6 warnings potentially fixable with the `--fix` option.

Warning: Task "eslint:src" failed. Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-07-02 05:45 UTC, vijaysingh-axway requested changes
1. I can see that  "threadIdentifier" api is not exposed, which can be used to visually group notification. Please expose this.
2. If you can give a test case would help qe to test it. Thanks!

2018-07-04 07:01 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10091/16/artifact/dist/mobilesdk-7.4.0.v20180703234417-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-07-30 04:03 UTC, vijaysingh-axway approved these changes
CR passed.

2018-07-30 05:35 UTC, merged