[TIMOB-25942] : iOS 11: Screen orientation not working in navigation window
appcelerator/titanium_mobile pull request #10104
Opened 2018-06-13 08:14 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-25942

2018-06-13 08:30 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10104/1/artifact/dist/mobilesdk-7.4.0.v20180613011526-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-13 08:44 UTC, hansemannn requested changes
One change required. Also, please make sure to test this on split-windows and different devices as well. Also, test using our kitchensink-v2 sample and larger sample apps.

2018-06-13 08:44 UTC, hansemannn commented on iphone/Classes/TiRootViewController.m
> +      [[UIApplication sharedApplication] setStatusBarOrientation:target animated:NO];
This method is deprecated in iOS 9+, we should use a wrapper to use the iOS 10+ API for newer devices.

2018-06-18 03:01 UTC, vijaysingh-axway commented
Apple has deprecated setStatusBarOrientation method in iOS9+ and haven't given any direct method to set status bar orientation. Need to check some different way to do this.

2018-09-12 14:48 UTC, hansemannn commented on iphone/Classes/TiRootViewController.m
> +      [[UIApplication sharedApplication] setStatusBarOrientation:target animated:NO];
@vijaysingh-axway Can you add the `[TiUtils isLowerThan:@"12.0"]` (or how the method was named) check to only add this workaround for iOS 11?

2018-09-13 03:50 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10104/2/artifact/dist/mobilesdk-7.5.0.v20180912203056-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-26 23:11 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10104/4/artifact/dist/mobilesdk-7.5.0.v20180926155147-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-27 06:39 UTC, merged