[TIMOB-26123] iOS: Drop iOS 8 support, use iOS 9 as the minimum target
appcelerator/titanium_mobile pull request #10103
Opened 2018-06-12 09:58 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26123

2018-06-12 10:00 UTC, build commented
<!--
  2 failure:  :disappointed_rel..., :microscope: Ther...
  0 warning: 
  2 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/hansemannn/titanium_mobile/blob/drop-ios8/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :thumbsup: Hey!, You deleted more code than you added. That's awesome!
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.4.0 test /Users/build/jenkins/workspace/dk_titanium_mobile_PR-10103-KPZS5YZBBYVNXOKRZTJQSWKCBHK5G3AF2XFRAB2ZUWDAODMTITZA
> grunt

Running "appcJs:src:lintOnly" (appcJs) task

Running "eslint:src" (eslint) task

/Users/build/jenkins/workspace/dk_titanium_mobile_PR-10103-KPZS5YZBBYVNXOKRZTJQSWKCBHK5G3AF2XFRAB2ZUWDAODMTITZA/tests/Resources/ti.builtin.addontest.js
  16:3  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  20:3  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions

✖ 2 problems (0 errors, 2 warnings)


Running "checkFormat:ios" (checkFormat) task
Fatal error: Error: Formatting incorrect on "iphone/Classes/ContactsModule.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='13635' length='5'>&#10;&#10;  </replacement>
</replacements>

Error: Formatting incorrect on "iphone/Classes/TiAppiOSSearchableIndexProxy.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='514' length='5'>&#10;  </replacement>
</replacements>

Error: Formatting incorrect on "iphone/Classes/TiContactsGroup.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='7512' length='5'>&#10;  </replacement>
<replacement offset='8431' length='5'>&#10;  </replacement>
</replacements>

Error: Formatting incorrect on "iphone/Classes/TiContactsPerson.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='24340' length='6'>&#10;&#10;  </replacement>
</replacements>

Error: Formatting incorrect on "iphone/Classes/TiUISearchBar.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='3183' length='5'>&#10;  </replacement>
</replacements>

Error: Formatting incorrect on "iphone/Classes/UIModule.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='14586' length='5'>&#10;  </replacement>
<replacement offset='14656' length='5'>&#10;  </replacement>
</replacements>

npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-13 06:44 UTC, vijaysingh-axway requested changes
We should change Deployment target to 9.0 in project.pbxproj file.
And I have left some comments also . Please fix.

2018-06-13 06:44 UTC, vijaysingh-axway commented on iphone/Classes/TiContactsPerson.m
> +  return;
No need of return.

2018-06-13 06:44 UTC, vijaysingh-axway commented on iphone/package.json
> +		"xcode": ">=7.0 <=9.x",
should be <= 10.x

2018-06-13 06:44 UTC, vijaysingh-axway commented on iphone/package.json
> +		"ios sdk": ">=9.0 <=11.x",
should be <= 12.x

2018-06-13 07:10 UTC, hansemannn commented on iphone/package.json
> +		"xcode": ">=7.0 <=9.x",
Thats handled in an own PR.

2018-06-13 07:11 UTC, hansemannn commented on iphone/package.json
> +		"ios sdk": ">=9.0 <=11.x",
Same as above.

2018-06-13 07:19 UTC, hansemannn commented
@vijaysingh-axway Updated PR

2018-06-13 08:39 UTC, hansemannn commented
@vijaysingh-axway Updated the PR, but have also put it back in progress, since I want to fix all deprecation warnings as part of this PR as well.

2018-06-13 12:32 UTC, hansemannn commented
@vijaysingh-axway I have migrated / removed all deprecated API's that was warned about in Xcode. The only remaining 4 warnings are regarding `CFReadStream*` API's that are being replaced by #9732 already.

2018-06-13 14:49 UTC, cb1kenobi commented
I'm not sure if this PR catches ALL of the Xcode 8 logic in the iOS build, but I approve the current changes to the iOS build.

2018-06-14 08:47 UTC, vijaysingh-axway requested changes
@hansemannn  I can see couple of more deprecation warnings other than CFReadStream* -
1. Deprecation in TiUIListView.m (appearanceWhenContainedIn)
2. Deprecation in MediaModule.m (UIPopoverController)
3. Deprecation in ContactsModule.m (ABAddressBookRef)

Can you please resolve them and conflicts in the branch. Thanks!

2018-06-14 09:42 UTC, hansemannn commented
Meeh, seems like Xcode cached a few warnings so they didn't show up. Filing a radar for that and updating the PR.

2018-06-14 09:47 UTC, build commented
<!--
  1 failure:  :disappointed_rel...
  0 warning: 
  2 messages
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :thumbsup: Hey!, You deleted more code than you added. That's awesome!
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.4.0 test /Users/build/jenkins/workspace/dk_titanium_mobile_PR-10103-KPZS5YZBBYVNXOKRZTJQSWKCBHK5G3AF2XFRAB2ZUWDAODMTITZA
> grunt

Running "appcJs:src:lintOnly" (appcJs) task

Running "eslint:src" (eslint) task

Running "checkFormat:ios" (checkFormat) task
Fatal error: Error: Formatting incorrect on "iphone/Classes/TiUISearchBar.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='3252' length='0'> </replacement>
<replacement offset='3253' length='1'></replacement>
<replacement offset='3273' length='1'></replacement>
</replacements>

Error: Formatting incorrect on "iphone/Classes/TiUITabGroup.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='4974' length='0'> </replacement>
<replacement offset='4975' length='1'></replacement>
<replacement offset='5002' length='1'></replacement>
<replacement offset='5097' length='0'> </replacement>
<replacement offset='5098' length='1'></replacement>
<replacement offset='5125' length='1'></replacement>
<replacement offset='5233' length='0'> </replacement>
<replacement offset='5234' length='1'></replacement>
<replacement offset='5261' length='1'></replacement>
<replacement offset='5357' length='0'> </replacement>
<replacement offset='5358' length='1'></replacement>
<replacement offset='5385' length='1'></replacement>
</replacements>

Error: Formatting incorrect on "iphone/Classes/TiViewProxy.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='729' length='26'>                 \&#10;  </replacement>
<replacement offset='797' length='12'> \&#10;    </replacement>
</replacements>

npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-14 11:42 UTC, hansemannn commented
@vijaysingh-axway Updated all remaining references and created [TIMOB-26129](https://jira.appcelerator.org/browse/TIMOB-26129) for you since you extensively worked on the `NSURLSession` API before.

2018-06-18 03:23 UTC, vijaysingh-axway approved these changes
CR approved.

2018-07-31 15:41 UTC, sgtcoolguy commented
@hansemannn I updated and rebased this PR on next branch. However, the two http client unit tests on iOS consistently fail on each rebuild.

Any ideas? This gets spit out on stderr for each:
```
[WARN] : failed, attempting to retry request...
[ERROR] : send can only be called if client is disconnected(0). Current state is 4
```

2018-08-28 18:30 UTC, sgtcoolguy commented
@hansemannn I pushed a fix for the compile error on TiUiScrollView.m, you missed removing the corresponding #endif for a macro block (you removed the #if portion).

Second, after taking a look at the Network tests that are failing, they are specifically tests which use query params. I think the changes to TiUtils.m is likely the root cause of these failures. Not sure which specific changes there yet. The most obvious place to start would be the change to TiUtils#encodeQueryPart()

2018-08-29 17:40 UTC, sgtcoolguy commented
@hansemannn I've pushed a couple changes that *should* fix the url encoding issue those tests were surfacing. The relevant change is here: 
https://github.com/appcelerator/titanium_mobile/pull/10103/commits/a2e74299dcdb285192eba67035a323e546bd0a7d

I'd love if you could come up with some idea of other tests we might want to write to cover the changes there. I think the new code is simpler and should work OK, but my first stab at it *did* uncover some broken behavior when it resolved an image file in a Ti.UI.ImageView test - it was around passing in a Ti.Filesystem.File as the "relative path" where it tries to handle special cases of paths looking like they're absolute but that should be resolved relative to the "app:" root (the Resources dir). It was basically pre-pending the resources path to the front without checking to see if the path really was an absolute path. My fix was to check if the path already had the resources path as a prefix, but maybe we should just test if the "relativePath" is really a valid absolute path and if so not try to turn it relative to the resources dir.

2018-08-30 07:13 UTC, hansemannn commented
iOS passed now:
```
1282 Total Tests: 1073 passed, 0 failed, 209 skipped.
```
and Android sometimes errors with random errors, which seem unrelated. I can write more tests around the resource handling and add those to this PR.

2018-09-11 17:00 UTC, merged