[TIMOB-26142] TiAPI: Deprecate Ti.XML
appcelerator/titanium_mobile pull request #10126
Opened 2018-06-20 13:19 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26142

2018-06-20 13:22 UTC, build commented
<!--
  2 failure:  :disappointed_rel..., :microscope: Ther...
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/hansemannn/titanium_mobile/blob/TIMOB-26142/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.4.0 test /Users/build/jenkins/workspace/dk_titanium_mobile_PR-10126-S6GXFSSGKBH4L25G6VEAO4EKWG4VAMQ6SMBYA6TVLLQVKHQGORZQ
> grunt

Running "appcJs:src:lintOnly" (appcJs) task

Running "eslint:src" (eslint) task

Running "checkFormat:ios" (checkFormat) task
Fatal error: Error: Formatting incorrect on "iphone/Classes/XMLModule.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='587' length='6'>&#10;&#10;  </replacement>
</replacements>

npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-20 13:43 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  1 messages
  1 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10126/3/artifact/dist/mobilesdk-7.4.0.v20180620062712-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.Layout | TIMOB-23372 #5 | 5.682 | Error: timeout of 5000ms exceeded |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-22 13:42 UTC, sgtcoolguy requested changes
Please use the proper compiler annotations/attributes to mark the code as deprecated.

Additionally, I think this removal/deprecation raises the issue of any other APIs which may use the xml code under the hood. Specifically, Ti.Network.HttpClient.responseXML comes to mind.

I assume that would *also* need to be deprecated/removed? Maybe it's an API addition that the native module would make if loaded up?

I don't know if we have any real usage numbers for devs using xml via that route, as I don't think our API analytics would capture it properly.

2018-06-22 13:42 UTC, sgtcoolguy commented on android/modules/xml/src/java/ti/modules/titanium/xml/XMLModule.java
> +// DEPRECATED IN SDK 8.0.0
Might as well make use of the actual @deprecated annotation available in Java: https://stackoverflow.com/questions/9031832/how-to-declare-or-mark-a-java-method-as-deprecated

```java
/**
 * @deprecated Will be removed from core SDK in 9.0.0 and moved out to a native module
 **/
@Deprecated
@Kroll.module
public class XMLModule extends KrollModule
```

2018-06-22 13:42 UTC, sgtcoolguy commented on iphone/Classes/XMLModule.m
> +    DebugLog(@"[WARN] The Ti.XML namespace has been deprecated in favor of a standalone module in SDK 8.0.0.");
We should try and use a more formal way of marking the code as deprecated too: https://stackoverflow.com/questions/1443599/how-do-i-flag-a-function-as-being-deprecated-in-an-iphone-objective-c-header-fil

So, I guess in this case that'd mean marking all of the XML module/types methods/properties in the header(s) as deprecated?

2018-06-22 13:43 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10126/5/artifact/dist/mobilesdk-7.4.0.v20180622062638-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-26 15:53 UTC, hansemannn commented
Not going to deprecate.

2018-06-26 15:53 UTC, closed without merging