[TIMOB-26201] Remove all deprecated API's
appcelerator/titanium_mobile pull request #10210
Opened 2018-07-25 07:48 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26201

> Note: I left out the Android Ti.Geolocation "legacy mode" deprecation removal. It's deprecated since 2.0.0, but the affected components are too complex to squeeze it into this PR. It should be properly removed by the Android team. I created [TIMOB-26132](https://jira.appcelerator.org/browse/TIMOB-26132) to track that.

2018-07-25 07:50 UTC, build commented
<!--
  2 failure:  :disappointed_rel..., :microscope: Ther...
  0 warning: 
  2 messages
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/hansemannn/titanium_mobile/blob/TIMOB-26201/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :thumbsup: Hey!, You deleted more code than you added. That's awesome!
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.4.0 test /Users/build/jenkins/workspace/dk_titanium_mobile_PR-10210-B7YGZXHETCPYUSB6GIM6EZ2K364HDOR2ZZW22RQFDZE3PNRO6XAA
> grunt

Running "appcJs:src:lintOnly" (appcJs) task

Running "eslint:src" (eslint) task

Running "checkFormat:ios" (checkFormat) task

Running "checkFormat:android" (checkFormat) task

Running "validate:docs" task
Warning: Docs validation failed with exit code: 1
Output: [ERROR] ./Titanium/UI/ListSection.yml
Titanium.UI.ListSection: found 6 error(s)!
	methods
		setItems
			parameters
				animation
					type
						ListViewAnimationProperties
		appendItems
			parameters
				animation
					type
						ListViewAnimationProperties
		insertItemsAt
			parameters
				animation
					type
						ListViewAnimationProperties
		replaceItemsAt
			parameters
				animation
					type
						ListViewAnimationProperties
		deleteItemsAt
			parameters
				animation
					type
						ListViewAnimationProperties
		updateItemAt
			parameters
				animation
					type
						ListViewAnimationProperties

[ERROR] Found 6 error(s)!
[ERROR] The following files have YAML syntax errors: 
[ERROR] ./Titanium/UI/ListView.yml
YAMLException: duplicated mapping key at line 952, column 5:
        type: Dictionary
        ^
 Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-07-30 13:59 UTC, hansemannn commented
@sgtcoolguy This is the last 8.0.0 PR that could mess up my Swift-setup environment at this point. Once merged, I can rebase the other one again and we have a solid iOS core.

2018-07-30 17:44 UTC, sgtcoolguy requested changes
There's a handful of changes still to be made, and I think we need to be more consistent in how we mark apis as removed or delete them.

On a related note, reviewing this makes it abundantly clear that we suck at marking methods/events/types/properties deprecated in a nice way that would make removing them easier on us in the future. We're not making use of the nice `@deprecated` annotation in Java at all here, and we're giving no tips about which version it was deprecated in. We should try and come up with some nice standard for each platform so it's as simple as doing some search and replace to find them.

2018-07-30 17:44 UTC, sgtcoolguy commented on iphone/Classes/TiCalendarCalendar.m
> -- (NSArray *)getEventsInDate:(id)arg
I don't see this as deprecated in our apidocs, and I don't think this was removed on Android...

2018-07-30 17:44 UTC, sgtcoolguy commented on iphone/Classes/TiMediaVideoPlayerProxy.m
> -        DEPRECATED_REPLACED(@"Media.VideoPlayer.preload", @"7.0.0", @"Media.VideoPlayer.load");
our apidocs do not note this as deprecated, and it seems to be supported on Android? (though looking at the impl, they just fire at the same time_.

2018-07-30 17:57 UTC, hansemannn commented
I feel like we should rework this PR and introduce a different concept:
- Leave all `removed` docs to let our developers know that something was removed
- Introduce the following "API's":
  - iOS: We already make heavy use of `DEPRECATED_REPLACED` and `DEPRECATED_REMOVED` across the SDK
  - Android: Use `@deprecated("7.0.0")` and `@removed("8.0.0")` annotations?
  - Windows: Something related to Android? (cc @infosia)

Working on this PR was not critical, only time-consuming. Let's start this over and do it right this time.

2018-07-30 17:57 UTC, closed without merging

2018-07-30 22:59 UTC, infosia commented
Added [TIMOB-26236](https://jira.appcelerator.org/browse/TIMOB-26236) to track this for Windows.