refactor(android): ScrollView now overrides toImage method
appcelerator/titanium_mobile pull request #10529
Opened 2018-12-11 16:18 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26630

**Description:**
ScrollView now passes its inner layout to the UIHelper in order to allow conversion to image of its
whole content and not only the visible part.

**Test case:**
There is a good code snippet in the JIRA ticket.

2018-12-11 16:22 UTC, build commented
<!--
  1 failure:  :disappointed_rel...
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@8.0.0 test /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-10529
> grunt

Running "appcJs:src:lintOnly" (appcJs) task

Running "eslint:src" (eslint) task

/Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-10529/tests/Resources/ti.ui.ios.tabbedbar.addontest.js
  31:38  warning  A space is required before ']'  array-bracket-spacing

✖ 1 problem (0 errors, 1 warning)
  0 errors, 1 warning potentially fixable with the `--fix` option.


Running "checkFormat:ios" (checkFormat) task

Running "checkFormat:android" (checkFormat) task
Fatal error: Error: Formatting incorrect on "android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='36971' length='1'>&#10;	</replacement>
</replacements>

npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-12-12 18:10 UTC, sgtcoolguy requested changes

2018-12-12 18:10 UTC, sgtcoolguy commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java
> +			return TiUIHelper.viewToImage(proxy.getProperties(), ((TiVerticalScrollView) scrollView).getLayout());
Why not introduce a very simple interface internally here that lists the methods common between the two implementations:
```java
public interface TiScrollView {
  public TiScrollViewLayout getLayout();
}
```

It looks like this code isn't the only place where we're doing `instanceof` checks just to cast and ask for the exact same method signature. I imagine you could clean up the code nicely by introducing it and having the `scrollView` field be declared as a `TiScrollView`.

2018-12-12 22:19 UTC, jquick-axway commented
@ypbnv, I did a quick test on iOS and that platform captures the `ScrollView` container (including the border)... and not the whole inner offscreen contents. So, the captured image will be exactly what you see onscreen.

Android and iOS have parity here. Only discrepancy I saw was that Android does not capture the border. (Minor issue, but the customer isn't applying a border so we're fine for now.)

The ticket isn't a bug. I think the person is just asking our advise on how to capture the inner contents.

2018-12-13 09:54 UTC, ypbnv commented
@sgtcoolguy Nice proposal. I will see to it.
@jquick-axway In case we have parity with iOS I am closing the PR. Thanks for checking it out!

2018-12-13 09:54 UTC, closed without merging