fix(android): resolve template compatibility with Java 9+
appcelerator/titanium_mobile pull request #10706
Opened 2019-02-15 22:23 UTC by garymathews

- Amed template for compatibility with Java 9+
- Fix building of hybrid native modules

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26826)

2019-02-15 22:47 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  3 messages
  
  DangerID: danger-id-default;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:thumbsup: Hey!, You deleted more code than you added. That's awesome!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10706/1/artifact/dist/mobilesdk-8.1.0.v20190215142518-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 2990 tests are passing.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5994a7203d126caf9d077e49d0976ba06f1e92de
</p>

2019-02-26 14:40 UTC, sgtcoolguy requested changes
Have you tested with Java <= 6 and Java 7+? We had to split the titanium_prep binaries based on JDK version due to changes in he includes or something long ago. Maybe we don't support older JDKs now? Looks to me like the app build still uses the different binaries, but the module build doesn't. So there's an issue here:
- either we can use one binary and it works (or we no longer support JDK 6-)
- or the module build needs to swap macOS binaries based own version as well

Also, why the removal of the titanium_prep exes for windows? AFAIK we still need them.

2019-02-26 19:06 UTC, garymathews commented
@sgtcoolguy We don't support Java 1.6 anymore since 1.7+ is required to build for Android (Studio also installs Java 7 by default). I have updated the `build.js` to remove this check. Also, the Windows binaries are included, they are just ~60% smaller than the previous binaries which makes them red on Github 'Files changed'.

2019-03-18 17:52 UTC, sgtcoolguy approved these changes

2019-03-21 10:46 UTC, ssjsamir approved these changes
**FR Passed** Able to build Ti.playservices and then include it in titanium application

**Test Steps**

1. Downloaded ti.playservices 
2. cd in to ti.playservices 
3. cd into Android folder 
4. Created lib folder
5. cd in to ti.playservices root
6. cd into the updater folder
7. did npm install node .
8. did npm install && node .
9. cd in to ti.playservices root
10. cd into Android folder 
11. run appc run -p android --build-only
12. added the module to a titanium application
13. added the code in to the {{app.js}}
```
const PlayServices = require('ti.playservices');

const win = Ti.UI.createWindow({ backgroundColor: 'gray' });
const btn = Ti.UI.createButton({ title: 'CHECK PLAY SERVICES' });

btn.addEventListener('click', () => {
    PlayServices.makeGooglePlayServicesAvailable((e) => {
        if (e.success) {
            alert(`Play Services: ${PlayServices.GOOGLE_PLAY_SERVICES_VERSION_CODE}`);
            // Use Play Services
        } else {
            alert(`Play Services is not available.`);
        }
    });
});

win.add(btn);
win.open();
```
14. ran the program 
15. pressed check play services 
16. version number was returned 


**Test Environment** 
```
Google pixel xl 7.1.1 sim
APPC CLI: 7.0.10
Operating System Name: Mac OS Mojave
Operating System Version: 10.14.2
Node.js Version: 8.9.1
Xcode 10.1
```

2019-03-25 15:50 UTC, merged