docs: remove docs for properties that have been removed, fix most warnings from docgen
appcelerator/titanium_mobile pull request #10711
Opened 2019-02-19 21:15 UTC by ewanharris

**JIRA:** TODO?

This PR fixes up the docs to do the following, it would be great if the initial authors of PRs associated to the changes/doc authors can review to make sure I haven't screwed up 🙂 I've tried to split the commits up so that it's a single commit per reviewable change

@garymathews Could you please take a look at the following
637312e262b062d0f9deef0a82d1628d9d199ccd - Update Geolocation docs in accordance with #10547. Keep an eye out for `// check me!` as there are still references to the removed properties (and `legacy mode`) that I'm unsure as to what to do with

@vijaysingh-axway Could you please take a look over the following
d77316f50793216fa31662e033be35cc068402c5 - Fix reference to lineBreakMode
7281537c5b1c0e5fa37c0c01097bcaa1bbd18a93 - Fix references in webview docs

@jawa9000  Could you please take a look over the following (and the others if you have time please)
2b97935687af4bd643406cde975f0dabfd9a4369 -  Correct name of contentOffset

Free for all commits 😆
7e25d1adce7d38fc16ab84bed702ba9a25314c8a - Fix typos
14ea75727d0a7bd3ad70fdd083d9ff05a997e1d9 - Adds API that referenced a class, makes doing this work much easier to know the full string to look for
feb7bbbb3bba9382acfe5234a9992801c52b8407 - Pass methods into the getter/setter generation to avoid creating invalid getters/setters

2019-02-19 21:44 UTC, build commented
<!--
  1 failure:  Tests have failed...
  1 warning:  There is no linke...
  3 messages
  1 markdown notices
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>There is no linked JIRA ticket in the PR body. Please include the URL of the relevant JIRA ticket. If you need to, you may file a ticket on <a href="https://jira.appcelerator.org/secure/CreateIssue!default.jspa">JIRA</a></td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:thumbsup: Hey!, You deleted more code than you added. That's awesome!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10711/1/artifact/dist/mobilesdk-8.1.0.v20190219131748-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:x: 1 tests have failed
There are 1 tests failing and 449 skipped out of 2990 total tests.</td>
    </tr>
  </tbody>
</table>

### Tests:

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| ios.Titanium.Media.AudioPlayer | #start, #stop | 2.011 | timeout of 2000ms exceeded |

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against feb7bbbb3bba9382acfe5234a9992801c52b8407
</p>

2019-02-19 23:10 UTC, garymathews requested changes

2019-02-19 23:10 UTC, garymathews commented on apidoc/Titanium/Geolocation/Geolocation.yml
> -  - name: PROVIDER_GPS
These providers are still present and can be used if `ti.playservices` is not included.

2019-02-26 20:15 UTC, sgtcoolguy requested changes

2019-02-26 20:15 UTC, sgtcoolguy commented on apidoc/Titanium/Android/Notification.yml
> +        you must use the [NotificationChannel.sound]Titanium.Android.NotificationChannel.sound)
Both before and after here look incorrect to me...

Is this correct?
```suggestion
        you must use the [NotificationChannel.sound](Titanium.Android.NotificationChannel.sound)
```

2019-02-26 20:15 UTC, sgtcoolguy commented on apidoc/Titanium/UI/iOS/iOS.yml
> +        Used with the `persistence` property of <Titanium.UI.WebView.setBasicAuthentication> to set the persistence level.
It's an argument, not a property.

2019-02-26 20:15 UTC, sgtcoolguy commented on apidoc/Titanium/UI/iOS/iOS.yml
> +        Used with the `persistence` property of <Titanium.UI.WebView.setBasicAuthentication> to set the persistence level.
arg, not prop

2019-02-26 20:15 UTC, sgtcoolguy commented on apidoc/Titanium/UI/iOS/iOS.yml
> +       Used with the `persistence` property of <Titanium.UI.WebView.setBasicAuthentication> to set the persistence level.
same as above

2019-02-26 20:15 UTC, sgtcoolguy commented on apidoc/Titanium/UI/iOS/iOS.yml
> +        Used with the `persistence` property of <Titanium.UI.WebView.setBasicAuthentication> to set the persistence level.
same as above

2019-02-26 20:15 UTC, sgtcoolguy commented on apidoc/Titanium/UI/iOS/iOS.yml
> +        Used to set the `injectionTime` property of <Titanium.UI.WebView.addUserScript>.
arg, not prop

2019-02-26 20:15 UTC, sgtcoolguy commented on apidoc/Titanium/UI/iOS/iOS.yml
> +        Used to set the `injectionTime` property of <Titanium.UI.WebView.addUserScript>.
arg, not prop

2019-02-28 18:07 UTC, sgtcoolguy approved these changes

2019-04-01 19:47 UTC, merged