fix(ios): Give a time delay to scroll if search view is hiding on selection
appcelerator/titanium_mobile pull request #10816
Opened 2019-03-29 22:09 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-26519

2019-03-29 22:46 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 1742 tests are passing.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 79ec3d3d40679c4e3d62b6e7e45a3cbf5e4d4699
</p>

2019-04-02 14:11 UTC, janvennemann requested changes

2019-04-02 14:11 UTC, janvennemann commented on iphone/Classes/TiUITableView.h
> +@property (nonatomic, assign) BOOL isLoaded;
Can you be more specific here with the variable name? What exactly is `isLoaded` associated with?

2019-04-02 14:11 UTC, janvennemann commented on iphone/Classes/TiUITableViewProxy.m
> +          if (idx == row)
Please use braces even for single line statements.

2019-04-11 17:53 UTC, janvennemann approved these changes

2019-04-11 17:54 UTC, janvennemann commented
@vijaysingh-axway CR passed! Can this even be unit tested? Looks like it requires user interaction.

2019-04-12 15:07 UTC, ssjsamir approved these changes
FR Passed: Tableview search no longer throws an error when going to a specific position. Tested with the following test case:
```
var win = Ti.UI.createWindow({
backgroundColor : '#fff'
});
 
var self = Ti.UI.createView({
borderRadius : 10,
backgroundColor : 'red',
});
 
win.add(self);
 
var label1 = Ti.UI.createLabel({
text : 'Este es el Titulo',
color : "#333",
font : {
fontSize : 12
}
});
 
var toolbar = Ti.UI.createToolbar({
items : [label1],
top : 0,
});
 
var tableData = [];
for (var i = 0; i <= 50; i++) {
var row = Ti.UI.createTableViewRow({
id_colu : i,
title : 'columna' + i,
height : 40
});
 
var title = Ti.UI.createLabel({
text : 'otracolu' + i,
});
 
row.add(title);
tableData.push(row);
}
 
var searchBar = Ti.UI.createSearchBar({
barColor : '#000',
showCancel : true,
height : 43,
top : 5,
filterAttribute : 'title'
});
 
var table = Ti.UI.createTableView({
data : tableData,
objName : 'table',
search : searchBar,
filterAttribute : 'title',
scrollable : true,
top : 90,
bottom : 10,
});
 
table.addEventListener('click', function(e) {
table.scrollToIndex(e.index, {
animated : false,
position : Ti.UI.iOS.TableViewScrollPosition.TOP
});
});
 
win.add(toolbar);
self.add(table);
 
win.open();
```

**Test Environment**
```
iPhone 6S+ sim(12.1)
APPC CLI: 7.0.10
Operating System Name: Mac OS Mojave
Operating System Version: 10.14.2
Node.js Version: 8.9.1
Xcode 10.1
```

2019-04-16 19:24 UTC, lokeshchdhry commented
@vijaysingh-axway , Can you please add unit test for this.

2019-04-17 19:20 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-10816/5/artifact/dist/mobilesdk-8.1.0.v20190417115930-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 3787 tests are passing.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2abbc322e5c88c3453403bbb2fa4ec52bb534109
</p>

2019-04-17 22:00 UTC, merged