[AC-6217] Android: add tabMode
appcelerator/titanium_mobile pull request #10856
Opened 2019-04-19 11:11 UTC by m1ga

**JIRA:** https://jira.appcelerator.org/browse/AC-6217

Switch between fixed and srollable tabMode:

```javascript
var win = Ti.UI.createWindow({

});
var btn1 = Ti.UI.createButton({
	title: "fixed",
	top: 5
});
var btn2 = Ti.UI.createButton({
	title: "scrollable",
	top: 60
});
win.add([btn1, btn2]);
btn1.addEventListener("click", function() {
	openTabGroup(Ti.UI.Android.TAB_MODE_FIXED);
})
btn2.addEventListener("click", function() {
	openTabGroup(Ti.UI.Android.TAB_MODE_SCROLLABLE);
})
win.open();

function openTabGroup(tabModeValue) {

	var tabs = [];

	for (var i = 0; i < 10; ++i) {
		var w = Ti.UI.createWindow({});
		var t = Ti.UI.createTab({
			window: w,
			title: 'win'
		});
		tabs.push(t);
	}

	tabGroup = Ti.UI.createTabGroup({
		tabs: tabs,
		tabMode: tabModeValue
	});
	tabGroup.open();
}
```

2019-04-19 11:28 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/m1ga/titanium_mobile/blob/tabmode/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:tada: Another contribution from our awesome community member, m1ga! Thanks again for helping us make Titanium SDK better. :thumbsup:</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 1968 tests are passing.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c66fa52e17aab2a225d8c460b1bf423ed5f090da
</p>

2019-07-30 18:10 UTC, sgtcoolguy commented
cc @ypbnv

2019-07-31 15:00 UTC, ypbnv commented on apidoc/Titanium/UI/TabGroup.yml
> +        [TAB_MODE_FIXED](Titanium.UI.Android.TAB_MODE_FIXED) is the style default style and will show all tabs at once.
One of the "style" words is redundant.

2019-07-31 15:02 UTC, ypbnv requested changes
Thank you for the contribution! Just a single comment in the documentation and it will need a bump of the version number in there - 8.1.0 should be changed to 8.3.0.

2019-07-31 15:18 UTC, m1ga commented
changed the text and the version number

2019-08-01 13:07 UTC, ypbnv commented on apidoc/Titanium/UI/Android/Android.yml
> +    since: "8.1.0"
This version number should also be 8.3.0.

2019-08-01 13:07 UTC, ypbnv commented on apidoc/Titanium/UI/Android/Android.yml
> +    since: "8.1.0"
This version number should also be 8.3.0.

2019-08-01 13:08 UTC, ypbnv commented
@m1ga Thanks! Can you update the version number in the other two places I have commented on?

2019-08-01 19:32 UTC, m1ga commented
missed them, sorry! Updated too

2019-08-02 01:27 UTC, jquick-axway commented
@m1ga, @ypbnv,

Our `TabGroup` in Titanium 7.x.x scrolled horizontally by **default**, but our new top tab style in 8.0.0 no longer scrolls without this tab mode. Which means we did not maintain the old behavior. (I didn't notice this until now, so, it got past me too.)

So, do you think we need a new "tabMode" property at all? I'm thinking we should make the top tabs scrollable by default and drop this new property if we can.

Perhaps a better question is would anyone want to use the "static" tab mode setting where it shows ellipsis if there isn't enough room for all tabs (this kind of looks bad).

2019-08-02 05:39 UTC, m1ga commented
@jquick-axway I can change the default value but it would be nice to have this option e.g. if you tabs are only some pixel too big it will be scrollable and with fixed you set it to be static.

2019-08-03 10:43 UTC, m1ga commented
I've changed the default value to scrollable again (inside the XML that caused it to be fixed: https://github.com/appcelerator/titanium_mobile/blame/1a2343d1500a47ea5adabe8a52fcc077dd4b5169/android/modules/design/res/values-land/values-land.xml)

2019-08-05 15:17 UTC, ypbnv commented
@jquick-axway , @m1ga To me it feels OK to have the default value match the old behavior ( I have no clue, why I did not pay attention to that doing the refactoring ) and have a new property exposed. I understand it does not make much sense parity-wise, but for edge cases like the one pointed out by Michael it would be useful.

And that rises a question - having a different default tabMode from the refactoring until now - which functionality would it make more sense to keep backward compatible?

2019-08-05 17:59 UTC, jquick-axway commented
The only thing that bugs me is that this new "tabMode" property only applies to Android's top tab style. It seems like a waste to me, which is why I was thinking about simplifying it. Hmm...

2019-08-20 17:07 UTC, jquick-axway commented
@m1ga, @ypbnv, does setting tab mode to "fixed" make the tabs fully span the width of the screen when in landscape mode? Or in portrait mode on a tablet? (I haven't tested this for myself yet.)

I ask because one thing that has changed as of Titanium 8.0.0 when we switched to the Java `TabLayout` class is that the top tabs do not fully fill the width of the screen in portrait mode on a tablet... versus the old tab group behavior did. I don't think it's a big deal, but there have been a couple app devs who have complained about it.

What I've seen on stackoverflow below suggests that this will do the trick...
https://stackoverflow.com/questions/30843775/tab-not-taking-full-width-on-tablet-device-using-android-support-design-widget

2019-08-22 17:32 UTC, m1ga commented
There is a difference between opening the Window in landscape mode vs turning it while open:
http://migaweb.de/20190822_192849.mp4

If you open it in portrait fixed mode and turn it it will take the whole space. If you open it in landscape fixed mode it will be centered.
Scrolling mode is always aligned to the left side

2023-06-28 19:18 UTC, m1ga commented
closing in favor of https://github.com/tidev/titanium-sdk/pull/13877

2023-06-28 19:18 UTC, closed without merging