Updated Menu.yml per TIDOC-2376
appcelerator/titanium_mobile pull request #11005
Opened 2019-06-28 15:38 UTC by jawa9000

https://jira.appcelerator.org/browse/TIDOC-2376

2019-06-28 16:00 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  2 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-11005/1/artifact/dist/mobilesdk-8.2.0.v20190628084135-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:x: 3 tests have failed
There are 3 tests failing and 464 skipped out of 3622 total tests.</td>
    </tr>
  </tbody>
</table>

### Tests:

<table><tr><th>Classname</th><th>Name</th><th>Time</th><th>Error</th></tr>
<tr><td>android.emulator.Titanium.Android</td><td>activity callbacks</td><td>7.514</td><td><pre>Error: timeout of 5000ms exceeded
at Titanium.&lt;anonymous&gt; (/ti-mocha.js:4290:23)</pre></td></tr>
<tr><td>android.emulator.Titanium.UI.TabGroup</td><td>add Map.View to TabGroup</td><td>10.002</td><td><pre>Error: timeout of 10000ms exceeded
at Titanium.&lt;anonymous&gt; (/ti-mocha.js:4290:23)</pre></td></tr>
<tr><td>ios.Titanium.Geolocation</td><td>#forwardGeocoder()</td><td>0.751</td><td><pre>Error: expected false to equal true
fail@file:///Users/build/Library/Developer/CoreSimulator/Devices/6DE1A7F7-2788-4FA8-811F-AC29E0B941E8/data/Containers/Bundle/Application/02B5365A-AADA-4FC5-9A9D-70748D91C0AD/mocha.app/node_modules/should/cjs/should.js:275:23
value@file:///Users/build/Library/Developer/CoreSimulator/Devices/6DE1A7F7-2788-4FA8-811F-AC29E0B941E8/data/Containers/Bundle/Application/02B5365A-AADA-4FC5-9A9D-70748D91C0AD/mocha.app/node_modules/should/cjs/should.js:356:23
file:///Users/build/Library/Developer/CoreSimulator/Devices/6DE1A7F7-2788-4FA8-811F-AC29E0B941E8/data/Containers/Bundle/Application/02B5365A-AADA-4FC5-9A9D-70748D91C0AD/mocha.app/ti.geolocation.test.js:257:36</pre></td></tr>
</table>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 05c67e211c3ed4770683fbbae44128db86049205
</p>

2019-07-01 15:01 UTC, sgtcoolguy requested changes
Looks like a bad insert here

2019-07-01 15:01 UTC, sgtcoolguy commented on apidoc/Titanium/Android/Menu.yml
> +                $.win.invalidateOptionsMenu(); // should be --> $.win.activity.invalidateOptionsMenu();
This doesn't look right

2019-07-30 18:33 UTC, closed without merging

2019-07-30 18:34 UTC, sgtcoolguy commented
manually fixed and merged

2019-07-30 21:15 UTC, jawa9000 commented on apidoc/Titanium/Android/Menu.yml
> +                $.win.invalidateOptionsMenu(); // should be --> $.win.activity.invalidateOptionsMenu();
Thanks for the assist, Chris.