feat(ios): expose api to use sf images
appcelerator/titanium_mobile pull request #11050
Opened 2019-07-12 23:37 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-27133

2019-07-13 00:09 UTC, build commented
<!--
  2 failure:  :microscope: Ther..., Tests have failed...
  2 warning:  Commit <a href="h..., Commit <a href="h...
  4 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/vijaysingh-axway/titanium_mobile/blob/TIMOB-27133/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Commit <a href="https://api.github.com/repos/appcelerator/titanium_mobile/commits/6d31046257196aa751ed98a0f728606d6dae60ab">6d31046257196aa751ed98a0f728606d6dae60ab</a> has a message "chore(ios) : Added support for Xcode 11 / iOS 13 dev environment" giving 2 errors:
- subject may not be empty
- type may not be empty
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Commit <a href="https://api.github.com/repos/appcelerator/titanium_mobile/commits/e5bd9fc9dd2a72dae983bde75502d892f80ab92f">e5bd9fc9dd2a72dae983bde75502d892f80ab92f</a> has a message "feat(iOS): Removed IS_XCODE_9 constants from code" giving 2 errors:
- scope must be lower-case
- subject must not be sentence-case, start-case, pascal-case, upper-case
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:thumbsup: Hey!, You deleted more code than you added. That's awesome!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-11050/1/artifact/dist/mobilesdk-8.2.0.v20190712164411-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:x: 1 tests have failed
There are 1 tests failing and 470 skipped out of 3728 total tests.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :rotating_light: This PR has one or more commits with warnings/errors for commit messages not matching our configuration. You may want to squash merge this PR and edit the message to match our conventions, or ask the original developer to modify their history.
  </td>
    </tr>
  </tbody>
</table>

### Tests:

<table><tr><th>Classname</th><th>Name</th><th>Time</th><th>Error</th></tr>
<tr><td>ios.Titanium.Database</td><td>#executeAllAsync() does not allow DB to be GC'd</td><td>30.003</td><td><pre>Error: timeout of 30000ms exceeded
file:///Users/build/Library/Developer/CoreSimulator/Devices/29E1514E-93D8-4A4B-A306-F232955340BA/data/Containers/Bundle/Application/B9CD3660-26F1-4A87-9FE9-95C7DDD735F6/mocha.app/ti-mocha.js:4290:32</pre></td></tr>
</table>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 57c2021e31b5f88c73e6e0e10cea656557a3404f
</p>

2019-07-23 16:29 UTC, janvennemann requested changes

2019-07-23 16:29 UTC, janvennemann commented on apidoc/Titanium/UI/iOS/iOS.yml
> +        More details on SF Symbols can be found from https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview.
```suggestion
        More details on SF Symbols can be found on https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview.
```

2019-07-23 16:29 UTC, janvennemann commented on apidoc/Titanium/UI/iOS/iOS.yml
> +        Get image from SF Symbol provided by Apple.
```suggestion
        Get image from SF Symbols provided by Apple.
```

2019-07-23 16:29 UTC, janvennemann commented on apidoc/Titanium/UI/iOS/iOS.yml
> +        can get the inbuilt SF Symbol name.
```suggestion
        use it to lookup the inbuilt SF Symbol name.
```

2019-07-24 13:25 UTC, janvennemann approved these changes
LGTM!

2019-07-24 13:26 UTC, janvennemann commented
@vijaysingh-axway please add a unit test for the new api, thanks!

2019-08-20 13:49 UTC, ssjsamir approved these changes
FR Passed: Able to make use of sf images, using the following test case: 
```
var win = Ti.UI.createWindow({
backgroundColor: '#fff'
});
var triangle = Ti.UI.iOS.systemImage('drop.triangle.fill');
var forward = Ti.UI.iOS.systemImage('forward');
var backward = Ti.UI.iOS.systemImage('backward');
var folder = Ti.UI.iOS.systemImage('folder.fill');
 
 
var imageView = Ti.UI.createImageView({
width: '150',
height: '150',
image: triangle,
tintColor: 'red'
});
 
 
var button = Ti.UI.createButton({
top: 60,
width: 100,
height: 50,
//backgroundImage: folder
image: folder
})
 
var stepper = Ti.UI.iOS.createStepper({
top: 150,
incrementImage: forward,
decrementImage: backward
});
 
 
win.add(button);
win.add(stepper);
win.add(imageView);
win.open();
```

**Test Environment**
```
MacOS Mojave version 10.14.4
Xcode 11 beta 5
Node.js ^8.11.1
iPhone 8 (13.0 Sim)
"NPM":"4.2.14","CLI":"7.1.1-master.2"
```

2019-08-22 08:36 UTC, hansemannn commented
Can this be merged please?

2019-08-22 10:38 UTC, hansemannn commented
@vijaysingh-axway @janvennemann @ssjsamir There was an issue with device builds, since the `TiBlob` class was not imported properly. This is fixed via https://github.com/vijaysingh-axway/titanium_mobile/pull/4 which has Vijays fork as the head, so once merged it should appear here.

2019-08-22 16:47 UTC, vijaysingh-axway commented
Thanks @hansemannn . Merged.

2019-08-22 17:48 UTC, hansemannn commented
We also see issues with this when using it in conditional code, even with Alloy.Globals constants. Can you reproduce it in Alloy?

2019-08-29 19:54 UTC, merged