fix(android): fix gradient background support for CardView
appcelerator/titanium_mobile pull request #11219
Opened 2019-09-16 14:14 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/[TICKET]

**Description:**
Fix support of Gradient background for Ti.UI.Android.CardView. Refactor the assigning of nativeView for TiUICardView in order to avoid duplicated execution of `processProperties()`. Add some "removed" properties in the docs and remove the color/image states properties. They are currently bugged, but I would not want to expand the scope of this PR.
Note: No unit tests, since this is a bug that is only visual. All the View's events are triggered but it remains invisible.

This PR's test case would be good to be ran again, since there are changes in the code it added:
https://github.com/appcelerator/titanium_mobile/pull/10045 

**Test case:**
_app.js_
```
var win = Ti.UI.createWindow();
var cardView = Ti.UI.Android.createCardView({
	width: 200,
	height: 200,
		backgroundGradient: {
		type: 'linear',
		colors: ['red', 'green'],
		startPoint: { x: '50%', y: 0 },
		endPoint: { x: '50%', y: '100%' },
		backFillStart: false
	},
});

win.add(cardView);
win.open();

```

2019-09-16 14:33 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  3 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-11219/1/artifact/dist/mobilesdk-8.3.0.v20190916071620-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 4336 tests are passing.
(There are 471 tests skipped)
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 27be3967b386bb45de0da4bbf05eea14cc1f39d0
</p>

2019-09-16 17:53 UTC, garymathews requested changes
You also need to update the statements in:
```Java
@Override
public void propertyChanged(String key, Object oldValue, Object newValue, KrollProxy proxy) {
...
```
To use `this.cardView`, add `PROPERTY_BACKGROUND_GRADIENT` handling and remove properties handled by the parent class.

2019-09-17 12:10 UTC, ypbnv commented
Updated with the changes in `propertyChanged()`. Also extracted setting the gradient background and extended the test case.

2019-09-17 17:22 UTC, hansemannn commented
@ypbnv Unfortunately, with this patch the `borderRadius` is not respected anymore.  Everything else seems to work fine. Bonus: A ripple effect would be good to work, but thats okay not to.

2019-09-20 11:58 UTC, ypbnv commented
Gradient background does not work together with CardView's border radius. From what I have found this is a problem in native Android as well, unfortunately. Setting any drawable as a background besides the internal RoundRectDrawable will break the corner radius of the native view.

Setting the PR as work in progress because I am still trying to somehow work around this limitation.

As a workaround for now I would suggest creating a "container" view with the desired background gradient and width and height set to Ti.UI.FILL. Putting it as the first child in a CardView and adding any other content to it. Not the best solution performance-wise, but it would allow usage of gradient and border radius.

2019-09-21 13:07 UTC, hansemannn commented
It works good! One note: If you also pass a `backgroundColor`, it will not work.

2019-09-21 15:45 UTC, hansemannn commented
Unfortunately it broke the `backgroundColor` usage completely:
```js
var win = Ti.UI.createWindow();

var cardView = Ti.UI.Android.createCardView({
	width: 200,
	height: 200,
	borderRadius: 100,
	backgroundColor: '#333'
});

win.add(cardView);
win.open();
```
This should render a circle, but it renders a square, since the `borderRadius` is ignored when combined with a `backgroundColor`.

2019-09-21 15:46 UTC, hansemannn commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUICardView.java
> +		if (d.containsKeyAndNotNull(TiC.PROPERTY_BACKGROUND_GRADIENT)) {
@ypbnv This is what broke it I think. You should handle both background-colors and background-gradients.

2022-03-21 21:50 UTC, hansemannn commented
Closing for now due to open issues with backwards compatibility and merge conflicts.

2022-03-21 21:50 UTC, closed without merging