fix(ios): select a valid ios sim xcodebuild destination
appcelerator/titanium_mobile pull request #11228
Opened 2019-09-18 06:06 UTC by cb1kenobi

The desired iOS simulator's runtime may be associated with a different Xcode than the one building with, so simply pick any simulator that is compatible with the Xcode building the app since it won't matter when ioslib laucnhes the selected iOS Simulator.

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27338

2019-09-18 06:15 UTC, build commented
<!--
  0 failure: 
  1 warning:  :mag: Can't find ...
  1 messages
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :mag: Can't find junit reports at `./junit.*.xml`, skipping generating JUnit Report.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8b3e71ee375f55e9ed53a3b5eb59135084a941b2
</p>

2019-09-18 09:30 UTC, ewanharris requested changes
I'm seeing a similar crash as Jenkins is locally, changing the code as commented appears to fix the crash

2019-09-18 09:30 UTC, ewanharris commented on iphone/cli/commands/_build.js
> +		for (const sim of Object.values(this.iosInfo.simulators.ios)) {
`this.iosInfo.simulators.ios` is an object with the following structure
```
{
	'13.0': [ // array of sims ],
	'12.4': [ // array of sims ]
}
```

I think this wants to be something like the below
```js
for (const [ runtime, sims ] of Object.entries(this.iosInfo.simulators.ios)) {
	for (const sim of sims) {
		if (sim.supportsXcode[xcodeId]) {
			dest = `platform=iOS Simulator,id=${sim.udid},OS=${appc.version.format(sim.version, 2, 2)}`;
			break;
		}
	}
}
```

2019-09-24 14:53 UTC, ewanharris approved these changes
Looks good to me!

2019-09-25 21:40 UTC, ssekhri commented
@cb1kenobi when trying to run a classic project on iOS 13 simulator, using XCode 11, I get the following error in both studio and cli
```
[INFO] :   Invoking xcodebuild
[DEBUG] :  Invoking: DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build -target testClassic -configuration Debug -scheme testClassic -derivedDataPath /Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic/build/iphone/DerivedData -UseNewBuildSystem=YES OBJROOT=/Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic/build/iphone/build/Intermediates SHARED_PRECOMPS_DIR=/Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic/build/iphone/build/Intermediates/PrecompiledHeaders SYMROOT=/Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic/build/iphone/build/Products -destination "platform=iOS Simulator,id=441204EF-B8B5-4829-ADDA-F9141902FB23,OS=10.3" ONLY_ACTIVE_ARCH=1 APPC_PROJECT_DIR=/Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic
[TRACE] :  User defaults from command line:
[TRACE] :      IDEDerivedDataPathOverride = /Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic/build/iphone/DerivedData
[TRACE] :      UseNewBuildSystem = YES
[TRACE] :  Build settings from command line:
[TRACE] :      APPC_PROJECT_DIR = /Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic
[TRACE] :      OBJROOT = /Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic/build/iphone/build/Intermediates
[TRACE] :      ONLY_ACTIVE_ARCH = 1
[TRACE] :      SHARED_PRECOMPS_DIR = /Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic/build/iphone/build/Intermediates/PrecompiledHeaders
[TRACE] :      SYMROOT = /Users/ssekhri/Documents/Appcelerator_Studio_Workspace/testClassic/build/iphone/build/Products
[ERROR] :  xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[ERROR] :  		{ platform:iOS Simulator, id:441204EF-B8B5-4829-ADDA-F9141902FB23, OS:10.3 }
[ERROR] :  	The requested device could not be found because no available devices matched the request.
[ERROR] :  	Available destinations for the "testClassic" scheme:
[ERROR] :  		{ platform:iOS Simulator, id:476F296D-E2F6-40A0-B0C8-5D476FA70520, OS:10.3.1, name:iPad (5th generation) }
[ERROR] :  		{ platform:iOS Simulator, id:D2E9BE3F-9952-4FFF-BBB2-C316568A5CCB, OS:11.0.1, name:iPad (5th generation) }
[ERROR] :  		{ platform:iOS Simulator, id:DEA27542-9EE9-4226-B3DE-EAC5D0A38A81, OS:11.2, name:iPad (5th generation) }
[ERROR] :  		{ platform:iOS Simulator, id:B4E094E6-B70F-4A44-90C2-D1FB7C8EA8AF, OS:11.3, name:iPad (5th generation) }
[ERROR] :  		{ platform:iOS Simulator, id:5957845E-C101-4DFA-B8CA-56B987D3E555, OS:12.2, name:iPad (5th generation) }
[ERROR] :  		{ platform:iOS Simulator, id:B8D476C9-AEB0-4440-BDFB-CD96402438FA, OS:12.2, name:iPad (6th generation) }
[ERROR] :  		{ platform:iOS Simulator, id:A06532C4-3CB1-42DA-ADB6-EA9F0347799C, OS:9.3, name:iPad 2 }
[ERROR] :  		{ platform:iOS Simulator, id:E2644C01-3BA8-4D3C-9A1A-E3C8264433F7, OS:9.3, name:iPad Air }
[ERROR] :  		{ platform:iOS Simulator, id:9AE43734-6717-4762-9A1F-0993EFBFC80C, OS:10.0, name:iPad Air }
[ERROR] :  		{ platform:iOS Simulator, id:7DC09A42-8762-4BC0-B001-F422B21EDC9C, OS:10.3.1, name:iPad Air }
[ERROR] :  		{ platform:iOS Simulator, id:CD6B65A5-6805-4C09-AD59-B0133E85B2B0, OS:11.0.1, name:iPad Air }
[ERROR] :  		{ platform:iOS Simulator, id:84EAF295-F891-4968-8C3D-C3BC8769099C, OS:11.2, name:iPad Air }
[ERROR] :  		{ platform:iOS Simulator, id:F29990FF-624D-4C80-8F4B-D52D0896878D, OS:11.3, name:iPad Air }
[ERROR] :  		{ platform:iOS Simulator, id:351D7E45-9F0D-4C24-BF79-8C936481AF3A, OS:12.2, name:iPad Air }
[ERROR] :  		{ platform:iOS Simulator, id:089CDD53-07E6-4BF6-9952-DB1FD8C55D67, OS:12.2, name:iPad Air (3rd generation) }
[ERROR] :  		{ platform:iOS Simulator, id:CD862665-076A-40B1-9079-1EA81D96A4F0, OS:13.0, name:iPad Air (3rd generation) }
[ERROR] :  		{ platform:iOS Simulator, id:1C936B35-9355-4FB1-A628-6C7EE1F3E7EC, OS:9.3, name:iPad Air 2 }
[ERROR] :  		{ platform:iOS Simulator, id:9F7DB60B-F2D8-432E-B2E6-D3E19C04C468, OS:10.0, name:iPad Air 2 }
[ERROR] :  		{ platform:iOS Simulator, id:866120D8-9568-4F53-9BF4-9DD35A7B5755, OS:10.3.1, name:iPad Air 2 }
[ERROR] :  		{ platform:iOS Simulator, id:623D41A8-0CAA-4BF5-9302-180CE5B46F29, OS:11.0.1, name:iPad Air 2 }
[ERROR] :  		{ platform:iOS Simulator, id:1DF6B3A0-5833-43C2-8C02-B59650AEB46A, OS:11.2, name:iPad Air 2 }
[ERROR] :  		{ platform:iOS Simulator, id:5E5749DD-9732-4E04-BD44-3EDF63BBBAC3, OS:11.3, name:iPad Air 2 }
[ERROR] :  		{ platform:iOS Simulator, id:3EF1989B-ECE8-4454-8BF2-B7C1C7D3DE38, OS:12.2, name:iPad Air 2 }
[ERROR] :  		{ platform:iOS Simulator, id:328543A5-3255-46AB-95C7-7DC82D65ABB3, OS:9.3, name:iPad Pro }
[ERROR] :  		{ platform:iOS Simulator, id:0B4980A8-1C81-41C0-9721-AF39F4D7B800, OS:10.0, name:iPad Pro (9.7 inch) }
[ERROR] :  		{ platform:iOS Simulator, id:801BE701-F1A5-4C66-9DFD-94319CCDA548, OS:10.3.1, name:iPad Pro (9.7 inch) }
[ERROR] :  		{ platform:iOS Simulator, id:973392CA-B7D2-48E7-9CD7-BB0A3C3350AA, OS:11.0.1, name:iPad Pro (9.7-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:077B6D23-14EC-4E83-BA9E-2F223FDDE105, OS:11.2, name:iPad Pro (9.7-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:0A253233-B4E6-4398-B61F-06BB7087E7BF, OS:11.3, name:iPad Pro (9.7-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:F1906364-7DAE-4740-AB2E-7FE1414C66AD, OS:12.2, name:iPad Pro (9.7-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:1AAE8920-E6C3-4F3B-B1C8-5A7C87A7E273, OS:13.0, name:iPad Pro (9.7-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:88831FF6-BBE7-4AAC-9071-B10015E2062C, OS:10.3.1, name:iPad Pro (10.5-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:83E9AE15-18BE-49FB-833E-E0EEC2FF527D, OS:11.0.1, name:iPad Pro (10.5-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:977BD9AA-D4E1-40CA-B587-EE2259B29991, OS:11.2, name:iPad Pro (10.5-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:1B1C29A1-0D25-4139-A2B4-D37FEED6E922, OS:11.3, name:iPad Pro (10.5-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:E91D8B22-367B-4AE3-868E-A800215A387B, OS:12.2, name:iPad Pro (10.5-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:9711C31E-4119-46CD-8FDD-B61E2A40DADE, OS:12.2, name:iPad Pro (11-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:C06AB6B4-2CCF-456C-8167-A68EE2AF79BB, OS:13.0, name:iPad Pro (11-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:830413C9-A11E-4ED3-B4FA-192F04300D0B, OS:10.0, name:iPad Pro (12.9 inch) }
[ERROR] :  		{ platform:iOS Simulator, id:A4059A09-21F5-4EB8-AB58-762C8FB7E5BD, OS:10.3.1, name:iPad Pro (12.9 inch) }
[ERROR] :  		{ platform:iOS Simulator, id:48C69495-FBC1-4CD8-B4E6-C5BAC1DB0ECF, OS:11.0.1, name:iPad Pro (12.9-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:3EA44D3D-6CCB-452E-B397-90077A8852A9, OS:11.2, name:iPad Pro (12.9-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:5AA4B631-5BDC-4F0C-BE2E-8DEB92785490, OS:11.3, name:iPad Pro (12.9-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:78E99A35-2795-4A63-9752-CA4DABD0A0DC, OS:12.2, name:iPad Pro (12.9-inch) }
[ERROR] :  		{ platform:iOS Simulator, id:A6184F11-1A7A-4C1A-9D52-C0C4FE931AD1, OS:10.3.1, name:iPad Pro (12.9-inch) (2nd generation) }
[ERROR] :  		{ platform:iOS Simulator, id:079B5DA0-3057-481D-8633-8EF896C589AB, OS:11.0.1, name:iPad Pro (12.9-inch) (2nd generation) }
[ERROR] :  		{ platform:iOS Simulator, id:459650D9-BA88-4F0D-99EA-A10170D8BF60, OS:11.2, name:iPad Pro (12.9-inch) (2nd generation) }
[ERROR] :  		{ platform:iOS Simulator, id:16EE9324-FDBF-45F1-B4E1-FDEB00BCF83C, OS:11.3, name:iPad Pro (12.9-inch) (2nd generation) }
[ERROR] :  		{ platform:iOS Simulator, id:881BDF37-1F1E-4332-85C3-24B39E8B2A96, OS:12.2, name:iPad Pro (12.9-inch) (2nd generation) }
[ERROR] :  		{ platform:iOS Simulator, id:328A554B-6671-440B-B11C-2D5B4B57D6F4, OS:12.2, name:iPad Pro (12.9-inch) (3rd gen [...]

2019-09-25 22:10 UTC, cb1kenobi commented
@ssekhri I don't believe it. Did you download the CI build or build from source? If from source, did you do an `npm install`? Please ensure you have selected the correct SDK in the tiapp.xml. Can you verify the ioslib version in the SDK is 1.7.14.

2019-09-25 23:06 UTC, ssekhri commented
@cb1kenobi I got the build from the CI. Got the builds again from Jenkins for master and 8_2_X PRs and ensured that the ioslib version is 1.7.14. Same results with SDk builds from both the branch.
I tried on another machine which was just setup new and only XCode 11 has been installed. Didn't see the issue on that machine.
So it might be a scenario that exists on my current macbook which has had different versions of XCode and simulators installed and deleted. Let me know if any further information from my machine could help identify the problem.

2019-09-26 22:10 UTC, ssekhri commented
@cb1kenobi tested the PR further. Noticed couple fo scenarios.
The test environment on the macbook had two XCode's under the Applications. The XCode 11 as XCode.app and XCode 10.3 as XCode10. The system has iOS simulators for version 13.0, 12.4 and 12.2.
**Issue 1:**
Step 1: With selected XCode as 11.0 ran a classic project on iOS simulator 13.0 successfully.
Step 2: Next switch the selected XCode to Xcode10.3. Build the project to iOS sim 12.4.  Fails with the logs as below:
```
[TRACE] ** BUILD SUCCEEDED **
[INFO]  Finished building the application in 15s 556ms
[INFO]  Launching iOS Simulator
[TRACE] [ioslib] Selected iOS Simulator: iPhone 8
[TRACE] [ioslib]   UDID    = 095A759C-F3AB-4FA9-9B63-F0AF7E10D33C
[TRACE] [ioslib]   iOS     = 12.4
[TRACE] [ioslib] Autoselected Xcode: 10.3
[TRACE] [ioslib] Checking if the simulator /Applications/Xcode10.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator is already running
[TRACE] [ioslib] Simulator is not running
[TRACE] [ioslib] Tailing iPhone 8 Simulator system log: /Users/satyamsekhri/Library/Logs/CoreSimulator/095A759C-F3AB-4FA9-9B63-F0AF7E10D33C/system.log
[TRACE] [ioslib] Running: /Applications/Xcode10.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator -CurrentDeviceUDID 095A759C-F3AB-4FA9-9B63-F0AF7E10D33C
[TRACE] [ioslib] iPhone 8 Simulator has exited with code 0
[TRACE] [ioslib] Exited with code: 0
```

**Issue 2:**
Step 1: With selected XCode as 10.3 ran a cleaned up classic project on iOS simulator 12.4 successfully.
Step 2:  Now try to run the same project on iOS simulator 12.2. It hangs during the simulator launch stage with logs as below:
```
[TRACE] ** BUILD SUCCEEDED **
[INFO]  Finished building the application in 14s 284ms
[INFO]  Launching iOS Simulator
[TRACE] [ioslib] Selected iOS Simulator: iPhone Xʀ
[TRACE] [ioslib]   UDID    = 9C5D0B01-26FC-4916-9E6C-505F2CE96BC7
[TRACE] [ioslib]   iOS     = 12.2
[TRACE] [ioslib] Autoselected Xcode: 10.3
[TRACE] [ioslib] Checking if the simulator /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator is already running
[TRACE] [ioslib] Simulator is not running
[TRACE] [ioslib] Tailing iPhone Xʀ Simulator system log: /Users/satyamsekhri/Library/Logs/CoreSimulator/9C5D0B01-26FC-4916-9E6C-505F2CE96BC7/system.log
[TRACE] [ioslib] Running: /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator -CurrentDeviceUDID 9C5D0B01-26FC-4916-9E6C-505F2CE96BC7
```
Step 3: Again try to build the project to iOS simulator 12.2. On the second attempt the project build successfully to the 12.2 sim.
Step 4: Now try to build the project to the iOS simulator 12.4 (same as in step 1). It fails. The logs are similar as in Issue 1.

2019-10-07 20:35 UTC, ssekhri commented
FR Passed. Concurrent builds on iOS simulator work fine. Apart from couple of scenarios that seem to be specific to one system the iOS simulator builds work fine.
Verified On:
Mac OS: 10.14.5
SDK: 8.3.0.v20190927124747
Appc CLI: 7.1.1
JDK: 1.8.0_162
Node: 10.5.0
Studio: 5.1.4.201909061933
Xcode: 11.0, 10.3
Device: iOS simulator 13.0, 12.4, 12.2

2019-10-09 15:14 UTC, merged