docs: add Ti.UI.View.id property
appcelerator/titanium_mobile pull request #11353
Opened 2019-11-20 15:26 UTC by drauggres

Property `id` of `Ti.UI.View` is not documented.

2019-11-20 15:37 UTC, drauggres commented
Since we already have `Ti.UI.View.getViewById` method, I think it wouldn't be wrong to consider `id` property as a legal part of the API.

2019-11-20 15:56 UTC, build commented
<!--
  1 failure:  Tests have failed...
  1 warning:  There is no linke...
  4 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>There is no linked JIRA ticket in the PR body. Please include the URL of the relevant JIRA ticket. If you need to, you may file a ticket on <a href="https://jira.appcelerator.org/secure/CreateIssue!default.jspa">JIRA</a></td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-11353/1/artifact/dist/mobilesdk-9.0.0.v20191120073005-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:tada: Another contribution from our awesome community member, drauggres! Thanks again for helping us make Titanium SDK better. :thumbsup:</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:x: 2 tests have failed
There are 2 tests failing and 709 skipped out of 7334 total tests.</td>
    </tr>
  </tbody>
</table>

### Tests:

<table><tr><th>Classname</th><th>Name</th><th>Time</th><th>Error</th></tr>
<tr><td>android.emulator.Titanium.Network.Socket.TCP</td><td>#connect() and receive data</td><td>49.03</td><td><pre>Error: done() invoked with non-Error: [object Object]
at /ti-mocha.js:6535:53959
      at TCP.error (/ti.network.socket.tcp.test.js:107:1)</pre></td></tr>
<tr><td>android.emulator.Titanium.UI.WebView</td><td>userAgent</td><td>30.007</td><td><pre>Error: timeout of 30000ms exceeded
at Titanium.&lt;anonymous&gt; (/ti-mocha.js:6535:53723)</pre></td></tr>
</table>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 846f820f3356012ca449039348c720b02b1e9f55
</p>

2019-11-21 15:33 UTC, sgtcoolguy requested changes
small tweak to doc text.

This looks good to me. We don't have specialized methods for this property, but as you state we have `getViewById` which makes use of the optional `id` property. It should likely be official API.

2019-11-21 15:33 UTC, sgtcoolguy commented on apidoc/Titanium/UI/View.yml
> +        The `id` property of the Ti.UI.View represents the view's identifier. The identificator string does
```suggestion
        The `id` property of the Ti.UI.View represents the view's identifier. The identifier string does
```

2019-11-21 15:38 UTC, merged