fix(ios): updated behaviour to original
appcelerator/titanium_mobile pull request #11354
Opened 2019-11-20 20:47 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-27350

2019-11-20 21:23 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/vijaysingh-axway/titanium_mobile/blob/TIMOB-27350_1/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 2352 tests are passing.
(There are 231 skipped tests not included in that total)
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 19b4e05f9da7094668bda31b35d320c8a5cb869a
</p>

2019-11-21 20:13 UTC, sgtcoolguy approved these changes
LGTM

2019-11-21 20:22 UTC, sgtcoolguy requested changes
Generally LGTM, but then I dug deeper...

I think we could fairly easily automate a test for this. Originally my understanding was that a Ti.Blob's toString() method returned it's text value. But I did not consider binary blobs.

So my guess here for the behavior is that if the Blob contains text, toString() should return that, and if it contains binary bytes, it should return `"[object TiBlob]"` . In fact, this is exactly what Android's implementation attempts to do. 

And in further looking, iOS's TiBlob has a `description` method that more or less does the same thing. That appears to be how "old" proxies handled toString() on IOS.

So I think we need to:
- Remove the TiBlob.m `description` method
- Add this JS-based fix as you have it
- add some unit tests for TiBlob that test when:
  - the blob has empty string content
  - the blob has ascii/text content
  - the blob has binary content

2019-11-22 21:03 UTC, vijaysingh-axway commented
@sgtcoolguy 
1. API description is used internally. It is not exposed to developers.  It is overridden from NSObject to log proper data while using Ti.API. See [here](https://github.com/appcelerator/titanium_mobile/blob/b295e6321ba38e29612b51d93c1518e87e6fffee/iphone/TitaniumKit/TitaniumKit/Sources/API/APIModule.m#L43). When [newArray componentsJoinedByString:@" "] get called, it looks fro description of every object inside newArray. I think we should not remove it.
2. Unit tests added.

2019-12-10 19:45 UTC, sgtcoolguy commented on tests/Resources/ti.blob.addontest.js
> +	afterEach(function (done) {
There's no need for this hook as none of the tests open a window...

2019-12-10 20:06 UTC, sgtcoolguy approved these changes
LGTM, pushed modified commits to have messages match convention and remove the unnecessary test hook.  Tests kind of do FR for QE, but should probably double-check with the original ticket's use case.

2019-12-12 13:58 UTC, ssjsamir approved these changes
**FR Passed:** Tested using the the test case mentioned in https://jira.appcelerator.org/browse/TIMOB-27350 able to see data received as a blon
`[INFO]   Received Data: [object TiBlob] `

**Test Environment**
```
MacOS Catalina 10.15.1 beta
Xcode 11.3
Node.js 10.16.3
"NPM":"4.2.15-1","CLI":"7.1.2-7"
iPhone 8 (ios 13.3)
```

2019-12-16 18:13 UTC, merged