iOS: remove Ti.Network.TCPSocket
appcelerator/titanium_mobile pull request #11362
Opened 2019-11-21 21:36 UTC by sgtcoolguy

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27619

**Optional Description:**
We have kept around `Ti.Network.TCPSocket` since SDK 1.7 because it's used by the bonjour service code on iOS. (The new class is `Ti.Network.Socket.TCP`)

This PR attempts to finally remove it.

The issue is that I have no experience with the bonjour APIs so I do not know how to tell if I broke this horribly. From my dumb testing, I can browse services on my Wifi LAN (2 printers and a media server via DLNA), but I can't seem to actually connect to them (`BonjourService.resolve()`). It's unclear if I'm doing something wrong, broke the code, or it's possibly a regression we introduced when moving to main thread.

Test code:
```javascript
/**
 * This file is used to validate iOS test-cases. It is ran using the Xcode
 * project in titanium_mobile/iphone/iphone/Titanium.xcodeproj.
 *
 * Change the below code to fit your use-case. By default, it included a button
 * to trigger a log that is displayed in the Xcode console.
 */

var win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

var btn = Ti.UI.createButton({
    title: 'Trigger'
});

btn.addEventListener('click', function() {
    Ti.API.info('Hello world!');
    // Create the Bonjour Browser (looking for http)
    // See more Bonjour Types here: https://developer.apple.com/library/mac/qa/qa1312/_index.html
    const httpBonjourBrowser = Ti.Network.createBonjourBrowser({
        serviceType : '_http._tcp',
        domain : 'local'
    });

    // Handle updated services
    httpBonjourBrowser.addEventListener('updatedservices', function (e) {
        for (const service of e.services) {
            console.log(service.name);
            console.log(service.domain);
            console.log(service.type);
            console.log(service.isLocal);
            console.log(service.socket);
            service.resolve();
            console.log(service.socket);
        }
    });

    // Start searching
    httpBonjourBrowser.search();
});

win.add(btn);
win.open();
```

I haven't tried with code I found at https://github.com/rborn/Advanced-Titanium-Tutorial---Bonjour-Networking/blob/master/Resources/bj.js

2019-11-21 22:02 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  1 warning:  Commit <a href="h...
  4 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/sgtcoolguy/titanium_mobile/blob/TIMOB-27619/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Commit <a href="https://api.github.com/repos/appcelerator/titanium_mobile/commits/f04b45f3ca3e6456481532bc8cbe3fc0a741904b">f04b45f3ca3e6456481532bc8cbe3fc0a741904b</a> has a message "docs(network): add updateddomains event to BonjourService, legacy TCP socket removed" giving 1 errors:
- header must not be longer than 72 characters, current length is 84
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:thumbsup: Hey!, You deleted more code than you added. That's awesome!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-11362/1/artifact/dist/mobilesdk-9.0.0.v20191121134116-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :rotating_light: This PR has one or more commits with warnings/errors for commit messages not matching our configuration. You may want to squash merge this PR and edit the message to match our conventions, or ask the original developer to modify their history.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 6625 tests are passing.
(There are 709 skipped tests not included in that total)
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e68c9d94eb84ebc1fef3289c844205f3c554566d
</p>

2019-11-22 15:58 UTC, sgtcoolguy commented
OK, after digging deeper - my changes definitely didn't cause the issue. Looks to be a main thread related issue: https://jira.appcelerator.org/browse/TIMOB-27076

Basically the bonjour APIs had locks on the main thread to wait for the service resolution (or publish/etc) to occur before returning (making the API sync).

As soon as I commented out the lock wait, it worked. The issue is that the API then becomes async and we'd need to fire an event to notify of success/failure to resolve/publish/etc. I don't know if we can explicitly run the resolution/publish off the main thread to "fix" this.

2019-11-26 13:40 UTC, janvennemann commented
+1 on the Node style callbacks for the new async versions of mentioned functions. Since we are investing so much effort to increase node compatibility, our own API should also go this way (or promise as you already mentioned).

@sgtcoolguy judging by the PR description, i guess you last comment is obsolete now, and you already addressed that issue?

2019-12-02 20:10 UTC, sgtcoolguy commented
For now I'm keeping both events *and* optional callbacks, so you can pick or choose which way to deal with things. I'd prefer callbacks myself, but most of our APIs are event based so it feels odd not to provide that for now.

2019-12-06 19:39 UTC, vijaysingh-axway requested changes
Few changes required as mentioned in comments.

2019-12-06 20:12 UTC, sgtcoolguy commented on iphone/Classes/TiNetworkBonjourServiceProxy.m
> +  NSNetServicesError code = [errorDict valueForKey:NSNetServicesErrorCode];
`NSNetServicesError` is an enum of type `NSInteger`, so I don't think we need to do this.

2019-12-06 20:24 UTC, sgtcoolguy commented
@vijaysingh-axway Pushed another commit to address your feedback (and another issue I saw internally with setSocket)

2019-12-06 20:52 UTC, vijaysingh-axway approved these changes
CR passed.

2019-12-09 19:09 UTC, lokeshchdhry commented
FR Passed.

Checked above code with different `service type` & checked if `Titanium.Network.Socket.TCP` is affected.

Looks good.

Studio Ver:       6.0.0.201911251516
SDK Ver:          9.0.0 local build
OS Ver:           10.14.5
Xcode Ver:        Xcode 11.2.1
Appc NPM:         5.0.0-2
Appc CLI:         7.1.2
Daemon Ver:       1.1.3
Ti CLI Ver:       5.2.2
Alloy Ver:        1.14.4
Node Ver:         12.13.1
NPM Ver:          6.12.1
Java Ver:         11.0.1
IOS Simulator:    ⇨ iPhone 11 Pro Max (iOS-13-2)

2019-12-09 19:09 UTC, merged