docs(android): correctly document uncaughtException payload
appcelerator/titanium_mobile pull request #11388
Opened 2019-12-10 21:24 UTC by garymathews

- Fix parity issues between iOS and Android with `uncaughtException` payload

##### TEST CASE
```JS
Ti.App.addEventListener('uncaughtException', e => {
    console.log(JSON.stringify(e, null, 4));
});
throw Error('Exception!');
```
- `column`, `stack` and `nativeStack` should exist on both iOS and Android

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27632)

2019-12-10 21:26 UTC, build commented
<!--
  1 failure:  :disappointed_rel...
  1 warning:  :mag: Can't find ...
  2 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :mag: Can't find junit reports at `./junit.*.xml`, skipping generating JUnit Report.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@9.0.0 test /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11388
> npm run ios-sanity-check && npm run lint


> titanium-mobile@9.0.0 ios-sanity-check /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11388
> ./build/scons check-ios-toplevel


> titanium-mobile@9.0.0 lint /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11388
> npm-run-all --parallel lint:**


> titanium-mobile@9.0.0 lint:js /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11388
> eslint .


> titanium-mobile@9.0.0 lint:docs /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11388
> tdoc-validate ./apidoc


> titanium-mobile@9.0.0 lint:ios /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11388
> clang-format-lint $npm_package_config_format_ios


> titanium-mobile@9.0.0 lint:android /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11388
> clang-format-lint $npm_package_config_format_android

[INFO] Global: OK!
[INFO] Global.JSON: OK!
[INFO] Global.String: OK!
[INFO] Global.console: OK!
[INFO] Modules.Cloud.ACLs: OK!
[INFO] CloudACLsResponse: OK!
[INFO] CloudACLsCheckResponse: OK!
[INFO] Modules.Cloud.Chats: OK!
[INFO] CloudChatsResponse: OK!
[INFO] CloudChatGroupsResponse: OK!
[INFO] Modules.Cloud.Checkins: OK!
[INFO] CloudCheckinsResponse: OK!
[INFO] Modules.Cloud.Clients: OK!
[INFO] CloudClientsResponse: OK!
[INFO] Modules.Cloud: OK!
[INFO] CloudStreamProgress: OK!
[INFO] CloudResponse: OK!
[INFO] Modules.Cloud.Emails: OK!
[INFO] CloudEmailsResponse: OK!
[INFO] Modules.Cloud.Events: OK!
[INFO] CloudEventsResponse: OK!
[INFO] CloudEventOccurrencesResponse: OK!
[INFO] Modules.Cloud.Files: OK!
[INFO] CloudFilesResponse: OK!
[INFO] Modules.Cloud.Friends: OK!
[INFO] CloudFriendsResponse: OK!
[INFO] CloudFriendRequestsResponse: OK!
[INFO] Modules.Cloud.GeoFences: OK!
[INFO] CloudGeoFenceResponse: OK!
[INFO] Modules.Cloud.KeyValues: OK!
[INFO] CloudKeyValuesResponse: OK!
[INFO] Modules.Cloud.Likes: OK!
[INFO] CloudLikesResponse: OK!
[INFO] Modules.Cloud.Messages: OK!
[INFO] CloudMessagesResponse: OK!
[INFO] Modules.Cloud.Objects: OK!
[INFO] CloudObjectsResponse: OK!
[INFO] Modules.Cloud.PhotoCollections: OK!
[INFO] CloudPhotoCollectionsResponse: OK!
[INFO] CloudPhotoCollectionsPhotosResponse: OK!
[INFO] Modules.Cloud.Photos: OK!
[INFO] CloudPhotosResponse: OK!
[INFO] Modules.Cloud.Places: OK!
[INFO] CloudPlacesResponse: OK!
[INFO] Modules.Cloud.Posts: OK!
[INFO] CloudPostsResponse: OK!
[INFO] Modules.Cloud.PushNotifications: OK!
[INFO] CloudPushNotificationsResponse: OK!
[INFO] CloudPushNotificationsQueryChannelResponse: OK!
[INFO] CloudPushNotificationsShowChannelResponse: OK!
[INFO] CloudPushNotificationsQueryResponse: OK!
[INFO] Modules.Cloud.PushSchedules: OK!
[INFO] CloudPushSchedulesResponse: OK!
[INFO] Modules.Cloud.Reviews: OK!
[INFO] CloudReviewsResponse: OK!
[INFO] Modules.Cloud.SocialIntegrations: OK!
[INFO] CloudSocialIntegrationsResponse: OK!
[INFO] Modules.Cloud.Statuses: OK!
[INFO] CloudStatusesResponse: OK!
[INFO] Modules.Cloud.Users: OK!
[INFO] CloudUsersSecureDialog: OK!
[INFO] CloudUsersResponse: OK!
[INFO] CloudUsersSecureResponse: OK!
[INFO] Modules.CloudPush: OK!
[INFO] CloudPushNotificationConfig: OK!
[INFO] CloudPushNotificationSuccessArg: OK!
[INFO] CloudPushNotificationErrorArg: OK!
[INFO] Modules: OK!
[INFO] Titanium.API: OK!
[INFO] Titanium.Accelerometer: OK!
[INFO] Titanium.Analytics: OK!
[INFO] Titanium.Android.ActionBar: OK!
[INFO] Titanium.Android.Activity: OK!
[INFO] ActivityResult: OK!
[INFO] Titanium.Android: OK!
[INFO] ServiceIntentOptions: OK!
[INFO] RequestPermissionAccessResult: OK!
[INFO] Titanium.Android.BigPictureStyle: OK!
[INFO] Titanium.Android.BigTextStyle: OK!
[INFO] Titanium.Android.BroadcastReceiver: OK!
[INFO] Titanium.Android.Calendar.Alert: OK!
[INFO] Titanium.Android.Calendar: OK!
[INFO] CalendarPermissionResponse: OK!
[INFO] Titanium.Android.Calendar.Calendar: OK!
[INFO] Titanium.Android.Calendar.Event: OK!
[INFO] Titanium.Android.Calendar.Reminder: OK!
[INFO] Titanium.Android.Intent: OK!
[INFO] Titanium.Android.Menu: OK!
[INFO] Titanium.Android.MenuItem: OK!
[INFO] Titanium.Android.Notification: OK!
[INFO] wakeLockOptions: OK!
[INFO] Titanium.Android.NotificationChannel: OK!
[INFO] Titanium.Android.NotificationManager: OK!
[INFO] Titanium.Android.PendingIntent: OK!
[INFO] Titanium.Android.QuickSettingsService: OK!
[INFO] showParams: OK!
[INFO] Titanium.Android.R: OK!
[INFO] Titanium.Android.RemoteViews: OK!
[INFO] Titanium.Android.Service: OK!
[INFO] Titanium.App.Android: OK!
[INFO] Titanium.App.Android.R: OK!
[ERROR] ./apidoc/Titanium/App/App.yml
Titanium.App: found 1 error(s)!
	events
		uncaughtException
			properties
				backtrace
					Invalid key(s) in Titanium.App: removed

[INFO] launchOptions: OK!
[INFO] Titanium.App.Properties: OK!
[INFO] Titanium.App.iOS.BackgroundService: OK!
[INFO] Titanium.App.iOS.LocalNotification: OK!
[INFO] Titanium.App.iOS.SearchQuery: OK!
[INFO] Titanium.App.iOS.SearchableIndex: OK!
[INFO] Titanium.App.iOS.SearchableItem: OK!
[INFO] Titanium.App.iOS.SearchableItemAttributeSet: OK!
[INFO] Titanium.App.iOS.UserActivity: OK!
[INFO] Titanium.App.iOS.UserDefaults: OK!
[INFO] Titanium.App.iOS.UserNotificationAction: OK!
[INFO] Titanium.App.iOS.UserNotificationCategory: OK!
[INFO] Titanium.App.iOS.UserNotificationCenter: OK!
[INFO] UserNotificationCallbackResponse: OK!
[INFO] UserNotificationDictionary: OK!
[INFO] GetUserNotificationSettings: OK!
[INFO] Titanium.App.iOS: OK!
[INFO] NotificationParams: OK!
[INFO] UserNotificationAttachment: OK!
[INFO] LaunchOptionsType: OK!
[INFO] UserNotificationSettings: OK!
[INFO] Titanium.Blob: OK!
[INFO] ImageAsCroppedDict: OK!
[INFO] Titanium.BlobStream: OK!
[INFO] Titanium.Buffer: OK!
[INFO] Titanium.BufferStream: OK!
[INFO] Titanium.Calendar.Alert: OK!
[INFO] Titanium.Calendar.Attendee: OK!
[INFO] Titanium.Calendar: OK!
[INFO] EventsAuthorizationResponse: OK!
[INFO] Titanium.Calendar.Calendar: OK!
[INFO] Titanium.Calendar.Event: OK!
[INFO] Titanium.Calendar.RecurrenceRule: OK!
[INFO] daysOfTheWeekDictionary: OK!
[INFO] recurrenceEndDictionary: OK!
[INFO] Titanium.Calendar.Reminder: OK!
[INFO] Titanium.Codec: OK!
[INFO] EncodeNumberDict: OK!
[INFO] DecodeNumberDict: OK!
[INFO] EncodeStringDict: OK!
[INFO] DecodeStringDict: OK!
[INFO] Titanium.Contacts: OK!
[INFO] showContactsParams: OK!
[INFO] ContactsAuthorizationResponse: OK!
[INFO] Titanium.Contacts.Group: OK!
[INFO] Titanium.Contacts.Person: OK!
[INFO] Titanium.Database.DB: OK!
[INFO] BatchQueryError: OK!
[INFO] PossibleBatchQueryError: OK!
[INFO] Titanium.Database: OK!
[INFO] Titanium.Database.ResultSet: OK!
[INFO] ErrorResponse: OK!
[INFO] SuccessResponse: OK!
[INFO] FailureResponse: OK!
[INFO] Titanium.Event: OK!
[INFO] Titanium.Filesystem.File: OK!
[INFO] Titanium.Filesystem.FileStream: OK!
[INFO] Titanium.Filesystem: OK!
[INFO] RequestStorageAccessResult: OK!
[INFO] Titanium.Geolocation.Android: OK!
[INFO] Titanium.Geolocation.Android.LocationProvider: OK!
[INFO] Titanium.Geolocation.Android.LocationRule: OK!
[INFO] Ti [...]

2019-12-10 21:46 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  3 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-11388/2/artifact/dist/mobilesdk-9.0.0.v20191210133119-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 6668 tests are passing.
(There are 700 skipped tests not included in that total)
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4965bc07dc87da925d7224d617daaab82ba65184
</p>

2019-12-11 18:30 UTC, sgtcoolguy requested changes
Should include pointers to the "new" properties in the docs.

2019-12-11 18:30 UTC, sgtcoolguy commented on apidoc/Titanium/App/App.yml
> +          since: "9.0.0"
add `notes: Use stack property for cross-platform parity`

2019-12-11 18:30 UTC, sgtcoolguy commented on apidoc/Titanium/App/App.yml
> +          since: "9.0.0"
add `notes: Use column property for cross-platform parity`

2019-12-11 18:30 UTC, sgtcoolguy commented on apidoc/Titanium/App/App.yml
> +          since: "9.0.0"
add `notes: Use nativeStack property for cross-platform parity`

2019-12-11 18:30 UTC, sgtcoolguy commented on apidoc/Titanium/App/App.yml
> +        since: "9.0.0"
I assume technically it was present earlier for iOS?

2019-12-12 13:53 UTC, sgtcoolguy approved these changes

2019-12-20 17:27 UTC, lokeshchdhry commented
@garymathews , I don't see `nativeStack` for IOS. Ran it on IOS sim.

2020-01-07 17:56 UTC, sgtcoolguy commented
To echo @lokeshchdhry iOS is showing `stackTrace` in this manual test case where you'd expect `nativeStack`.

2020-01-07 18:09 UTC, sgtcoolguy commented
I just pushed a fix for the issue @lokeshchdhry and I noted. The uncaughtException now reports the native stack trace as `nativeStack`, not `stackTrace` for the provided test case above. (it also properly provides the `column` and `line` values now too). Ready to re-test for FR @lokeshchdhry

2020-01-07 18:40 UTC, lokeshchdhry commented
FR Passed.

`column`, `stack` and `nativeStack` exists on both iOS and Android.

Studio Ver:       6.0.0.201911251516
SDK Ver:          9.0.0 local build
OS Ver:           10.14.5
Xcode Ver:        Xcode 11.3
Appc NPM:         5.0.0-2
Appc CLI:         7.1.2
Daemon Ver:       1.1.3
Ti CLI Ver:       5.2.2
Alloy Ver:        1.14.4
Node Ver:         12.13.1
NPM Ver:          6.12.1
Java Ver:         11.0.1
Android Devices:  ⇨ google Pixel (Android 10)
IOS Simulator:    ⇨ iPhone 11 Pro Max iOS 13.3

2020-01-07 19:06 UTC, merged