docs: update Ti.Android.R and Ti.App.Android.R docs
appcelerator/titanium_mobile pull request #11492
Opened 2020-02-21 08:18 UTC by drauggres

In docs before this PR:
1. `R` described as both: `R` property of `Ti.Android` and class `R` (in `Ti.Android` namespase) that extends `Ti.Proxy`
2. Same for `R` in `Ti.App.Android`
3. [Documentation](https://docs.appcelerator.com/platform/latest/#!/api/Titanium.App.Android.R) for `Ti.App.Android.R` was almost empty.

This PR should fix these problems.

Required for correct fix for https://github.com/appcelerator/docs-devkit/issues/29.

2020-02-21 08:39 UTC, build commented
<!--
  0 failure: 
  1 warning:  There is no linke...
  4 messages
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>There is no linked JIRA ticket in the PR body. Please include the URL of the relevant JIRA ticket. If you need to, you may file a ticket on <a href="https://jira.appcelerator.org/secure/CreateIssue!default.jspa">JIRA</a></td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-11492/1/artifact/dist/mobilesdk-9.1.0.v20200221001945-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:tada: Another contribution from our awesome community member, drauggres! Thanks again for helping us make Titanium SDK better. :thumbsup:</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 6419 tests are passing.
(There are 702 skipped tests not included in that total)
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 15162bc6a3c942a8c36ea30ce0bd27042211bec4
</p>

2020-03-03 17:49 UTC, janvennemann requested changes
Left a few notes on some phrasing. I would also like keep the type defined as `Titanium.Android.R` instead of renaming it to `RProxy`. See my comment in the the related PR on the docs-devkit how we could handle that.

2020-03-04 09:35 UTC, drauggres commented
@janvennemann Thanks for review. 
There are two problems in the generated `.d.ts`:
1. Properties of the `Ti.Android.R` are defined as properties of the instance (not static), so they are not available (e.g. `Ti.Android.R.drawable` will not work).
2. `Ti.App.Android.R` don't have any properties (except inherited from `Ti.Proxy`)

First problem could be solved in the generator solely. But the second couldn't, we need to change the docs.
Currently in docs there are 4 `R`s: 2 constants and 2 classes in `Ti.App.Android` and `Ti.Android` namespaces, but in the code there are only 3 `R`: 2 properties and single `RProxy`, so these changes reflect the actual state.
We can use `R` name for the common class (instead of `RProxy), naming does not really matter, but we can't use `Ti.Android.R` because it is also type of `Ti.App.Android.R` (anyway this common class/interface will not be exported from the module and only used internally as type for the `R` properties).

2020-03-04 10:00 UTC, drauggres commented on apidoc/Titanium/App/Android/Android.yml
> +        Starting in Titanium SDK 7.3.0, this API exposes all Android related R classes
I removed `Starting in Titanium SDK 7.3.0 ...`, but `To access ..` should stay (I also added similar line to `Ti.Android.R` description).

2020-03-04 10:01 UTC, drauggres commented on apidoc/common/RProxy.yml
> +    using its integer id, as follows:
fixed

2020-03-04 10:06 UTC, drauggres commented on apidoc/Titanium/App/Android/Android.yml
> +        integer id, as follows.
> Not sure why it mentions an integer id here, but resource name should be the correct phrasing.

fixed

> Also, please reformat the newlines on this paragraph so it uses up to 80 characters on each line.

Done.
P.S. It doesn't seem like we have 80 characters limit in the docs, most likely 100.

2020-03-04 10:07 UTC, drauggres commented on apidoc/Titanium/Android/Android.yml
> +    type: RProxy
Changed to `R`, explanation below in the comment.

2020-03-04 11:09 UTC, janvennemann commented on apidoc/Titanium/App/Android/Android.yml
> +        integer id, as follows.
Yeah, we don't really have a character limit. The 80 characters are more of a guideline.

2020-03-04 11:18 UTC, janvennemann commented
@drauggres We should be able to have `Titanium.Android.R` as both a value and a type, TypeScript supports that. Here's what i think needs to be done to solve this:

- Get rid of the additional R.yml under titanium/app/android (as you already did). Change the type of the `R` property in titanium/Android.yml to the existing `Titanium.Android.R`.
- Keep the R.yml under titanium/android with it's existing name `Titanium.Android.R`
- Change the TypeScript generator so it declares `Titanium.Android.R` as an interface instead of a namespace. Since TypeScript treats namespaces as values and interfaces as types, we can have both the `R` property on the `Titanium.Android` namespace, as well as the type definition `Titanium.Android.R` as an interface.

2020-03-04 11:23 UTC, drauggres commented
>Keep the R.yml under titanium/android with it's existing name Titanium.Android.R

Then we'll have `Ti.Android.R` as type of `Ti.App.Android.R`. Don't you find it a bit confusing?

2020-03-04 11:41 UTC, janvennemann commented
@drauggres No not really. As you said it is solely used internally to provide typing information. There is no way to create this type so users only access it through the properties `Ti.Android.R` and `Ti.App.Android.R`. With your updated summaries on the type and the properties, it should make it clear what's what.

Type:

> The Titanium binding of the native Android `R` class, giving access to Android system-wide resources **or** application resources.

And then the property definitions state:

Titanium.Android.R

> Accessor for Android **system resources**.

Titanium.App.Android.R

> The `R` namespace for **application resources**

2020-03-04 12:28 UTC, drauggres commented
- `R` moved back to `Titanium.Android.R`.
- Type of `Ti.App.Android.R` changed to `Ti.Android.R`.

2020-03-05 11:06 UTC, janvennemann approved these changes

2020-03-05 11:31 UTC, merged