fix(android): obtain holder for module references
appcelerator/titanium_mobile pull request #11498
Opened 2020-02-25 00:15 UTC by garymathews

- Obtain module instance when holder cannot be found.

##### TEST CASE
```JS
const permissions = Ti.Filesystem.requestStoragePermissions;
 
// Attempt to call 'requestStoragePermissions'.
permissions(e => {
    if (e.success) {
        console.log('Storage permissions granted.');
        return;
    }
    console.warn('Storage permissions denied.');
});
```
- Should see a console log regarding storage permissions.
- Should not see
```
Couldn't obtain argument holder
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27777)

2020-02-25 00:36 UTC, build commented
<!--
  1 failure:  Test suite crashe...
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Test suite crashed on iOS simulator. Please see <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-11498/1/artifact/mocha_2020-01-31-063250_macos-rocket.crash">the crash log</a> for more details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 3 tests are passing.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 58b0a569be92cb2d8506c957883f868a8ab17957
</p>

2020-04-02 15:34 UTC, sgtcoolguy requested changes

2020-04-02 15:34 UTC, sgtcoolguy commented on android/kroll-apt/src/main/resources/org/appcelerator/kroll/annotations/generator/ProxyBinding.fm
> +			holder = moduleInstance.Get(isolate);
seems like you'd need to do another `if` check like above here after trying the module instance? I think it *shouldn't* ever be empty/null, but who knows. We don't want to simply hard crash if it ever is...

2020-04-14 17:35 UTC, jquick-axway approved these changes
CR: Pass

2020-04-14 19:11 UTC, ssekhri commented
FR Passed.
Don't see the error "Couldn't obtain argument holder"
The permission is requested on the device and log message are seen based on allow/reject of permission.
Verified on:
Mac OS: 10.15.4
SDK: 9.1.0.v20200413125029
Appc CLI: 8.0.0
JDK: 11.0.4
Node: 10.17.0
Studio: 6.0.0.202003181504
Device: Pixel3(v10.0) emulator

2020-04-14 19:59 UTC, merged