fix(ios): use searchtextfield exposed in iOS 13 to set color
appcelerator/titanium_mobile pull request #11494
Opened 2020-02-21 23:49 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-27754

2020-02-21 23:54 UTC, build commented
<!--
  2 failure:  :microscope: Ther..., :disappointed_rel...
  1 warning:  :mag: Can't find ...
  2 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/vijaysingh-axway/titanium_mobile/blob/TIMOB-27754/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :mag: Can't find junit reports at `./junit.*.xml`, skipping generating JUnit Report.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@9.1.0 test /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11494
> npm run ios-sanity-check && npm run lint


> titanium-mobile@9.1.0 ios-sanity-check /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11494
> ./build/scons check-ios-toplevel


> titanium-mobile@9.1.0 lint /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11494
> npm-run-all --parallel lint:**


> titanium-mobile@9.1.0 lint:android /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11494
> clang-format-lint $npm_package_config_format_android


> titanium-mobile@9.1.0 lint:docs /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11494
> tdoc-validate ./apidoc


> titanium-mobile@9.1.0 lint:ios /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11494
> clang-format-lint $npm_package_config_format_ios


> titanium-mobile@9.1.0 lint:js /Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-11494
> eslint .

./apidoc/Global/Console/Console.yml
	methods[log].parameters[message].type - Please define a new type rather than using the generic Object/Dictionary references: Object
	methods[info].parameters[message].type - Please define a new type rather than using the generic Object/Dictionary references: Object
	methods[warn].parameters[message].type - Please define a new type rather than using the generic Object/Dictionary references: Object
	methods[error].parameters[message].type - Please define a new type rather than using the generic Object/Dictionary references: Object
	methods[debug].parameters[message].type - Please define a new type rather than using the generic Object/Dictionary references: Object
	methods[timeLog].parameters[data].type - Please define a new type rather than using the generic Object/Dictionary references: Object

./apidoc/Global/Global.yml
	methods[require].returns - Please define a new type rather than using the generic Object/Dictionary references: Object

./apidoc/Global/JSON/JSON.yml
	methods[stringify].parameters[value].type - Please define a new type rather than using the generic Object/Dictionary references: Object
	methods[parse].returns - Please define a new type rather than using the generic Object/Dictionary references: Object

./apidoc/Modules/Cloud/ACLs/ACLs.yml
	methods[create].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[update].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[show].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[remove].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[addUser].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[removeUser].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[checkUser].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary

./apidoc/Modules/Cloud/ACLs/ACLs.yml
	properties[acls].type - Please define a new type rather than using the generic Object/Dictionary references: Array<Dictionary>

./apidoc/Modules/Cloud/ACLs/ACLs.yml
	properties[permission].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary

./apidoc/Modules/Cloud/Chats/Chats.yml
	methods[create].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[remove].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[getChatGroups].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[queryChatGroups].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[query].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary

./apidoc/Modules/Cloud/Chats/Chats.yml
	properties[chats].type - Please define a new type rather than using the generic Object/Dictionary references: Array<Dictionary>

./apidoc/Modules/Cloud/Chats/Chats.yml
	properties[chat_groups].type - Please define a new type rather than using the generic Object/Dictionary references: Array<Dictionary>

./apidoc/Modules/Cloud/Checkins/Checkins.yml
	methods[create].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[query].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[remove].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[show].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary

./apidoc/Modules/Cloud/Checkins/Checkins.yml
	properties[checkins].type - Please define a new type rather than using the generic Object/Dictionary references: Array<Dictionary>

./apidoc/Modules/Cloud/Clients/Clients.yml
	methods[geolocate].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary

./apidoc/Modules/Cloud/Clients/Clients.yml
	properties[location].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary

./apidoc/Modules/Cloud/Cloud.yml
	methods[sendRequest].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary
	methods[createX509CertificatePinningSecurityManager].parameters[params].type - Please define a new type rather than using the generic Object/Dictionary references: Array<Dictionary>

./apidoc/Modules/Cloud/CloudResponse.yml
	properties[meta].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary

./apidoc/Modules/Cloud/Emails/Emails.yml
	methods[send].parameters[parameters].type - Please define a new type rather than using the generic Object/Dictionary references: Dictionary

./apidoc/Modules/Cloud/Events/Events.yml
	methods[create].param [...]

2020-02-24 15:05 UTC, janvennemann requested changes
Just some notes about code formatting. Please use property accessor where possible ;)

2020-02-24 15:05 UTC, janvennemann commented on iphone/Classes/TiUISearchBar.m
> +          UISearchTextField *textField = [[self searchBar] searchTextField];
```suggestion
          UISearchTextField *textField = self.searchBar.searchTextField;
```

2020-02-24 15:05 UTC, janvennemann commented on iphone/Classes/TiUISearchBar.m
> +    [[UITextField appearanceWhenContainedInInstancesOfClasses:@ [[UISearchBar class]]] setAttributedPlaceholder:placeholder];
```suggestion
    [[UITextField appearanceWhenContainedInInstancesOfClasses:@[UISearchBar.class] setAttributedPlaceholder:placeholder];
```

2020-02-24 15:05 UTC, janvennemann commented on iphone/Classes/TiUISearchBar.m
>      [[[self searchBar] searchTextField] setTextColor:[[TiUtils colorValue:value] _color]];
```suggestion
    self.searchBar.searchTextField.textColor = [TiUtils colorValue:value]._color;
```

2020-02-24 15:05 UTC, janvennemann commented on iphone/Classes/TiUISearchBar.m
> +          [textField setAttributedPlaceholder:placeholder];
```suggestion
          textField.attributedPlaceholder = placeholder;
```

2020-02-24 20:13 UTC, vijaysingh-axway commented
@janvennemann Updated!

2020-02-25 08:51 UTC, janvennemann approved these changes

2020-03-02 15:19 UTC, nguyen8427 commented
hello, is it possible to put this fixed in 8.3 or 8.4 release?

2020-03-05 11:25 UTC, janvennemann approved these changes

2020-03-18 11:13 UTC, ssaddique commented
FR partially passed. See JIRA ticket for more details.

2020-03-20 15:31 UTC, ssaddique commented
**FR Passed**. See JIRA ticket for details. PR ready to be merged.

2020-03-20 16:10 UTC, merged