fix(android): allow TiDownloadManager to fire fail listener
appcelerator/titanium_mobile pull request #11575
Opened 2020-03-26 23:41 UTC by garymathews

- Allow `TiDownloadManager` to fire fail listener, which prevented `error` events for some components

##### TEST CASE
```JS
const win = Ti.UI.createWindow();
const img = Ti.UI.createImageView({
	image: 'https://invalid.host.com/image.jpg'
});

img.addEventListener('error', e => {
	console.error(JSON.stringify(e, null, 4));
});

win.add(img);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27797)

2020-03-27 00:00 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  4 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/garymathews/titanium_mobile/blob/TIMOB-27797/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:thumbsup: Hey!, You deleted more code than you added. That's awesome!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-11575/1/artifact/dist/mobilesdk-9.1.0.v20200326164248-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 6633 tests are passing.
(There are 699 skipped tests not included in that total)
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2d6c811c59a961aecfc28cbf2751bc96d925e661
</p>

2020-04-02 15:26 UTC, sgtcoolguy commented
@garymathews Can you please turn that manual test into a mocha test? It looks like it should be pretty straightforward to convert...

2020-04-15 01:16 UTC, jquick-axway requested changes

2020-04-15 01:16 UTC, jquick-axway commented on android/titanium/src/java/org/appcelerator/titanium/util/TiDownloadManager.java
> +	public InputStream blockingDownload(final URI uri) throws Exception
We need to update the `@return` comment since it no longer returns `null` if failed to download.

2020-04-15 01:16 UTC, jquick-axway commented on android/titanium/src/java/org/appcelerator/titanium/util/TiDownloadManager.java
The above `if (TiApplication.isUIThread()) { ... }` code block should be changed to throw an exception too for consistency. This code block can be tested when setting a Titanium view's `backgroundImage` property.

How about something like this?
```java
// If running on main UI thread, then block this thread while doing download on another thread.
// Note: Using "HttpUrlConnection" on UI thread will cause a "NetworkOnMainThreadException" to be thrown.
if (TiApplication.isUIThread()) {
	// Provides the error result of the threaded-out runnable below.
	class RunnableResult
	{
		Exception exception;
	}

	// Perform the blocking download on another thread.
	// Downloaded content will be made available via Titanium's "TiResponseCache".
	final RunnableResult runnableResult = new RunnableResult();
	Thread thread = new Thread(new Runnable() {
		@Override
		public void run()
		{
			try (InputStream stream = blockingDownload(uri)) {
				if (stream != null) {
					KrollStreamHelper.pump(stream, null);
				}
			} catch (Exception ex) {
				runnableResult.exception = ex;
			}
		}
	});
	thread.start();
	thread.join();
	if (runnableResult.exception != null) {
		throw runnableResult.exception;
	}

	// Return a stream to the downloaded file/content via our response cache.
	URI cachedUri = TiResponseCache.fetchEndpointFollowingRedirects(uri);
	if (cachedUri != null) {
		inputStream = TiResponseCache.openCachedStream(cachedUri);
	}
	return inputStream;
}
```

2020-04-15 18:24 UTC, garymathews commented
@jquick-axway Updated PR

2020-04-15 19:33 UTC, jquick-axway approved these changes
CR: Pass

2020-04-15 19:35 UTC, jquick-axway commented
@garymathews, using `AtomicReference` to box the exception was a smart idea. I like it. And you're the first person to add a Java lambda to our codebase. 👍

2020-04-24 13:36 UTC, ssjsamir approved these changes
FR passed: Able to see the correct events being fired, tested with the test case above and the following test case: 
```
Ti.UI.setBackgroundColor('#000');

var tabGroup = Ti.UI.createTabGroup();

var win1 = Ti.UI.createWindow({
    title:'Tab 1',
    backgroundColor:'#fff',
});

var img = Ti.UI.createImageView({
	image:'http://files.daddyhunt.com/sites/default/files/imagecache/mangrid-212/photos/z/z/z/277606/Photo_on_2010-09-14_at_13.14_3.jpg'
});
win1.add(img);
img.addEventListener('error', function(){
    Ti.API.info('--------------fired error event----------');
});

tabGroup.addTab(Ti.UI.createTab({
    title:'Tab 1',
    window:win1
}));
tabGroup.open();
```

**Test Environment**

**MacOS Catalina: 10.15.5 Beta 
Xcode: 11.4
Java Version: 1.8.0_131
Android NDK: 21.1.6273396-beta2
Node.js: 10.16.3
""NPM":"5.0.0-1","CLI":"8.0.0-master.10""
Pixel Xl 7.1.1 Sim**

2020-04-28 13:42 UTC, merged