docs: updated tls version support for iOS
appcelerator/titanium_mobile pull request #11754
Opened 2020-06-04 22:16 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-26959

2020-06-04 22:46 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  2 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:x: 1 tests have failed
There are 1 tests failing and 467 skipped out of 4418 total tests.</td>
    </tr>
  </tbody>
</table>

### Tests:

<table><tr><th>Classname</th><th>Name</th><th>Time</th><th>Error</th></tr>
<tr><td>android.emulator.Titanium.Android</td><td>activity callbacks (9)</td><td>5.005</td><td><pre>Error: timeout of 5000ms exceeded
at Titanium.&lt;anonymous&gt; (/ti-mocha.js:6535:53120)</pre></td></tr>
</table>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9fea7dc02086b100f10f232ed72e8a6fbecb856c
</p>

2020-06-08 14:28 UTC, janvennemann requested changes

2020-06-08 14:28 UTC, janvennemann commented on apidoc/Titanium/Network/HTTPClient.yml
> +    In android, use the <Titanium.Network.HTTPClient.tlsVersion> property to set the version of the TLS protocol
```suggestion
    On Android, use the <Titanium.Network.HTTPClient.tlsVersion> property to set the version of the TLS protocol
```

2020-06-08 14:28 UTC, janvennemann commented on apidoc/Titanium/Network/HTTPClient.yml
> +    In iOS, add `NSExceptionMinimumTLSVersion` key in plist section of tiapp.xml to set minimum TLS version.
```suggestion
    On iOS, add the `NSExceptionMinimumTLSVersion` key in the `<plist>` section of `tiapp.xml` to set a minimum TLS version. 
```

2020-06-08 14:28 UTC, janvennemann commented on apidoc/Titanium/Network/HTTPClient.yml
> +    See following example-
```suggestion
    See following example:
```

The examples also feels kind of redundant. I think only the last one should be enough. Also make sure to use proper indentation and fenced code blocks.

```
    ```
    <key>NSAppTransportSecurity</key>
    <dict>
      <key>NSExceptionDomains</key>
      <dict>
        <key>www.appcelerator.com</key>
        <dict>
          <key>NSExceptionMinimumTLSVersion</key>
          <string>TLSv1.3</string>
        </dict>
      </dict>
    </dict>
    ```
```

2020-06-08 14:28 UTC, janvennemann commented on apidoc/Titanium/Network/HTTPClient.yml
> +        behavior for that android versions.
```suggestion
        behavior for that Android versions.
```

2020-06-09 23:10 UTC, vijaysingh-axway commented
@janvennemann  Addressed review comments.

2020-06-25 16:25 UTC, janvennemann approved these changes

2020-07-01 19:01 UTC, ssekhri commented
FR Passed.

2020-07-06 14:58 UTC, merged