fix(iOS): set parent view controller for detached view controllers
appcelerator/titanium_mobile pull request #12233
Opened 2020-10-30 01:11 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-28209
https://jira.appcelerator.org/browse/TIMOB-27865

2020-10-30 01:26 UTC, build commented
<!--
  2 failure:  :microscope: Ther..., Tests have failed...
  0 warning: 
  3 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/vijaysingh-axway/titanium_mobile/blob/AC-6615/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-12233/1/artifact/dist/mobilesdk-9.3.0.v20201029181315-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:x: 9 tests have failed
There are 9 tests failing and 989 skipped out of 12251 total tests.</td>
    </tr>
  </tbody>
</table>

### Tests:

<table><tr><th>Classname</th><th>Name</th><th>Time</th><th>Error</th></tr>
<tr><td>ios.macos.Titanium.Blob</td><td>image dimensions should be reported in pixels (10.15.7)</td><td>0.003</td><td><pre>Error: expected 6 to be 11
fail@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:275:23
value@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:356:23
postlayout@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.blob.test.js:483:33</pre></td></tr>
<tr><td>ios.macos.Titanium.UI.Semantic Colors</td><td>use semantic colors via color properties (10.15.7)</td><td>0.014</td><td><pre>Error: expected 'Ti.UI.View' view to match snapshot image: snapshots/systemredcolor_light.png
    width
fail@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:275:23
value@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:356:23
postlayout@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.ui.test.js:363:34</pre></td></tr>
<tr><td>ios.macos.Titanium.UI.View.borderRadius corners</td><td>1 value with shadow effect (10.15.7)</td><td>0.006</td><td><pre>Error: expected 'Ti.UI.View' view to match snapshot image: snapshots/borderRadiusWithShadow30px_1x.png
    width
fail@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:275:23
value@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:356:23
postlayout@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.ui.view.test.js:1232:39</pre></td></tr>
<tr><td>ios.macos.Titanium.UI.View.borderRadius corners</td><td>1 value to create circle (10.15.7)</td><td>0.005</td><td><pre>Error: expected 'Ti.UI.View' view to match snapshot image: snapshots/borderRadius30px.png
    width
fail@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:275:23
value@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:356:23
postlayout@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.ui.view.test.js:1200:39</pre></td></tr>
<tr><td>ios.macos.Titanium.UI.View.borderRadius corners</td><td>set property post layout (10.15.7)</td><td>0.006</td><td><pre>Error: expected 'Ti.UI.View' view to match snapshot image: snapshots/borderRadius12px_12_1x.png
    width
fail@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:275:23
value@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:356:23
postlayout@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.ui.view.test.js:1169:39</pre></td></tr>
<tr><td>ios.macos.Titanium.UI.View.borderRadius corners</td><td>2 values in Array (10.15.7)</td><td>0.005</td><td><pre>Error: expected 'Ti.UI.View' view to match snapshot image: snapshots/borderRadius12px_12_1x.png
    width
fail@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:275:23
value@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:356:23
postlayout@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.ui.view.test.js:1135:41</pre></td></tr>
<tr><td>ios.macos.Titanium.UI.View.borderRadius corners</td><td>2 values in String (10.15.7)</td><td>0.011</td><td><pre>Error: expected 'Ti.UI.View' view to match snapshot image: snapshots/borderRadius12px_12_1x.png
    width
fail@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:275:23
value@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:356:23
postlayout@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.ui.view.test.js:1101:41</pre></td></tr>
<tr><td>ios.macos.Titanium.UI.View.borderRadius corners</td><td>4 values in Array (10.15.7)</td><td>0.005</td><td><pre>Error: expected 'Ti.UI.View' view to match snapshot image: snapshots/borderRadius12px_12_12dp_12_1x.png
    width
fail@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:275:23
value@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-12233/tmp/mocha/bui [...]

2020-10-30 07:11 UTC, hansemannn commented
Thank you Vijay! I hope this can be tested very extensively to prevent random crashes or memory leaks. Quite afraid of this kind of major change.

2020-10-30 23:53 UTC, vijaysingh-axway commented
> Thank you Vijay! I hope this can be tested very extensively to prevent random crashes or memory leaks. Quite afraid of this kind of major change.

@hansemannn Yeah. It will be tested properly. It would be great if you can test it on your app as well.

2020-11-05 11:02 UTC, janvennemann requested changes

2020-11-05 20:44 UTC, vijaysingh-axway commented on iphone/Classes/TiUITabGroupProxy.m
> +    [tabController.view removeFromSuperview];
Actual addSubview is [here](https://github.com/appcelerator/titanium_mobile/pull/12233/files#diff-30207cc237420adbde6370f0966b5ace65298e900041ae900d71769d050ab57dL160) where view is added on container controller's view. So I have added container view management of adding after window is opened. And removing is where controller.view is removed.

2020-11-06 19:43 UTC, janvennemann approved these changes

2021-01-08 22:02 UTC, ssekhri commented
The changes look good and the tests mentioned in the ticket and in this PR work fine.
However as this is a major change would run some more regression tests and memory tests as part of FR.

2021-01-13 23:47 UTC, ssekhri commented
FR Passed.
Verified on:
Mac OS: 10.15.4
SDK: 9.3.0.v20201105121820
Appc CLI: 8.1.1
JDK: 11.0.6
Node: 12.16.1
Studio: 6.0.0.202005141803
Xcode: 12.3

2021-01-15 20:08 UTC, merged

2021-01-15 20:27 UTC, m1ga commented
@sgtcoolguy  you might want to close this issue: https://github.com/appcelerator/titanium_mobile/issues/11651 too if it is fixed