fix(android): handle encoded WebView url
appcelerator/titanium_mobile pull request #12450
Opened 2021-02-09 00:22 UTC by garymathews

- Correctly decode WebView URLs

##### TEST CASE
```JS
const win = Ti.UI.createWindow();
const webView = Ti.UI.createWebView({
	url: 'https://test.com/sub/api?key=TiTeSTKEy%3D%3D&var=1234'
});

webView.addEventListener('load', (e)=>{
	Ti.API.info(`url: ${e.source.url}`);
});

win.add(webView);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-28341)

2021-02-09 00:38 UTC, build commented
<!--
  0 failure: 
  1 warning:  :mag: Can't find ...
  1 messages
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :mag: Can't find junit reports at `./junit.*.xml`, skipping generating JUnit Report.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against be1656a429dd5cda14ac90301ae5eb35b1ea422e
</p>

2021-02-09 01:48 UTC, jquick-axway approved these changes
CR: Pass

2021-02-09 14:49 UTC, sgtcoolguy requested changes

2021-02-09 14:49 UTC, sgtcoolguy commented on tests/Resources/ti.ui.webview.test.js
> +				should(e.source.url).be.a.string;
```suggestion
				should(e.source.url).be.a.String();
```

2021-02-09 14:49 UTC, sgtcoolguy commented on tests/Resources/ti.ui.webview.test.js
> +				should(e.source.url).be.a.string;
```suggestion
				should(e.source.url).be.a.String();
```

2021-02-09 14:49 UTC, sgtcoolguy commented on tests/Resources/ti.ui.webview.test.js
> +		webview.addEventListener('load', e => {
Should this ever fire a load event? The url looks invalid, so I assume it'd never load.

2021-02-09 14:49 UTC, sgtcoolguy commented on tests/Resources/ti.ui.webview.test.js
> +			url: 'https://test/pin%20wheel+.jpg'
same here, the url is invalid so shouldn't actually ever load

2021-02-09 14:49 UTC, sgtcoolguy commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiUIWebView.java
> +		final String query = uri.getEncodedQuery() != null ? "?" + uri.getEncodedQuery() : "";
assign to temp variable to avoid double call

2021-02-09 14:49 UTC, sgtcoolguy commented on tests/Resources/ti.ui.webview.test.js
> +	it('decode url', (finish) => {
limit to android? What changes on iOS here? Do we expect the same result?

2021-02-09 18:08 UTC, sgtcoolguy approved these changes

2021-02-09 18:57 UTC, lokeshchdhry commented
FR Passed.
No repeated sections of the encrypted are seen.

Studio Ver:       6.0.0.202005141803
SDK Ver:          9.3.X Local build
OS Ver:           10.15.5
Xcode Ver:        Xcode 12.3
Appc NPM:         5.0.0
Appc CLI:         8.1.1
Daemon Ver:       3.2.0
Ti CLI Ver:       5.2.5
Alloy Ver:        1.15.2
Node Ver:         12.13.1
NPM Ver:          6.14.7
Java Ver:         11.0.6
Android Devices:  ⇨ google Pixel (Android 10)

2021-02-10 16:40 UTC, merged

2021-03-05 15:56 UTC, build commented
The backport to `9_0_X` failed:
```
The process 'git' failed with exit code 128
```
Check [the run](https://github.com/appcelerator/titanium_mobile/actions/runs/624930762) for full details
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Check out the target branch
git checkout 9_0_X
# Make sure it's up to date
git pull
# Check out your branch
git checkout -b backport-12450-to-9_0_X
# Apply the commits from the PR
curl -s https://github.com/appcelerator/titanium_mobile/commit/2ad01084ea4972a4cd56e4c2a11f1110b4f52277.patch | git am -3 --ignore-whitespace
curl -s https://github.com/appcelerator/titanium_mobile/commit/0540cd2f2788081a4d7c2a099a5f00becad0ca16.patch | git am -3 --ignore-whitespace
curl -s https://github.com/appcelerator/titanium_mobile/commit/195a0b931f8f23b2ef1cca3cc2af60460978500f.patch | git am -3 --ignore-whitespace
curl -s https://github.com/appcelerator/titanium_mobile/commit/2ac8dfb03c2b63cd7d072e2758398503a51119c8.patch | git am -3 --ignore-whitespace
curl -s https://github.com/appcelerator/titanium_mobile/commit/a28323663c3b8e5bf2a0666a7c23b9790be357b7.patch | git am -3 --ignore-whitespace
curl -s https://github.com/appcelerator/titanium_mobile/commit/22f801398e6e5e27e856c49b956facfa47f50a4d.patch | git am -3 --ignore-whitespace
# Push it to GitHub
git push --set-upstream origin backport-12450-to-9_0_X
```
Then, create a pull request where the `base` branch is `9_0_X` and the `compare`/`head` branch is `backport-12450-to-9_0_X`.