feat(android): sync tab and actionbar title
appcelerator/titanium_mobile pull request #12499
Opened 2021-02-25 19:00 UTC by m1ga

**JIRA:** https://jira.appcelerator.org/browse/28371

Provide a clear PR title prefixed with `[TICKET]`

**Optional Description:**

Will update the Actionbar title automatically when you change the tab

**example**
```
Ti.UI.createTabGroup({
	autoTabTitle: true,
	tabs: [

		Ti.UI.createTab({
			window: Ti.UI.createWindow({
				title: 'Page 1'
			}),
			title: 'Page 1'
		}),

		Ti.UI.createTab({
			window: Ti.UI.createWindow({
				title: 'Page 2'
			}),
			title: 'Page 2'
		})

	]

}).open();
```

2021-02-25 19:19 UTC, build commented
<!--
  2 failure:  :microscope: Ther..., Test suite crashe...
  1 warning:  There is no linke...
  3 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/m1ga/titanium_mobile/blob/tabTitle/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Test suite crashed on iOS simulator. Please see <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-12499/1/artifact/mocha_2021-02-25-010440_slapchop-macos.crash">the crash log</a> for more details.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>There is no linked JIRA ticket in the PR body. Please include the URL of the relevant JIRA ticket. If you need to, you may file a ticket on <a href="https://jira.appcelerator.org/secure/CreateIssue!default.jspa">JIRA</a></td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:tada: Another contribution from our awesome community member, m1ga! Thanks again for helping us make Titanium SDK better. :thumbsup:</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 11199 tests are passing.
(There are 664 skipped tests not included in that total)
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 27195019e0571a764b6cb3a4ffb4466b474b9e73
</p>

2021-02-25 19:20 UTC, hansemannn commented
Thanks @m1ga! But I think this is not the correct behavior. I would expect to see the window title at the top, not the tab title. For parity with iOS, it also would not need an own property but become the default behavior in SDK 10

2021-02-25 19:30 UTC, m1ga commented
@hansemannn ah I see. Will update the PR.

Keep in mind it is not the default behavior in other apps. e.g. in Whatsapp the actionbar title is always the app name (or they have all window tab names set to "Whatsapp") and it doesn't change:
![Screenshot_20210225-202616](https://user-images.githubusercontent.com/4334997/109206223-e0d17800-77a7-11eb-8421-5c28bc26c3d7.png)
same for the Play Store or Youtube Music. The Actionbar title is not changing when changing the tabs

2021-02-25 19:32 UTC, hansemannn commented
Mhh, thats odd. Even with bottom navigation? I thought Instagram and some other apps moved to that behavior, maybe I missed something here.

2021-02-25 19:35 UTC, m1ga commented
ah, Instagram is changing the actionbar! But the right hamburger menu items moves between the shop and profile page :-) looks like they set a whole new actionbar

2021-02-25 20:01 UTC, m1ga commented
it is using the window title now but the first title is not set correctly ("Windo..." instead of "Window 1")

```javascript
Ti.UI.createTabGroup({
	autoTabTitle: true,
    // style: Titanium.UI.Android.TABS_STYLE_BOTTOM_NAVIGATION,
	tabs: [

		Ti.UI.createTab({
			window: Ti.UI.createWindow({
				title: 'Window 1'
			}),
			title: 'Page 1'
		}),

		Ti.UI.createTab({
			window: Ti.UI.createWindow({
				title: 'Window 2'
			}),
			title: 'Page 2'
		})

	]

}).open();
```

but will look at that tomorrow

2021-03-02 18:45 UTC, m1ga commented
fixed the truncated title at app start. Apparently you have to expand the title as a workaround (will set it to twice the title and set it to blank).

2022-03-21 13:52 UTC, hansemannn requested changes
A few minor issues

2022-03-21 13:52 UTC, hansemannn commented on android/modules/ui/src/java/ti/modules/titanium/ui/TabGroupProxy.java
> +		if (autoTabTitle) {
Rename to `tabGroup` instead of `tg`. Also, it can be inside the if-statement.

2022-03-21 13:52 UTC, hansemannn commented on apidoc/Titanium/UI/TabGroup.yml
> +    since: 10.1.0
Change to 10.2.0

2022-03-21 17:00 UTC, hansemannn approved these changes

2022-03-21 17:00 UTC, merged