fix: deprecate selectedBackgroundColor and selectedBackgroundImage
appcelerator/titanium_mobile pull request #12513
Opened 2021-03-02 21:22 UTC by garymathews

- Android has logged both `selectedBackgroundColor` and `selectedBackgroundImage` as deprecated for a while
- Deprecate the same properties on iOS for parity with Android including `selectedBackgroundGradient`
- Update documentation of deprecated properties

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26304)

2021-03-02 22:01 UTC, build commented
<!--
  2 failure:  Tests have failed..., Test suite crashe...
  1 warning:  This PR has miles...
  2 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Tests have failed, see below for more information.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Test suite crashed on iOS simulator. Please see <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-12513/1/artifact/mocha_2021-03-02-133505_macos-lepew.crash">the crash log</a> for more details.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This PR has milestone set to 10.0.0, but the version defined in package.json is 10.1.0
Please either:
- Update the milestone on the PR
- Update the version in package.json
- Hold the PR to be merged later after a release and version bump on this branch</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:x: 1 tests have failed
There are 1 tests failing and 733 skipped out of 11706 total tests.</td>
    </tr>
  </tbody>
</table>

### Tests:

<table><tr><th>Classname</th><th>Name</th><th>Time</th><th>Error</th></tr>
<tr><td>android.emulator.Titanium.UI.ImageView</td><td>.image with redirected URL and autorotate set to true (5.0.2)</td><td>10.026</td><td><pre>Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (app.js)
</pre></td></tr>
</table>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 10f3e39540016575c1182a936aca7f6530532ed7
</p>

2021-03-03 19:05 UTC, vijaysingh-axway requested changes
Some minor changes required.

2021-03-04 22:12 UTC, garymathews commented on apidoc/Titanium/UI/ListItem.yml
> +    deprecated:
Good catch!

2021-03-04 22:31 UTC, vijaysingh-axway approved these changes
CR passed.

2021-03-09 15:54 UTC, sgtcoolguy commented on apidoc/Titanium/UI/ListItem.yml
> +    default: Transparent
is the default really `'transparent'` or `null`/`undefined`?

2021-03-09 15:54 UTC, sgtcoolguy commented on apidoc/Titanium/UI/ListItem.yml
> +        notes: This property has been deprecated in favor of backgroundSelectedColor.
```suggestion
        notes: This property has been deprecated in favor of `backgroundSelectedColor`.
```

2021-03-09 15:55 UTC, sgtcoolguy commented on apidoc/Titanium/UI/ListItem.yml
> +        notes: This property has been deprecated in favor of backgroundSelectedImage.
```suggestion
        notes: This property has been deprecated in favor of `backgroundSelectedImage`.
```

or 

```suggestion
        notes: This property has been deprecated in favor of <Titanium.UI.ListItem.backgroundSelectedImage>.
```

2021-03-09 15:56 UTC, sgtcoolguy commented on apidoc/Titanium/UI/ListItem.yml
> +        notes: This property has been deprecated in favor of backgroundSelectedGradient.
```suggestion
        notes: This property has been deprecated in favor of `backgroundSelectedGradient`.
```

or

```suggestion
        notes: This property has been deprecated in favor of <Titanium.UI.ListItem.backgroundSelectedGradient>.
```

2021-03-09 15:57 UTC, sgtcoolguy commented on apidoc/Titanium/UI/TableViewRow.yml
> +        notes: This property has been deprecated in favor of backgroundSelectedImage.
```suggestion
        notes: This property has been deprecated in favor of `backgroundSelectedImage`.
```

or

```suggestion
        notes: This property has been deprecated in favor of <Titanium.UI.TableViewRow.backgroundSelectedImage>.
```

2021-03-10 00:27 UTC, ssekhri commented
FR Passed.
Verified on:
Mac OS: 10.15.4
SDK: 10.1.0.v20210309145621 
Appc CLI: 8.1.1
JDK: 11.0.6
Node: 12.16.1
Studio: 6.0.0.202005141803
Xcode: 12.3,
iOS simulator 14.3
Android emulator v11.0

2021-03-10 00:28 UTC, merged