docs: mark accessors that were autogenerated but documented as removed in 10
appcelerator/titanium_mobile pull request #12677
Opened 2021-03-30 17:29 UTC by ewanharris

This PR is related to #12661 and #12654 and removes some accessor functions that were documented properly (i.e existed in the yml docs and were not autogenerated by the docs scripts) but were actually backed by the auto-generation of accessors. Namely:

* Ti.Android.Intent.getData
* Ti.Android.MenuItem.setCheckable
* Ti.Android.MenuItem.setChecked
* Ti.Android.MenuItem.setEnabled
* Ti.Android.MenuItem.setVisible
* Ti.Android.MenuItem.isActionViewExpanded
* Ti.Android.MenuItem.isCheckable
* Ti.Android.MenuItem.isChecked
* Ti.Android.MenuItem.isEnabled
* Ti.Android.MenuItem.isVisible
* Ti.Network.HTTPClient.setTimeout (this is fine to remove as it is not part of the spec)
* Ti.UI.TableView.setHeaderPullView (iOS only)

It does not (yet) deal with the following APIs:

* Ti.UI.Tab.setWindow - This exists on Android but not iOS
* Sound.isLooping - This exists on iOS but not Android
* Sound.isPlaying - This exists on iOS but not Android
* Sound.isPaused - This exists on iOS but not Android

Personally, I think we should just remove the above APIs rather than have a difference between iOS and Android. But, that's like just my opinion so I'm open to suggestions

[JIRA](https://jira.appcelerator.org/browse/TIMOB-28407)

2021-03-30 17:31 UTC, build commented
<!--
  0 failure: 
  1 warning:  :mag: Can't find ...
  1 messages
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :mag: Can't find junit reports at `./junit.*.xml`, skipping generating JUnit Report.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3d00ea9478d504f981038ea84c855fb0e30ad933
</p>

2021-03-30 18:37 UTC, sgtcoolguy requested changes

2021-03-30 18:37 UTC, sgtcoolguy commented on apidoc/Titanium/Android/MenuItem.yml
> +      notes: Use the <Titanium.Android.MenuItem.checkable> property instead.
```suggestion
      notes: Use the <Titanium.Android.MenuItem.visible> property instead.
```

2021-03-30 20:04 UTC, vijaysingh-axway commented
I think, we can deprecate following APIs in favor of corresponding properties.  Probably we can create a ticket to track it.
   Sound.isLooping - This exists on iOS but not Android
   Sound.isPlaying - This exists on iOS but not Android
   Sound.isPaused - This exists on iOS but not Android

2021-04-05 14:55 UTC, sgtcoolguy approved these changes

2021-04-05 14:59 UTC, merged

2021-04-06 14:46 UTC, sgtcoolguy commented
@ewanharris We chatted on teams about this, but to summarize my thoughts:

Personally I think the get/set methods can be marked deprecated/removed in 10.0.0 since they fell under what we were attempting to get rid of around autogenerated accessors. I think the `is*` boolean query methods are less obvious and we should deprecate them in 10.0.0, but not remove them.

So we should:
-  add back the `@Kroll.method` annotations for the `MenuItem` ones and not mark them removed yet in docs
- mark the `Sound.is*` methods deprecated in docs.
- remove `Ti.UI.Tab.setWindow` and note it as such in the docs