chore: deprecate TableViewRow header and footer properties
appcelerator/titanium_mobile pull request #12689
Opened 2021-04-05 20:48 UTC by garymathews

- Deprecate `TableViewRow` properties `header` and `footer` in favor of `headerTitle` and `footerTitle`

##### TEST CASE
- Both `headerTitle` and `footerTitle` should have priority over deprecated `header` and `footer` properties
- Using `header` and `footer` will output a deprecation warning
```JS
const win = Ti.UI.createWindow();
const tableView = Ti.UI.createTableView({ backgroundColor: 'white' });
tableView.setData([{
	headerTitle: 'headerTitle',
	footerTitle: 'footerTitle',
	header: 'header',
	footer: 'footer',
	title: 'Row',
	color: 'black'
}]);
win.add(tableView);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-28198)

2021-04-05 21:35 UTC, build commented
<!--
  1 failure:  Test suite crashe...
  0 warning: 
  2 messages
  
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Test suite crashed on iOS simulator. Please see <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-12689/1/artifact/mocha_2021-04-02-121529_slapchop-macos.crash">the crash log</a> for more details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 4 tests are passing.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against dbbede8ae72d365cc8d0b3b513951bf009b54284
</p>

2021-04-05 22:48 UTC, jquick-axway approved these changes
CR: Pass

2021-04-07 18:01 UTC, sgtcoolguy commented on iphone/Classes/TiUITableViewRowProxy.m
> +    if (headerTitle != nil)
```suggestion
    if (headerTitle != nil) {
```

2021-04-07 18:01 UTC, sgtcoolguy commented on iphone/Classes/TiUITableViewRowProxy.m
> +  if (footerTitle != nil)
```suggestion
  if (footerTitle != nil) {
```

2021-04-07 18:01 UTC, sgtcoolguy requested changes
iOS side doesn't compile

2021-04-08 19:40 UTC, sgtcoolguy approved these changes

2021-04-09 00:04 UTC, vijaysingh-axway commented
@garymathews  In iOS, you have to make changes at couple of more places inside file TiUITableViewProxy.m e.g. https://github.com/appcelerator/titanium_mobile/blob/9b27f4ba0637d5fa98920b5262b5f2b7f8625782/iphone/Classes/TiUITableViewProxy.m#L694 , a=https://github.com/appcelerator/titanium_mobile/blob/9b27f4ba0637d5fa98920b5262b5f2b7f8625782/iphone/Classes/TiUITableViewProxy.m#L671 and https://github.com/appcelerator/titanium_mobile/blob/9b27f4ba0637d5fa98920b5262b5f2b7f8625782/iphone/Classes/TiUITableViewProxy.m#L603 , https://github.com/appcelerator/titanium_mobile/blob/9b27f4ba0637d5fa98920b5262b5f2b7f8625782/iphone/Classes/TiUITableViewProxy.m#L532

2021-04-12 18:53 UTC, vijaysingh-axway approved these changes
Looks good!

2021-04-12 18:58 UTC, ssekhri commented
FR Passed.
Verified on:
Mac OS: 10.15.4
SDK: 10.1.0.v20210411201210
Appc CLI: 8.1.1
JDK: 11.0.6
Node: 12.16.1
Studio: 6.0.0.202005141803
Xcode: 12.3
iOS simulator v14.3
Android emulator v11.0

2021-04-13 01:34 UTC, merged