fix(android): longpress event wrongly fires on a tapped view with touch disabled
appcelerator/titanium_mobile pull request #12820
Opened 2021-05-18 21:38 UTC by jquick-axway

**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-28454

**Summary:**
When tapping on a chlid view with "touchEnabled" set to `false`, a "longpress" event is wrongly fired when the parent view is listening for it. A "longpress" event should only happen when tap-and-holding for half a second.

**Test:**
1. Build and run the below on Android.
2. Tap on the "Click Me" label.
3. Verify a dialog displays "click". _(You should no longer get a "longpress" dialog.)_
4. Long press on the label.
5. Verify a dialog displays "longpress" with coordinates close to `(125, 125)`.
6. Long press the top-left corner of the blue square.
7. Verify a dialog displays "longpress" with coordinates close to `(0, 0)`.
8. Long press the bottom-right corner of the blue square.
9. Verify a dialog displays "longpress" with coordinates close to `(250, 250)`.

```javascript
const window = Ti.UI.createWindow({ backgroundColor: "white" });
const view = Ti.UI.createView({
	backgroundColor: "blue",
	touchFeedback: true,
	width: "250dp",
	height: "250dp",
});
view.add(Ti.UI.createLabel({
	text: "Click Me\nor\nLong Press Me",
	textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER,
	color: "white",
	touchEnabled: false,
}));
view.addEventListener("click", () => {
	alert("click");
});
view.addEventListener("longpress", (e) => {
	const formatter = new Intl.NumberFormat(Ti.Locale.currentLocale, {
		maximumFractionDigits: 0,
		minimumFractionDigits: 0,
	});
	alert(`longpress (${formatter.format(e.x)},${formatter.format(e.y)})`);
});
window.add(view);
window.open();
```

2021-05-18 21:57 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  3 messages
  
  DangerID: danger-id-Danger;
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :white_check_mark: All tests are passing
Nice one! All 15086 tests are passing.
(There are 962 skipped tests not included in that total)
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-12820/1/artifact/dist/mobilesdk-10.1.0.v20210518144115-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5bf95884e64036771a723106a6eb4c3d0f5f5899
</p>

2021-05-19 15:56 UTC, garymathews requested changes

2021-05-19 22:06 UTC, garymathews approved these changes
CR: **PASS**

2021-05-20 19:07 UTC, lokeshchdhry commented
FR Passed.
`Click` only fires `Click` & not `longpress`.

2021-05-20 22:22 UTC, merged