chore: update ti.cloudpush
appcelerator/titanium_mobile pull request #12986
Opened 2021-07-29 01:04 UTC by garymathews

- Update `ti.cloudpush` to version `8.0.0`

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-28480)

2021-07-29 01:29 UTC, build commented
<!--
  2 failure:  Tests have failed..., Test suite crashe...
  0 warning: 
  2 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Tests have failed, see below for more information.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Test suite crashed on iOS simulator. Please see <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-12986/1/artifact/mocha_2021-07-28-182034_macos-eve.crash">the crash log</a> for more details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:x: 1 tests have failed
There are 1 tests failing and 458 skipped out of 8483 total tests.</td>
    </tr>
  </tbody>
</table>

### Tests:

<table><tr><th>Classname</th><th>Name</th><th>Time</th><th>Error</th></tr>
<tr><td>android.emulator.Titanium.UI.ImageView</td><td>.image with redirected URL and autorotate set to true (5.0.2)</td><td>10.27</td><td><pre>Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (app.js)
</pre></td></tr>
</table>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 81447d1c7f53167ec4153b00c59d6e8ebf4f794c
</p>

2021-07-30 23:08 UTC, jquick-axway requested changes
FR: Failed

On Android 12 and when targeting API Level 31, tapping a push notification fails to launch app unless its UI is backgrounded. It looks like we're running into the following breaking-change...
https://developer.android.com/about/versions/12/behavior-changes-12
https://developer.android.com/reference/android/app/Notification.Builder#setContentIntent(android.app.PendingIntent)

2021-08-04 00:50 UTC, jquick-axway reviewed
CR: Pass
FR: Pass

Tested on Android 12, Android 11, and Android 5.

2021-08-04 00:50 UTC, jquick-axway approved these changes

2021-09-02 18:04 UTC, lokeshchdhry commented
FR Passed.
Works fine on Android 12, 10 & 5.

2021-09-02 18:25 UTC, merged