fix(ios): amend TiMediaVideoPlayer parent controller
appcelerator/titanium_mobile pull request #13011
Opened 2021-08-10 18:28 UTC by garymathews

- Amend changes from https://github.com/appcelerator/titanium_mobile/pull/12233

##### TEST CASE
- JIRA Project

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-28518)

2021-08-10 19:20 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  2 messages
  1 markdown notices
  DangerID: danger-id-Danger;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>:fist: The commits in this PR match our conventions! Feel free to Rebase and Merge this PR when ready.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>:x: 8 tests have failed
There are 8 tests failing and 737 skipped out of 11866 total tests.</td>
    </tr>
  </tbody>
</table>

### Tests:

<table><tr><th>Classname</th><th>Name</th><th>Time</th><th>Error</th></tr>
<tr><td>android.emulator.Titanium.Geolocation.methods</td><td>#forwardGeocoder() works via Promise return value (5.0.2)</td><td>5.057</td><td><pre>Error: done() invoked with non-Error: {"source":{"accuracy":1,"locationServicesEnabled":true,"hasCompass":true,"lastGeolocation":"{\"latitude\":37.4219983,\"longitude\":-122.084,\"altitude\":5,\"accuracy\":20,\"heading\":0,\"speed\":0,\"timestamp\":1628622568000}","apiName":"Ti.Geolocation","bubbleParent":true,"__propertiesDefined__":true},"code":-1,"success":false}
at /ti.geolocation.test.js:610:10</pre></td></tr>
<tr><td>android.emulator.Titanium.Geolocation.methods</td><td>#forwardGeocoder() works via callback argument (5.0.2)</td><td>5.017</td><td><pre>Error: expected false to be true
at Assertion.fail (/node_modules/should/cjs/should.js:275:13)
      at Assertion.value (/node_modules/should/cjs/should.js:356:9)
      at Geolocation.&lt;anonymous&gt; (/ti.geolocation.test.js:585:32)</pre></td></tr>
<tr><td>android.emulator.Titanium.Network.HTTPClient</td><td>responseXML (5.0.2)</td><td>0.189</td><td><pre>Error: expected true to be false
at Assertion.fail (/node_modules/should/cjs/should.js:275:13)
      at Assertion.value (/node_modules/should/cjs/should.js:356:9)
      at HTTPClient.xhr.onload (/ti.network.httpclient.test.js:28:40)</pre></td></tr>
<tr><td>ios.macos.fs</td><td>#truncate() truncates to specified number of bytes (10.15.5)</td><td>2.099</td><td><pre>Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (app.js)
</pre></td></tr>
<tr><td>ios.macos.Titanium.Platform.methods</td><td>#openURL (url, options, callback) (10.15.5)</td><td>0.018</td><td><pre>Error: expected 'mocha://test1' to equal 'mocha://test3'
value@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-13011/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/node_modules/should/cjs/should.js:356:23
listener@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-13011/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.platform.test.js:373:49</pre></td></tr>
<tr><td>ios.macos.Titanium.Platform.methods</td><td>#openURL (url, callback) (10.15.5)</td><td>4.287</td><td><pre>Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (app.js)
</pre></td></tr>
<tr><td>ios.macos.Titanium.Platform.methods</td><td>#openURL (url) (10.15.5)</td><td>2.085</td><td><pre>Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (app.js)
</pre></td></tr>
<tr><td>ios.macos.Titanium.UI.iOS.WebViewConfiguration</td><td>allowsPictureInPictureMediaPlayback (10.15.5)</td><td>2.731</td><td><pre>Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (app.js)
run@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-13011/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.main.js:9258:22
processImmediateQueue@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-13011/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.main.js:9321:18
drainQueues@file:///Users/build/jenkins/workspace/ium-sdk_titanium_mobile_PR-13011/tmp/mocha/build/iphone/build/Products/Debug-maccatalyst/mocha.app/Contents/Resources/ti.main.js:9298:52</pre></td></tr>
</table>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 749322a8bc7b864bf0df19b7ad804d9f8e8f6bb3
</p>

2021-08-19 22:18 UTC, jquick-axway requested changes
FR: Failed

When showing the video player not-fullscreen, the video is wrongly displayed in the window's top-left corner instead.

You can reproduce the issue with the below. The video should be played within a 300x200 view in the center of the window (it has a blue border), but the video is wrongly shown in the top-left corner.
```javascript
const window = Ti.UI.createWindow();
const videoView = Ti.Media.createVideoPlayer({
	url: "https://raw.githubusercontent.com/appcelerator/titanium_mobile/master/tests/remote/mov_bbb.mp4",
	autoplay: true,
	borderWidth: "4dp",
	borderColor: "blue",
	width: "300dp",
	height: "200dp",
});
window.add(videoView);
window.open();
```

2021-09-01 22:20 UTC, jquick-axway approved these changes
CR/FR: Pass

2021-09-02 14:01 UTC, ewanharris approved these changes
FR Pass. Original behaviour is restored, tests cases and sample from ticket all now function as expected.

2021-09-02 14:01 UTC, merged