fix(ios): mediaModule undeclared identifer
appcelerator/titanium_mobile pull request #13397
Opened 2022-04-14 08:49 UTC by m1ga

fixes https://github.com/tidev/titanium_mobile/issues/13396

Have to see if I can produce an test case! It's a bigger app that is not building for Store without this change.

Error log
```
[TRACE] app/build/iphone/Classes/MediaModule.m:2180:28: error: use of undeclared identifier 'musicPicker'; did you mean 'mediaPicker_'?
[TRACE]     [self closeModalPicker:musicPicker];
[TRACE]                            ^~~~~~~~~~~
[TRACE]                            mediaPicker_
[TRACE] app/build/iphone/Classes/MediaModule.m:2177:48: note: 'mediaPicker_' declared here
[TRACE] - (void)mediaPicker:(MPMediaPickerController *)mediaPicker_ didPickMediaItems:(MPMediaItemCollection *)collection
[TRACE]                                                ^
[TRACE] app/build/iphone/Classes/MediaModule.m:2202:26: error: use of undeclared identifier 'musicPicker'; did you mean 'mediaPicker_'?
[TRACE]   [self closeModalPicker:musicPicker];
[TRACE]                          ^~~~~~~~~~~
[TRACE]                          mediaPicker_
[TRACE] app/build/iphone/Classes/MediaModule.m:2200:57: note: 'mediaPicker_' declared here
[TRACE] - (void)mediaPickerDidCancel:(MPMediaPickerController *)mediaPicker_
[TRACE]                                                         ^
[TRACE] 2 errors generated.
[TRACE]  
```

2022-04-15 19:45 UTC, hansemannn requested changes
`musicPicker` actually is defined, but currently only if the `openMusicLibrary()` function is used (due to conditional compiling). The proper fix would be to expand the `USE_TI_MEDIAOPENMUSICLIBRARY` macro checks to also check for `USE_TI_MEDIAQUERYMUSICLIBRARY`.

2022-04-15 19:50 UTC, hansemannn commented
Alternate fix: https://github.com/tidev/titanium_mobile/pull/13398

2022-04-15 19:56 UTC, m1ga commented
:+1: I'll test your fix tomorrow and it looks better, then we can close this one here

2022-04-17 18:57 UTC, m1ga commented
closing in favor of https://github.com/tidev/titanium_mobile/pull/13398

2022-04-17 18:57 UTC, closed without merging