fix(all): change xmlns
appcelerator/titanium_mobile pull request #13410
Opened 2022-04-19 12:43 UTC by m1ga

change `xmlns:ti="http://ti.appcelerator.org"` -> `xmlns:ti="http://ti.tidev.io"`

2022-04-19 12:58 UTC, caspahouzer requested changes
tidev.io not ti.tidev.io 

we have no subdomain there

2022-04-19 12:59 UTC, m1ga commented
It's not a domain, its a namespace

2022-04-19 13:03 UTC, caspahouzer commented
The LGTM

2022-04-22 03:45 UTC, caspahouzer approved these changes

2022-04-28 11:30 UTC, hansemannn approved these changes

2022-04-28 11:30 UTC, merged