feat(ios): be able to detect an emulated iOS app on Apple Silicon
appcelerator/titanium_mobile pull request #13592
Opened 2022-10-07 09:58 UTC by hansemannn

Example code to test (compile an app and run it on an Apple Silicon mac, e.g. via Testflight):
```js
const win = Ti.UI.createWindow({
	backgroundColor: '#fff'
});

const btn = Ti.UI.createButton({
	title: 'Check if emulated'
});

btn.addEventListener('click', () => {
	alert(`Is emulated iOS app on Apple Silicon: ${Ti.Platform.isAppleSiliconTranslated}`);
});

win.add(btn);
win.open();
```

2022-10-07 12:01 UTC, hansemannn commented
@janvennemann Would you mind checking the proxy part? The logic itself is from Apple :)

2022-10-07 14:21 UTC, janvennemann requested changes
Just some small notes regarding naming and the method summary in the docs.

I'm also wondering if it would make sense to have this in an iOS only namespace? The is `Ti.Platform.Android` for Android specific device infos and this likely falls in the same category, just for iOS, right?

2022-10-07 14:21 UTC, janvennemann commented on iphone/Classes/PlatformModule.m
> +- (bool)isRunningOnAppleSilicon
Maybe name it `isTranslatedBinaryOnAppleSilicon` to indicate that it refers to the Rosetta translation and not just whether the App is running on an Apple Silicon device?

2022-10-07 14:21 UTC, janvennemann commented on apidoc/Titanium/Platform/Platform.yml
> +        via an Apple Silicon device.
```suggestion
        A Boolean value that indicates whether the current app is running as a translated
        binary using Rosetta on an Apple Silicon device.
```

2022-10-11 16:03 UTC, janvennemann approved these changes
Thanks! Yeah, makes sense to only go through the effort of creating the new namespace when there are actually more iOS only utils.

2022-10-11 16:05 UTC, merged