feat(android): use EncryptedSharedPreferences
appcelerator/titanium_mobile pull request #13848
Opened 2023-06-18 13:08 UTC by m1ga

fixes https://github.com/tidev/titanium-sdk/issues/13846

Adds `Ti.App.Properties.useEncryption` to store EncryptedSharedPreferences.

## Test

```js
Ti.App.Properties.setString("string", "plain value");
console.log("not encrypted - should be 'plain value': " + Ti.App.Properties.getString("string", "default"));

Ti.App.Properties.useEncryption = true;
Ti.App.Properties.setString("string", "secure value");
console.log("encrypted - should be 'secure value': " + Ti.App.Properties.getString("string", "default"));

Ti.App.Properties.useEncryption = false;
Ti.App.Properties.setString("string", "plain value 2");
console.log("not encrypted - should be 'plain value 2': " + Ti.App.Properties.getString("string", "default"));

Ti.App.Properties.useEncryption = true;
console.log("encrypted - should be 'secure value': " + Ti.App.Properties.getString("string", "default"));
```

Stores the values in an encrypted xml:

![Screenshot_20230618_142738](https://github.com/tidev/titanium-sdk/assets/4334997/34c59a81-372d-417d-ab2c-47d5cc154bd6)

## Todo
* [ ] Extend test
* [ ] Docs

2024-02-04 18:08 UTC, m1ga commented on apidoc/Titanium/App/Properties/Properties.yml
> +    since: {android: "12.3.0"}
```suggestion
    since: {android: "12.4.0"}
```

2025-04-28 09:28 UTC, hansemannn requested changes

2025-04-28 09:28 UTC, hansemannn commented on apidoc/Titanium/App/Properties/Properties.yml
> +        to store properties.
`EncryptedSharedPreferences` has been deprecated lately, see the link you've used. It's deprecated in 1.1.0-alpha-7 and we should target 1.0.0, but if the APIs in the main SharedPreferences expose the necessary APIs already, those should be used directly, so we don't need to migrate it again.

Otherwise, this PR should wait for a stable 1.1.0.

2025-04-28 13:31 UTC, m1ga commented on android/titanium/src/java/org/appcelerator/titanium/TiProperties.java
> +	SharedPreferences preferencesPlain;
`preferences` will be the normal encrypted or plain preference object throughout the whole file. So that name is correct. 
`preferencesPlain` is the none-encrypted version I only use to assign to `preferences` in the beginning or when you get elements. I could rename it to `noneEncryptedPreferences` but I like `plain` better in this case.

2025-04-28 13:37 UTC, m1ga commented on apidoc/Titanium/App/Properties/Properties.yml
> +        to store properties.
yeah `MasterKey` was added in 1.1.0-alpha01. I'll check for the deprecation message, updated to 1.1.0-alpha07 and I see it now too. We'll have to wait for the final version 1.1.0.

2025-04-28 13:55 UTC, m1ga commented
according to https://www.spght.dev/articles/28-05-2024/jetsec-deprecation the way to do it is just use the normal 
`SharedPreferences` without encryption:
> Additionally, as of Android 10 (Q), all devices encrypt user data on the filesystem by default, adding another level of security.

so you can only access it from a rooted phone and you shouldn't store sensitive data in it. Or encrypt it by hand and store it.

**Conclusion:**
I think we can just close this PR as `EncryptedSharedPreferences` still works in the alpha version but as we don't know how long it will be deprecated we should just not start to use it

2025-04-28 15:37 UTC, hansemannn commented
Makes sense! Still thank you for the effort to research this and do the PoC :-)

2025-04-28 15:37 UTC, closed without merging