230718 rotate event
appcelerator/titanium_mobile pull request #13882
Opened 2023-07-18 19:29 UTC by m1ga

old 2019 PR https://github.com/tidev/titanium-sdk/pull/11411 but with iOS event too!

```js
var win = Ti.UI.createWindow();
var v = Ti.UI.createView({width: 100,height: 100,backgroundColor: "#f00",touchEnabled: false});

win.addEventListener("rotate", onRotate);

win.add(v);
win.open();

function onRotate(e) {
  console.log("rotate", e.rotate);
  if (Ti.Platform.osname === 'android') {
    v.rotation = e.rotate;  // android
  } else {
    var matrix2d = Ti.UI.createMatrix2D();
    matrix2d = matrix2d.rotate(e.rotate); // in degrees
    var a = Ti.UI.createAnimation({
      transform: matrix2d,
      duration: 1,
    });
    v.animate(a);  // ios
  }
}
```

https://user-images.githubusercontent.com/4334997/160287718-8af400d0-a26c-4bb8-904f-d2a4697c915a.mp4

2024-10-19 13:53 UTC, m1ga commented on apidoc/Titanium/UI/View.yml
> +    since: "12.3.0"
```suggestion
    since: "12.6.0"
```

2025-04-06 13:19 UTC, m1ga commented on apidoc/Titanium/UI/View.yml
> +    since: "12.6.0"
```suggestion
    since: "12.7.0"
```

2025-04-28 09:22 UTC, hansemannn requested changes

2025-04-28 09:22 UTC, hansemannn commented on iphone/TitaniumKit/TitaniumKit/Sources/API/TiUIView.h
> +  UIRotationGestureRecognizer *rotationRegognizer;
```suggestion
  UIRotationGestureRecognizer *rotationRecognizer;
```

Please also fix in all usages

2025-04-28 10:51 UTC, hansemannn approved these changes

2025-04-28 10:53 UTC, merged