docs: add info about iOS foreground notifications
appcelerator/titanium_mobile pull request #13956
Opened 2023-12-19 21:18 UTC by m1ga

Apparently there is a `showInForground` in `userInfo`: https://github.com/tidev/titanium-sdk/blob/abdc7bf7dd1a0f2c7080f3c6fe4229d4b53dd776/iphone/TitaniumKit/TitaniumKit/Sources/API/TiApp.m#L547 but it was never documented.

Setting `userInfo: {showInForeground:true}` will display a local notification banner if the app is in foreground.

2024-01-12 09:21 UTC, hansemannn requested changes
Two quick ones

2024-01-12 09:21 UTC, hansemannn commented on apidoc/Titanium/App/iOS/UserNotificationCenter.yml
> +        Only available in iOS >= 10. Boolean if a notification banner is shown if the app is in foreground.
These notes are not required anymore, as Titanium requires iOS 13+

2024-01-12 09:21 UTC, hansemannn commented on apidoc/Titanium/App/iOS/UserNotificationCenter.yml
> +    type: Dictionary<UserInfoDictionary>
Is this required? `UserInfoDictionary` should also work

2024-01-12 09:33 UTC, hansemannn approved these changes

2024-01-30 19:45 UTC, cb1kenobi approved these changes
LGTM

2024-01-30 19:45 UTC, merged