feat(android): new event for empty TextFields
appcelerator/titanium_mobile pull request #13975
Opened 2024-01-26 22:08 UTC by m1ga

The `change` event on a TextField is only called when there is content in the field. If it is empty and you press "backspace" again you won't get any event. 

I've added an event: `emptyField` that will fire. 

```js
const win = Ti.UI.createWindow({});
var tf1 = Ti.UI.createTextField({
	width: 150,
	left: 10
});
var tf2 = Ti.UI.createTextField({
	width: 150,
	right: 10,
	value: "remove me"
});
tf2.addEventListener("emptyField", function(e) {
	console.log("key", e.keyCode)
	tf1.focus();
})
tf2.addEventListener("change", function(e) {
	console.log("change", tf2.value.length)
})
win.add(tf1);
win.add(tf2);
win.addEventListener("open", function() {
	tf2.focus();
})
win.open();
```

https://github.com/tidev/titanium-sdk/assets/4334997/f10a081e-8810-4744-a685-d1d4f67d9d9e

TODO:
* [ ] Docs
* [ ] rename it?
* [ ] someone needs to check if iOS has something similar

2024-02-01 13:19 UTC, jordanbisato commented
Isn't necessary to check if the TextField is empty before trigger the emptyField event?

2024-02-01 14:34 UTC, m1ga commented
as far as I can tell from testing it will only fire when the field is empty, so no text is in there and you press a key (See video above). You have to check the keyCode in Ti to see if it is the back key. I can add a check for the length but currently it looks like it is not necessary unless you have an example where it breaks

2024-06-15 12:54 UTC, hansemannn requested changes

2024-06-15 12:54 UTC, hansemannn commented on apidoc/Titanium/UI/TextField.yml
> +  - name: emptyField
Rename to `empty`?

2024-06-15 12:54 UTC, hansemannn commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
> +		this.tv.setOnKeyListener(new View.OnKeyListener()
Only add the listener if the event is listening for it

2024-06-15 13:14 UTC, m1ga commented
Fixed both comments

2024-06-15 14:18 UTC, hansemannn approved these changes

2024-06-15 14:18 UTC, merged