chore(android): let there be gradle 8
appcelerator/titanium_mobile pull request #14014
Opened 2024-03-23 19:03 UTC by AbdullahFaqeir

chore(android): let there be gradle 8
chore(android): fixed deprecations in kroll-apt project
chore(android): made kroll-apt incremental to enhance build time

**GitHub issue:** https://github.com/tidev/titanium-sdk/issues/13579

This PR is dedicated to my mentor Nafe Abboushi.

2024-03-23 20:34 UTC, m1ga requested changes
Are the changes to the JAVA files necessary for the update? The more stuff that is changed, the more we have to test :wink: 

Also I wouldn't update the min and targetSDK with this PR. If we still can use 21 we should do that too. Same with target 34. I have a PR for that here https://github.com/tidev/titanium-sdk/pull/13940/ as the broadcast receiver has to be adjusted.

So if that is not needed for the gradle PR please keep it as it is and do it in a separate PR (less changes, less testing).

I couldn't build a SDK locally. It's almost working but the last step `titaniumPublication(MavenPublication)` tries to publish it online instead of making a local repo? I've canceled it as it was uploading stuff :smile: Didn't want to publish something I don't need.

There aren't all cmake version available during build process. I have a different PR about that https://github.com/tidev/titanium-sdk/pull/13966 and I had to use `3.22.1` as that is available on all platforms.

2024-03-24 19:30 UTC, AbdullahFaqeir reviewed
All reviews applied.

2024-03-26 18:09 UTC, m1ga commented
I have to do some testing but the first round was very good and I was able to build kitchensink an my app now :+1: 

Review will follow once I have more time to test

2024-05-01 05:15 UTC, cb1kenobi reviewed
This is AWESOME! I don't wanna lose momentum on this PR.

I found a few indention nitpicks. I haven't tested the PR yet, but I spent some time researching some of the changes such as no longer need to call `.setPackageName()`. Good stuff!

What sort of testing do we need to do to get this over the finish line? I can test on Windows doing emulator builds as well as build-only device/dist builds. I don't have any working Android devices. Sigh.

2024-05-01 05:15 UTC, cb1kenobi commented on android/app/build.gradle
> +					"${projectDir}/../titanium/build/outputs/ti-assets"
Are these indentations intentional?

```suggestion
				'src/main/assets',
				"${projectDir}/../titanium/build/outputs/ti-assets"
```

2024-05-01 05:15 UTC, cb1kenobi commented on android/templates/build/ti.constants.gradle
> +			tiActivityConfigChanges: 'density|fontScale|keyboard|keyboardHidden|layoutDirection|locale|mcc|mnc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|touchscreen|uiMode'
Intentional indention?

```suggestion
		tiActivityConfigChanges: 'density|fontScale|keyboard|keyboardHidden|layoutDirection|locale|mcc|mnc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|touchscreen|uiMode'
```

2024-05-01 05:15 UTC, cb1kenobi commented on android/titanium/build.gradle
> +						'kroll.jsModuleName'      : 'titanium'
Intentional indention?

```suggestion
					'kroll.outputJsonFilePath': "${projectDir}/../../dist/android/titanium.bindings.json".toString(),
					'kroll.outputCppDirPath'  : "${projectDir}/../runtime/v8/generated".toString(),
					'kroll.jsModuleName'      : 'titanium'
```

2024-05-01 05:15 UTC, cb1kenobi commented on android/titanium/build.gradle
> +					"${projectDir}/../modules/ui/assets"
Intentional indention?

```suggestion
				'assets',
				"${projectDir}/../modules/ui/assets"
```

2024-05-01 05:15 UTC, cb1kenobi commented on android/titanium/build.gradle
> +					"${projectDir}/../modules/ui/res"
Intentional indention?

```suggestion
				'res',
				"${projectDir}/../modules/ui/res"
```

2024-05-01 05:15 UTC, cb1kenobi commented on android/titanium/build.gradle
> +				"set(LIBV8_MODE \"${packageJson.v8.mode}\")"
Intentional indention?

```suggestion
			"set(LIBV8_VERSION \"${packageJson.v8.version}\")",
			"set(LIBV8_MODE \"${packageJson.v8.mode}\")"
```

2024-05-01 05:15 UTC, cb1kenobi commented on android/untar.gradle
> +			dest: project.properties.dest)
Intentional indention?

```suggestion
		compression: project.properties.compression,
		overwrite: project.properties.overwrite,
		src: project.properties.src,
		dest: project.properties.dest)
```

2024-05-01 08:27 UTC, m1ga commented
> What sort of testing do we need to do to get this over the finish line?

:+1:  @cb1kenobi I would love to split this up into smaller steps as this is a big PR:
https://github.com/tidev/titanium-sdk/issues/13579#issuecomment-2021150043
I have made older PRs: first one only updates the gradle files to the newer syntax, 2nd one updates cmake and checkstyle (looks much but it's only linting). Then we only have the gradle 8 parts in here and can focus on that as it's a bigger change.

2024-09-12 15:37 UTC, hansemannn requested changes
A few questions and changes we should verify

2024-09-12 15:37 UTC, hansemannn commented on android/app/build.gradle
> +		minSdkVersion 26
Doesn't this bump the default min-sdk version to Android 8? We should remain stable with the current one

2024-09-12 15:37 UTC, hansemannn commented on android/app/build.gradle
> +	//namespace 'com.titanium.test'
Remove comment

2024-09-12 15:37 UTC, hansemannn commented on android/build.gradle
> +		classpath 'com.android.tools.build:gradle:8.3.1'
Let's do 8.10.1

2024-09-12 15:37 UTC, hansemannn commented on android/cli/commands/_buildModule.js
> -	await mainManifest.writeToFilePath(path.join(moduleMainDir, 'AndroidManifest.xml'));
What happened to this?

2024-09-12 15:37 UTC, hansemannn commented on android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip
Use latest one as well

2024-09-12 15:37 UTC, hansemannn commented on android/templates/build/root.build.gradle
> +		classpath 'com.google.gms:google-services:4.4.1'
Use latest ones for kotlin, gradle and google-services

2024-09-13 00:41 UTC, AbdullahFaqeir commented
Was this put in the system in any way or not, I hope so, and if not I would love to get back and work on it

2024-09-13 02:41 UTC, AbdullahFaqeir commented
> A few questions and changes we should verify. And can you please rebase with latest master to resolve the merge conflicts?

Of course

2024-09-13 14:22 UTC, m1ga commented on android/app/build.gradle
> -	compileSdkVersion 33
this is still needed. It complains that it is missing. It can be 34

2024-09-13 14:34 UTC, m1ga commented
Did a first quick test. The current PR won't build. These files need to be changed:

android/modules/ui/src/java/ti/modules/titanium/ui/PickerProxy.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiImageView.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIActivityIndicator.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIButton.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIButtonBar.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIOptionBar.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUITabbedBar.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/listview/TiRecyclerViewHolder.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/searchbar/TiUISearchBar.java
android/modules/ui/src/java/ti/modules/titanium/ui/widget/tabgroup/TiUIAbstractTabGroup.java

 Some `R.` resources need to be changed. E.g.
```
R.style.Widget_MaterialComponents_TextInputLayout_OutlinedBox_ExposedDropdownMenu
```
will be
```
com.google.android.material.R.style.Widget_MaterialComponents_TextInputLayout_OutlinedBox_ExposedDropdownMenu
```

We can't change the import `org.appcelerator.titanium.R` because some lines like `R.style.Widget_Titanium_OutlinedButton_IconOnly` are in the titanium namespace.

Best is to follow the errors when building the SDK (~30 changes). I'm not sure how to add files to this PR :blush:  But it won't take long to change it. Just go through the error messages and change `R` with `com.google.android.material.R`.

After that: SDK builds fine and I tested it with two apps with existing modules and they work fine. Kitchensink works too. Hyperloop-examples breaks: 
```
[ERROR] [GRADLE] A problem occurred configuring project ':gradle-project'.
[ERROR] [GRADLE] > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
[ERROR] [GRADLE]    > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
[ERROR] [GRADLE]      
[ERROR] [GRADLE]      If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.
[ERROR] [GRADLE] 
```

2024-09-13 14:38 UTC, m1ga commented on android/gradle.properties
> +
This can be removed now

2024-09-13 14:44 UTC, hansemannn commented
@m1ga PR's can be checked out most easily with the Github CLI and `gh pr checkout 14014` in this case. It clones the branch and checks it out. You can then push into the branch and the commits occur here.

2024-09-13 14:54 UTC, m1ga commented
@hansemannn nice! That worked :+1: SDK will build now, modules & hyperloop currently fail with the error above. 

@AbdullahFaqeir would be nice if you can find out where the namespace is missing. Apps without hyperloop work fine but I didn't check all controls yet.

2024-09-13 14:57 UTC, hansemannn commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIButton.java
> +				styleId = com.google.android.material.R.attr.buttonBarPositiveButtonStyle;
To keep the diff small, you could also just `import com.google.android.material.R;` I think.

2024-09-13 20:13 UTC, AbdullahFaqeir commented
@m1ga @hansemannn I fixed it to build for modules, couldn't build tho on my Silicon machine, but it the fix for sure went after that stage.

2024-09-14 11:15 UTC, m1ga commented
awesome! SDK builds, apps build, modules build :+1: We are getting closer.

* fix for hyperloop apps: https://github.com/tidev/hyperloop.next/pull/392
* small workflow update in https://github.com/tidev/titanium-sdk/pull/14112 (modules build fine, but when you start a example app build in a module it won't forward the `--sdk 12.6.0` parameter)

2024-09-14 16:16 UTC, m1ga commented
one thing we'll need to tell the module developers: minSdk 12.6.0 is required when you build modules with this SDK as it is building with a higher Java version. The other way (old modules in 12.6.0 apps) works fine.

2024-09-14 16:18 UTC, AbdullahFaqeir commented
> one thing we'll need to tell the module developers: minSdk 12.6.0 is required when you build modules with this SDK as it is building with a higher Java version. The other way (old modules in 12.6.0 apps) works fine.

@m1ga while generating the manifest file?

2024-09-14 16:22 UTC, m1ga commented
when building an app with a module that was build with this PR you'll see
´Unsupported class file major version 61` as the module was build with JAVA_17 and the app is trying to build with JAVA_11 (current 12.4.0). But since we have the `minSdk` value in the module manifest it's fine. The developer just have to update it when using 12.6.0 to build the module

2024-09-14 16:31 UTC, AbdullahFaqeir commented
> when building an app with a module that was build with this PR you'll see ´Unsupported class file major version 61`as the module was build with JAVA_17 and the app is trying to build with JAVA_11 (current 12.4.0). But since we have the`minSdk` value in the module manifest it's fine. The developer just have to update it when using 12.6.0 to build the module

@m1ga Exactly!

2024-09-14 17:09 UTC, AbdullahFaqeir commented
@m1ga  @hansemannn I believe the PR is ready to be merged?

2024-09-16 11:59 UTC, m1ga reviewed
My tests look good:
* building the SDK :heavy_check_mark: 
* building app with multiple existing modules with this SDK :heavy_check_mark: 
* building modules and the included example app :heavy_check_mark: 
* building hyperloop-examples :heavy_check_mark: 
* building kitchensink-v2 :heavy_check_mark:

2024-09-17 00:06 UTC, hansemannn commented on android/templates/module/generated/build.gradle
>  	ndkVersion '22.1.7171670'
@AbdullahFaqeir You resolved this but added no commit?

2024-09-17 00:09 UTC, AbdullahFaqeir commented on android/templates/module/generated/build.gradle
>  	ndkVersion '22.1.7171670'
Ooh, didn't see yours, I believe yes it should, and it allows me to build on my machine, let me see this

2024-09-17 01:05 UTC, AbdullahFaqeir commented on android/templates/module/generated/build.gradle
>  	ndkVersion '22.1.7171670'
Done

2024-09-17 06:04 UTC, hansemannn approved these changes
LGTM!

2024-09-17 07:21 UTC, m1ga approved these changes

2024-09-17 07:22 UTC, AbdullahFaqeir commented
LET'S GOOOO 🚀🚀🚀

2024-09-17 07:26 UTC, merged

2024-09-17 15:35 UTC, cb1kenobi commented
Excellent work!

2024-11-02 17:00 UTC, AhmedMSayed commented
Halla walla, That's Awesome @AbdullahFaqeir you saved my day