[AC-4523] Android: Add property to release space when hiding an object
appcelerator/titanium_mobile pull request #8458
Opened 2016-10-02 10:21 UTC by m1ga

**JIRA:** https://jira.appcelerator.org/browse/AC-4523

2016-10-02 10:21 UTC, build commented
Can one of the admins verify this patch?

2016-10-02 13:41 UTC, hansemannn requested changes

2016-10-02 13:41 UTC, hansemannn commented on android/titanium/src/java/org/appcelerator/titanium/TiC.java
> +	public static final String PROPERTY_FREE_SPACE = "freeSpace";
I don't like the property-name. What about a more "boolean-like" property, e.g. `showSpaceWhenHidden` or `truncateSpace`? Or even expose the used constant directly and introduce a `hiddenBahavior` property. That keeps it more flexible, allows more configuration and sounds more native. Thanks!

2016-10-02 13:41 UTC, hansemannn commented on apidoc/Titanium/UI/View.yml
> +    since: 6.0.0
6.0.0 is already in QE-testing, please set it to 6.1.0 and we'll try to review it in that timeframe. Thx!

2016-10-02 14:26 UTC, m1ga commented on android/titanium/src/java/org/appcelerator/titanium/TiC.java
> +	public static final String PROPERTY_FREE_SPACE = "freeSpace";
Good idea! I'll go for `hiddenBehaviour: Ti.UI.VIEW_GONE | Ti.UI.VIEW_INVISIBLE`
Then it looks almost like the native View.GONE and View.INVISIBLE

2016-10-02 17:10 UTC, hansemannn approved these changes

2016-10-02 17:10 UTC, hansemannn commented
Looks great now! Putting into further review for 6.1.0.

2016-10-02 17:15 UTC, hansemannn commented on android/modules/ui/src/java/ti/modules/titanium/ui/UIModule.java
> +	@Kroll.constant public static final int VIEW_INVISIBLE = View.INVISIBLE;
Thinking about it, we might want to rename them to `Ti.UI.HIDDEN_BEHAVIOR_GONE` and `Ti.UI.HIDDEN_BEHAVIOR_INVISIBLE`. What do you think? And please add + validate the docs for the constants, they are not documented, yet.

2016-10-02 17:30 UTC, m1ga commented on android/modules/ui/src/java/ti/modules/titanium/ui/UIModule.java
> +	@Kroll.constant public static final int VIEW_INVISIBLE = View.INVISIBLE;
Sure, changed the property and updated the constants inside the doc! `HIDDEN_BEHAVIOR_INVISIBLE` is fine, too. So its more connected to the property name

2016-10-06 15:27 UTC, hansemannn commented
CR + FT passed, PR approved! Great work! 🚀

2016-10-06 15:27 UTC, merged