[TIMOB-16369]
appcelerator/titanium_mobile pull request #8468
Opened 2016-10-04 06:46 UTC by fmerzadyan

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-16369

2016-10-04 06:46 UTC, build commented
Can one of the admins verify this patch?

2016-10-04 07:38 UTC, hansemannn commented
Please rebase with master, thanks!

2016-10-06 13:30 UTC, sgtcoolguy commented
@fmerzadyan To rebase and remove the extra conflicting commit:

```
git checkout master
git pull upstream master
git checkout TIMOB-16369
git rebase master
git push origin TIMOB-16369 --force
```

2016-10-06 13:47 UTC, sgtcoolguy requested changes
I'm struggling to understand what exactly we're trying to achieve here. The linked ticket is not very clear and has a long comment history.

Are we trying to expose some new property to disable the standard popup/context bar when used? Or allow the user to create their own popup bar contents?

From what I can tell the user wanted to stop those default options in the action bar, but still allow you to select text (Basically you can select/highlight text, but can't copy/paste it out). From what I can make out of @hansemannn 's iOS implementation is that his new property actually disables both text selection and the popup, which doesn't seem like what the user wanted.

Additionally, it looks like Tim Poulsen was asking to replace the default action bar content with his own content.

I think we need to go back to the drawing board on this ticket and properly address what the user is asking for (if possible), including on iOS.

2016-10-06 13:47 UTC, sgtcoolguy commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiUIWebView.java
> +//import ti.modules.titanium.ui.R;
remove this commented out line

2016-10-06 13:47 UTC, sgtcoolguy commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiUIWebView.java
> +//            Log.d(TAG, "TiUIWebView.TiWebView constructor is fired");
remove commented out logging

2016-10-06 13:47 UTC, sgtcoolguy commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiUIWebView.java
> +	private class TiWebView extends WebView {
Looks like you're not using the same formatting preferences we had, so there are a lot of formatting changes here.

Please use the formatting settings from our standards repo: https://github.com/appcelerator/appc-standards/tree/master/languages/java

2016-10-06 13:47 UTC, sgtcoolguy commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/webview/TiUIWebView.java
> +//            Log.d(TAG, "TiWebView.startActionMode has been fired");
Remove all this commented out code...

2016-10-11 17:13 UTC, hansemannn commented
Closing in favor of #8494.

2016-10-11 17:13 UTC, closed without merging