[TICKET] Added missing responseHeaders property
appcelerator/titanium_mobile pull request #8470
Opened 2016-10-04 10:17 UTC by Topener

Ticket: https://jira.appcelerator.org/browse/AC-4528

2016-10-04 10:17 UTC, build commented
Can one of the admins verify this patch?

2016-10-04 13:15 UTC, hansemannn requested changes
We cannot merge this currently. Please address the comments before.

2016-10-04 13:15 UTC, hansemannn commented on apidoc/Titanium/Network/HTTPClient.yml
> +
Remove this block, it's generated automatically

2016-10-04 13:15 UTC, hansemannn commented on apidoc/Titanium/Network/HTTPClient.yml
> +    summary: All of the response headers.
Bad wording, please use a descriptive text.

2016-10-04 13:15 UTC, hansemannn commented on apidoc/Titanium/Network/HTTPClient.yml
> +        Contains an array of response headers
It is a dictionary no area. Also already mentioned in the summary.

2016-10-04 13:15 UTC, hansemannn commented on apidoc/Titanium/Network/HTTPClient.yml
> +    type: Array
Incorrect type, it is a dictionary.

2016-10-04 13:15 UTC, hansemannn commented on apidoc/Titanium/Network/HTTPClient.yml
> +    platforms: [ios]
Incorrect platform, it is `[iphone, ipad]`.

2016-10-04 14:48 UTC, Topener commented
I've updated the changes

2016-10-05 07:19 UTC, hansemannn requested changes

2016-10-05 07:19 UTC, hansemannn commented on apidoc/Titanium/Network/HTTPClient.yml
> +    type: Array<Object>
The type still looks invalid. The code says it's a Dictionary [here](https://github.com/appcelerator/titanium_mobile/blob/master/iphone/Classes/TiNetworkHTTPClientProxy.m#L536) and [here](https://github.com/appcelerator/titanium_mobile/blob/master/iphone/Classes/TiNetworkHTTPClientProxy.h#L46). So it has to be: `type: Dictionary` unless you really receive an array.

2016-10-06 13:53 UTC, hansemannn commented
Applied the fix manually, PR approved!

2016-10-06 13:53 UTC, hansemannn approved these changes

2016-10-06 13:53 UTC, merged