[TIMOB-16369] iOS: Hide context menu in Ti.UI.WebView
appcelerator/titanium_mobile pull request #8488
Opened 2016-10-07 21:50 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-16369

2016-10-11 13:43 UTC, sgtcoolguy commented
test this please

2016-10-11 13:44 UTC, sgtcoolguy requested changes

2016-10-11 13:44 UTC, sgtcoolguy commented on iphone/Classes/TiUIWebView.m
> +    BOOL disableSelection = [TiUtils boolValue:[[self proxy] valueForKey:@"disableContextMenu"] def:NO];
might want to rename the variable to match the property: disableContextMenu - rather than disableSelection.

2016-10-13 08:30 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +    BOOL disableSelection = [TiUtils boolValue:[[self proxy] valueForKey:@"disableContextMenu"] def:NO];
Agree. The Travis job is running for 2 days now, hopefully it's re-triggered correctly after the commit.

2016-11-07 15:09 UTC, hansemannn commented
Hey Chris, so I finally updated the docs in @5fbc5d9 to have the Android part documented as well (not done in #8494). We should be cool now!

2016-11-07 15:21 UTC, sgtcoolguy approved these changes

2016-11-07 20:56 UTC, merged