[timob-23494] Android: Support #createFile() method on Ti.Filesystem.File
appcelerator/titanium_mobile pull request #8514
Opened 2016-10-14 17:24 UTC by fmerzadyan

**JIRA:** https://jira.appcelerator.org/browse/timob-23494

**Android did not support createFile**

2016-10-17 21:28 UTC, garymathews commented on android/titanium/src/java/org/appcelerator/titanium/TiFileProxy.java
> +    public boolean createFile()
Formatting, use tabs

2016-10-20 17:51 UTC, sgtcoolguy commented
@fmerzadyan Please update the unit test for Ti.Filesystem.File.createFile to no longer skip on Android and confirm that this fix works.

Easiest way to do so is to clone appcelerator/titanium-mobile-mocha-suite locally, and copy Resources/ti.filesystem.file.test.js into appcelerator/titanium_mobile/tests/Resources. Then modify the test to no longer skip (around line 204):
```javascript
it('#createFile() and #deleteFile()', function () {
    var newFile = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, 'myfile');
```

Add the updated file into your PR.

2016-10-25 16:02 UTC, sgtcoolguy requested changes
The test is passing, so great job there. I think just one more small change is necessary - you appear to be recreating a TiBaseFile using a hard-coded location unnecessarily. Just use the TiBaseFile that's already generated in the constructor and wrapped by the proxy.

2016-10-25 16:02 UTC, sgtcoolguy commented on android/titanium/src/java/org/appcelerator/titanium/TiFileProxy.java
> +		Context context = TiApplication.getInstance().getApplicationContext();
Is all of this necessary? I think this is hard-coding the location of the file when it shouldn't be. Don't we already create the correct TiBaseFile up in the constructor? You should be able to just do `return tbf.createFile();` here.

2016-10-26 18:34 UTC, fmerzadyan commented on android/titanium/src/java/org/appcelerator/titanium/TiFileProxy.java
> +		Context context = TiApplication.getInstance().getApplicationContext();
`return tbf.createFile()` would mean `TiBaseFile`'s `createFile` method which would simply return false everytime (see [tbf.createFile).](https://github.com/appcelerator/titanium_mobile/pull/8514/files#diff-0c93a7953c3607b38b61844d828ba1a4R193) To start from the beginning, when the url is passed to the `TiFileProxy`, `tbf` is instantiated to a child class `TiResourceFile` which is a sibling to `TiFile`. In order to use `TiFile.createFile` I needed to convert `tbf` to `TiFile` and to do this I needed a path. `tbf.getNativePath` would throw errors stating that directory and file did not exist. Even using `mkdirs` or `mkdir` didn't fix this so I used `ContextWrapper` instead. It doesn't affect other url's and also `applicationDataDirectory`, `resourcesDirectory`, etc would return the same url in end when it is parsed in `TiFileFactory`. (see [storage locations](http://docs.appcelerator.com/platform/latest/#!/guide/Filesystem_Access_and_Storage)

2016-10-31 14:51 UTC, sgtcoolguy approved these changes

2016-10-31 14:51 UTC, merged