[AC-4579] iOS: support for iOS numberOfLines on UILabel
appcelerator/titanium_mobile pull request #8543
Opened 2016-10-25 15:20 UTC by chmiiller

**JIRA:** https://jira.appcelerator.org/browse/AC-4579
https://jira.appcelerator.org/browse/AC-4579

I've just signed the Online CLA, so my email is: carlosh.lz@hotmail.com

2016-10-25 15:23 UTC, build commented
Can one of the admins verify this patch?

2016-10-25 15:51 UTC, sgtcoolguy commented
ok to test

2016-10-25 16:13 UTC, hansemannn commented on apidoc/Titanium/UI/Label.yml
> +    since: {android: "4.1.0", ios: "6.0.0"}
Rename to  `{android: "4.1.0", iphone: "6.1.0", ipad: "6.1.0}`
- 6.0.0 is already and Beta and will not take new features at this point
- The docs need to distinguish `iphone` and `ipad` as specified keys

2016-10-25 16:15 UTC, hansemannn requested changes
Left some comments that require changes. Please also add unit-test for this property in https://github.com/appcelerator/titanium-mobile-mocha-suite

2016-10-25 16:15 UTC, hansemannn commented on apidoc/Titanium/UI/Label.yml
> +    since: {android: "4.1.0", ios: "6.0.0"}
Rename to  `{android: "4.1.0", iphone: "6.1.0", ipad: "6.1.0}`
- 6.0.0 is already and Beta and will not take new features at this point
- The docs need to distinguish `iphone` and `ipad` as specified keys

2016-10-25 16:15 UTC, hansemannn commented on iphone/Classes/TiUILabel.m
> +	[(TiViewProxy *)[self proxy] contentsWillChange];
The indentation is messed-up here, please align with the other lines (use diff-tool to check before commiting).

2016-10-25 16:15 UTC, hansemannn commented on iphone/Classes/TiUILabel.m
> +    [[self label] setNumberOfLines:[TiUtils floatValue:value]];
Use `ENSURE_TYPE(value, NSNumber);` for validation

2016-10-25 16:31 UTC, sgtcoolguy commented
@chmiiller regarding Hans' comment about our unit tests. We maintain a test suite now that we use against PRs. The suite itself is at https://github.com/appcelerator/titanium-mobile-mocha-suite

In particular, it'd be good to add a unit test for Ti.UI.Label.setMaxLines in https://github.com/appcelerator/titanium-mobile-mocha-suite/blob/master/Resources/ti.ui.label.test.js

To do so, clone that repo down locally. Copy titanium-mobile-mocha-suite/Resources/ti.ui.label.test.js to titanium_mobile/tests/Resources/ti.ui.label.test.js and then edit it to add a test for maxLines. (Anything in the titanium_mobile/tests folder acts as an "override" for the test suite. So you could also cheat and copy the app.js and comment out all the other suites other than ti.ui.label.test.)

You can run the test suite with that change locally by doing:
```
cd titanium_mobile/build
npm install
node scons.js cleanbuild ios # builds and installs ios-only SDK as 6.1.0 in your system
node scons.js test iOS # runs the unit tests against iOS
```

2016-10-26 10:09 UTC, hansemannn commented
@chmiiller Thanks for the changes! Unfortunately you made the changes in this repo instead of [titanium-mobile-mocha-suite](https://github.com/appcelerator/titanium-mobile-mocha-suite). Can you just push https://github.com/appcelerator/titanium_mobile/pull/8543/commits/b2b706cd12085a32938f5b780ea19f65d23b5e1e to the existing repo and I will review the PR there as well. Thx!

2016-10-26 10:11 UTC, chmiiller commented
ops, I got bit confused by @sgtcoolguy 's answer. Gonna push it...

2016-10-26 10:18 UTC, chmiiller commented
here it is: https://github.com/appcelerator/titanium-mobile-mocha-suite/pull/6
Hope it is correct now 😁

2016-10-26 11:42 UTC, hansemannn approved these changes

2016-10-26 11:50 UTC, hansemannn commented
CR + FT **passed**, PR **approved**. Thanks @chmiiller! 🚀

2016-10-26 11:50 UTC, merged

2016-10-26 11:51 UTC, chmiiller commented
this [commit](https://github.com/appcelerator/titanium_mobile/pull/8543/commits/74131e3dbd795f081f935f064fe8dc96b748e8e8) removes the ti.ui.label.test.js added by mistake in the repo

2016-10-26 14:26 UTC, sgtcoolguy commented
cc @hansemannn and @chmiiller : Just to clear up the confusion here - We typically add the new/modified unit tests in our PRs as you did, @chmiiller - that way we can ensure that the test is run and passes as part of the PR that modifies the behavior. Then once merged, we migrate the changes back to the titanium-mobile-mocha-suite so that the test is in the canonical suite used by all platforms. It's a fairly new process here and not that friendly yet, which is why even we are a little iffy about it. 😏 We'd eventually like to have some auto-merge process that once a test gets modified as part of a PR in titanium_mobile and is merged in and passes it'd get auto-merged back into the suite repo.

As for why we place the modified test in the PR itself? Otherwise once it goes into the full suite it'll get run against every PR, so totally unrelated PRs would suddenly start failing because of the modified test without the PR that implements/fixes it being merged yet.

2016-10-26 14:55 UTC, chmiiller commented
Makes (a lot of) sense now =)
Thanks!

2017-02-23 12:54 UTC, yomybaby commented
👍