[AC-4649] Android: Adding getLocationOnScreen() to retrieve location after translation
appcelerator/titanium_mobile pull request #8650
Opened 2016-12-01 19:16 UTC by m1ga

**JIRA:** https://jira.appcelerator.org/browse/AC-4649

2016-12-01 19:16 UTC, build commented
Can one of the admins verify this patch?

2016-12-02 14:41 UTC, hansemannn requested changes
Please add docs, thx!

2016-12-02 17:27 UTC, garymathews commented
Thanks, but I believe this is a bug with the `Titanium.View.rect` property. After an animation the `left right top bottom` properties will stay as originally set. But the `rect` `x` and `y` properties should update to the new position.

Adding a new method should not be necessary, `rect` should be fixed to address this issue 👍

2016-12-02 17:30 UTC, m1ga commented
I see,thanks. I'll have a look and close this one. May be the parts I've added could fix the `rect` problem already.

2016-12-02 17:30 UTC, closed without merging