[TIMOB-23666]: iOS Button setting remote backgroundImage doesn't app…
appcelerator/titanium_mobile pull request #8691
Opened 2016-12-15 07:11 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-23666

2016-12-18 14:33 UTC, hansemannn requested changes

2016-12-18 14:33 UTC, hansemannn commented on iphone/Classes/TiUIView.m
> +	return [TiUtils loadCappedBackgroundImage:image forProxy:[self proxy] withLeftCap:leftCap withTopCap:topCap];
`withTopCap` should be `topCap`, since the `with` prefix is only used for the 1st argument, based on Obj-C coding guidelines.

2016-12-18 14:33 UTC, hansemannn commented on iphone/Classes/TiUtils.m
> +    return resultImage;
Where does this method logic come from? I feel like I saw this before, and if so, we should use this logic for all usages to avoid duplicate code.

2016-12-18 14:33 UTC, hansemannn commented on iphone/iphone/Assets.xcassets/AppIcon.appiconset/Contents.json
> +    {
How is this change related to the PR? Please restore the initial Contents.json or give me a quick explanation on this. The icons are generated automatically for packaged SDK's anyway. :-)

2016-12-19 06:16 UTC, vijaysingh-axway commented on iphone/Classes/TiUtils.m
> +    return resultImage;
There is a method in TIUtils.m named - +(UIImage*)loadBackgroundImage:(id)image forProxy:(TiProxy*)proxy
. But this method do not use capping . So a new method needed which uses capping.

2016-12-27 15:56 UTC, hansemannn approved these changes

2017-01-19 20:21 UTC, htbryant94 commented
FR Approved! Tested with demo code on iPhone 7 (10.2) Sims & Device and was able to set the BackgroundImage of button elements both with remote and local image paths. Additionally, ran the test case for the following elements:

Ti.UI.iOS.Stepper 
Ti.UI.iOS.Toolbar
Ti.UI.SearchBar
Ti.UI.TabGroup (setActiveTabBackgroundImage)
Ti.UI.TextField

2017-01-19 20:21 UTC, htbryant94 approved these changes

2017-01-22 16:19 UTC, hansemannn commented
@htbryant94 I did not finish the CR, yet and would tackle that early this week, so please don't merge / resolve, yet, thx!

2017-02-02 13:12 UTC, hansemannn commented
CR + FT **passed**, PR **approved**. Great work @vijaysingh-axway !

2017-02-02 13:12 UTC, merged