[TIMOB-23327]:Webview request send out beforeload event is excuted on Webview
appcelerator/titanium_mobile pull request #8732
Opened 2017-01-09 09:35 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-23327

2017-01-09 14:58 UTC, hansemannn requested changes

2017-01-09 14:58 UTC, hansemannn commented on apidoc/Titanium/UI/WebView.yml
>      since: "5.4.0"
Change to `since: { android: "5.4.0", iphone: "6.10", ipad: "6.1.0"}`

2017-01-09 14:58 UTC, hansemannn commented on apidoc/Titanium/UI/WebView.yml
>      since: "5.4.0"
Same as above, include the `since` for iOS

2017-01-09 14:58 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +    RELEASE_TO_NIL(blacklistedURLs);
Indentation

2017-01-09 14:58 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +    blacklistedURLs = [[NSArray alloc] initWithArray:args];
Should we retain this?

2017-01-09 14:58 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +                if([self.proxy _hasListeners:@"onStopBlacklistedUrl"]) {
Replace `if(` with `if (` in 730 and 731

2017-01-09 14:58 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +            if([urlAbsStr rangeOfString:blackListedUrl options:NSCaseInsensitiveSearch].location !=NSNotFound) {
Replace `!=NSNotFound` with `!= NSNotFound`

2017-01-09 14:58 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +                    NSDictionary *eventDict = [NSDictionary dictionaryWithObjectsAndKeys:urlAbsStr,@"url",@"Webview did not load blacklisted url.", @"messsage", nil];
Try to use the shorthand dictionary next time. It looks more solid to read (in my personal opinion). Like this:
```objc
[[self proxy] fireEvent:@"onStopBlacklistedUrl" withObject:@{
    @"url": urlAbsStr,
    @"message": @"Webview did not load blacklisted url."
}];

And is the message the same as used on Android? Maybe we can unify that as well.

2017-01-09 14:58 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +        NSString *urlAbsStr = [newUrl absoluteString];
Always use readable variables in Obj-C, e.g. `urlString`

2017-01-09 14:58 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +                    [self.proxy fireEvent:@"onStopBlacklistedUrl" withObject:eventDict];
Try to use `[self proxy]` instead of `self.proxy`, but just out of personal preference :-)

2017-01-10 03:17 UTC, vijaysingh-axway commented on iphone/Classes/TiUIWebView.m
> +    blacklistedURLs = [[NSArray alloc] initWithArray:args];
As this is allocated here and is getting release when dealloc called or new blacklisted urls are getting set. So I think it is right.

2017-01-10 08:23 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +    blacklistedURLs = [[NSArray alloc] initWithArray:args];
The release-cycle is clear, but think we don't work with ARC here, I see cases where the array could be GC'd while still being used. Especially when we have more requests over the time and the variable remains in idle.

2017-01-10 09:07 UTC, hansemannn commented on apidoc/Titanium/UI/WebView.yml
> +    since: [android: "5.4.0", iphone: "6.1.0", ipad: "6.1.0"]
Use curly brackets (like an object) instead of square brackets. Same for the below as well

2017-01-10 09:29 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +    blacklistedURLs = [[NSArray alloc] initWithArray:args];
This is what I would propose:

```objc
-(void)setBlacklistedURLs_:(id)args
{
    ENSURE_TYPE(args, NSArray);
    
    if (blacklistedURLs) {
        RELEASE_TO_NIL(blacklistedURLs);
    }
    
    for (id blacklistedURL in args) {
        ENSURE_TYPE(blacklistedURL, NSString);
    }
    
    blacklistedURLs = [args retain];
}
```

2017-01-10 09:32 UTC, hansemannn commented
Another issue: The loading spinner doesn't stop when the URL is blocked. I will add that change, fix the docs and merge then.

2017-01-10 09:45 UTC, hansemannn commented
CR + FT passed, PR approved!

2017-01-10 09:45 UTC, hansemannn approved these changes

2017-01-10 09:45 UTC, merged