[TIMOB-16005] Android: Non-fullscreen keyboard in landscape mode
appcelerator/titanium_mobile pull request #8785
Opened 2017-01-24 17:53 UTC by m1ga

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-16005

2017-01-24 17:53 UTC, build commented
Can one of the admins verify this patch?

2017-02-13 18:37 UTC, MasterLazer commented
CR && FT PASS

2017-02-13 18:45 UTC, frankieandone reviewed
CR && FT PASS

2017-02-15 19:13 UTC, hansemannn requested changes

2017-02-15 19:13 UTC, hansemannn commented on apidoc/Titanium/UI/TextArea.yml
> +    since: {android: "6.2.0"}
Wait, if we review this now, the `since` tag should be 6.1.0. Also, add a period in 211 please.

2017-02-15 19:13 UTC, hansemannn commented on apidoc/Titanium/UI/TextField.yml
> +    since: {android: "6.2.0"}
Same changes here, thanks Michael!

2017-02-15 19:54 UTC, m1ga commented on apidoc/Titanium/UI/TextArea.yml
> +    since: {android: "6.2.0"}
Nice! Changed it 👍

2017-03-09 02:11 UTC, lokeshchdhry commented
FR Passed.

With `fullscreen` set to true, we see some space left above the keyboard.
Checked with phone & tablet.

Appc Studio : 4.8.1.201612050850
SDK Version : Locally built 6.1.0
Mac OS Version : 10.12.2
Xcode Version : Xcode 8.2.1 Build version 8C1002
Appc CLI AND Appc NPM : {"NPM":"4.2.8","CLI":"6.1.0"}
Ti CLI : 5.0.11
Alloy : 1.9.5
Node : v4.6.0
Device: Nexus 6 android 6.0.1, Pixel Xl android 7.1.1
Emulator: Nexus 9 android 6.0

2017-03-09 02:12 UTC, merged