[TIMOB-24397] iOS: WebView - load a webpage with request headers
appcelerator/titanium_mobile pull request #8831
Opened 2017-02-10 16:55 UTC by chreck

Jira: https://jira.appcelerator.org/browse/TIMOB-24397

Move the setting of the request header into the function loadURLRequest.

2017-02-10 23:07 UTC, hansemannn requested changes

2017-02-11 13:37 UTC, hansemannn approved these changes

2017-02-11 13:37 UTC, hansemannn commented on iphone/Classes/TiUIWebView.m
> +        }
I've done it for you now.

2017-02-11 13:39 UTC, hansemannn commented
CR approved!

2017-02-16 17:05 UTC, longton95 commented
FR passed.
Webview now loads webpages with request headers tested using the test case in the ticket TIMOB-24397 as well as the test cases in TIMOB-17467 and TIMOB-24329


ENV
```
SDK Version : Local 6.1.0 
Mac OS Version : 10.12.2
Xcode Version : Xcode 8.2 Build version 8C38
Appc CLI : 6.1.0
Appc NPM : 4.2.9-1
Node : v4.6.0
Device: iPhone 6 (10.2.1) iPhone 5 (9.3.5)
```

2017-02-16 17:06 UTC, longton95 approved these changes
FR passed.
Webview now loads webpages with request headers tested using the test case in the ticket TIMOB-24397 as well as the test cases in TIMOB-17467 and TIMOB-24329


ENV
```
SDK Version : Local 6.1.0 
Mac OS Version : 10.12.2
Xcode Version : Xcode 8.2 Build version 8C38
Appc CLI : 6.1.0
Appc NPM : 4.2.9-1
Node : v4.6.0
Device: iPhone 6 (10.2.1) iPhone 5 (9.3.5)
```

2017-02-16 17:06 UTC, merged