[TIMOB-24400] Android: Support saving video files to gallery
appcelerator/titanium_mobile pull request #8837
Opened 2017-02-14 13:05 UTC by garymathews

- Amended `createExternalStorageFile()`
- Added video support for `Ti.Media.saveToPhotoGallery()` to maintain parity with iOS
- Updated documentation

###### TEST CASE
- Download [BigBuckBunny_320x180.mp4](http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4) and place into your project `Resources` folder
```Javascript
var videoFile = Ti.Filesystem.getFile('BigBuckBunny_320x180.mp4');

Ti.Media.saveToPhotoGallery(videoFile.read(), {
    success : function(e) {
        console.log('-> SUCCESS');
    },
    error : function(e) {
        console.log('-> ERROR', e)
    }
});
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24400)

2017-02-14 21:37 UTC, antw12 requested changes
After code review this works on a device that has a gallery, However with a pixel device this does not have a gallery and so the save will be unsuccessful as specified with logs after running the application, advised changes are to include another directory choice if it fails as it may be because the directory aka gallery does not exist on that device

2017-02-14 22:46 UTC, garymathews commented
Looks like you're missing write permission.

```XML
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
```Javascript
Ti.Android.requestPermissions(['android.permission.WRITE_EXTERNAL_STORAGE'], function(e) {
	if (e.success) {
	    // saveToPhotoGallery
	} else {
	    Ti.API.info('ERROR: ' + e.error);
	}
});
```

The `createExternalStorageFile()` method creates the directory path if it does not exist. Saving to gallery does not require a Gallery to exist. It saves the media to one of Androids default media folders (Pictures, Movies, Downloads etc..) which will be scanned by the Gallery or similar media viewer on the device.

2017-02-14 23:35 UTC, antw12 commented
`02-14 15:31:59.813 22728-22728/? I/art: Late-enabling -Xcheck:jni
02-14 15:31:59.844 22728-22728/com.titanium.test W/ActivityThread: Application com.titanium.test can be debugged on port 8100...
02-14 15:31:59.856 22728-22728/com.titanium.test I/TiApplication: (main) [0,0] checkpoint, app created.
02-14 15:31:59.859 22728-22728/com.titanium.test I/TiApplication: (main) [3,3] Titanium 1.0 (N/A N/A)
02-14 15:31:59.860 22728-22728/com.titanium.test I/MultiDex: VM with version 2.1.0 has multidex support
02-14 15:31:59.860 22728-22728/com.titanium.test I/MultiDex: install
02-14 15:31:59.860 22728-22728/com.titanium.test I/MultiDex: VM has multidex support, MultiDex support library is disabled.
02-14 15:31:59.892 22728-22728/com.titanium.test I/TiApplication: (main) [33,36] Titanium Javascript runtime: v8
02-14 15:31:59.921 22728-22728/com.titanium.test I/TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
02-14 15:32:00.242 22728-22728/com.titanium.test I/TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = com.titanium.test.TitaniumtestActivity@f78f4c5
02-14 15:32:00.257 22728-22754/com.titanium.test E/TiMedia: (KrollRuntimeThread) [15,15] Failed to create external storage directory.
02-14 15:32:00.266 22728-22754/com.titanium.test I/TiAPI:  -> ERROR {"code":-1,"success":false}
02-14 15:32:00.321 22728-22796/com.titanium.test I/Adreno: QUALCOMM build                   : a5b4970, If5818605d9
                                                           Build Date                       : 10/12/16
                                                           OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                           Local Branch                     : N24D
                                                           Remote Branch                    : 
                                                           Remote Branch                    : 
                                                           Reconstruct Branch               : 
02-14 15:32:00.324 22728-22796/com.titanium.test I/OpenGLRenderer: Initialized EGL, version 1.4
02-14 15:32:00.324 22728-22796/com.titanium.test D/OpenGLRenderer: Swap behavior 1
02-14 15:32:02.280 22728-22728/com.titanium.test W/APSAnalyticsHelper: Analytics service not found.`

This is the error for the pixel, but it seems to work with the S4 device. only difference i can tell is that S4 has a gallery directory and the pixel does not.

2017-02-15 18:47 UTC, antw12 commented
After Having a chat With Gary, we do not support android 7 for this feature and due to this in combination with it being ok with a device of a lesser version, im happy to pass the CR.

2017-02-15 18:47 UTC, antw12 approved these changes

2017-02-16 13:37 UTC, garymathews commented
@antw12 Just to clarify, could you test this on your Pixel?
###### tiapp.xml
```XML
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```

###### app.js
```Javascript
var permission = 'android.permission.WRITE_EXTERNAL_STORAGE';

function saveToGallery() {
    var videoFile = Ti.Filesystem.getFile('BigBuckBunny_320x180.mp4');
    Ti.Media.saveToPhotoGallery(videoFile.read(), {
        success : function(e) {
            console.log('SAVED TO GALLERY!');
        },
        error : function(e) {
            console.log('SAVE ERROR: ', e)
        }
    });
}

if (Ti.Android.hasPermission(permission)) {
    saveToGallery();
} else {
    Ti.Android.requestPermissions([permission], function(e) {
        if (e.success) {
            saveToGallery();
        } else {
            Ti.API.info('PERMISSIONS ERROR: ' + e.error);
        }
    });
}
```

2017-02-21 18:53 UTC, lokeshchdhry commented
FR Passed.

Video gets downloaded & saved successfully to the photo gallery.
1. Checked using the code provided above.
2. Also checked by downloading a video file & trying it to save to gallery.

Appc Studio : 4.8.1.201612050850
SDK Version : Local 6.1.0 build
Mac OS Version : 10.12.2
Xcode Version : Xcode 8.2.1 Build version 8C1002
Appc CLI AND Appc NPM : {"NPM":"4.2.9-2","CLI":"6.1.0"}
Ti CLI : 5.0.11
Alloy : 1.9.5
Node : v4.6.0
A0001e: running 6.0.1

2017-02-21 18:54 UTC, merged