[TIMOB-24429] Android: Only disable HW-acceleration for borderView below Lolipop
appcelerator/titanium_mobile pull request #8851
Opened 2017-02-28 14:45 UTC by garymathews

- Disable HW acceleration for Views with `borderRadius` only on Android versions below Lolipop and above Honecomb

###### TEST CASE
```Javascript
var win = Ti.UI.createWindow();
	view = Ti.UI.createView({
	    height: Ti.UI.FILL,
	    width: Ti.UI.FILL
	}),
	mapView = require('ti.map').createView({
	    height: Ti.UI.FILL,
	    width: Ti.UI.FILL,
	    borderRadius: 50
	});

view.add(mapView);
win.add(view);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24429)

2017-03-01 17:09 UTC, hansemannn requested changes

2017-03-03 17:44 UTC, garymathews commented on android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
> +	private static final boolean LOWER_THAN_LOLIPOP = (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP);
👍

2017-03-08 08:12 UTC, hansemannn submitted a review, later dismissed

2017-03-08 08:12 UTC, hansemannn commented on android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
> +					if (radius > 0f && HONEYCOMB_OR_GREATER && LOWER_THAN_LOLIPOP) {
Still the old name ⚠️

2017-03-08 08:12 UTC, hansemannn commented on android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
> +			if (radius > 0f && HONEYCOMB_OR_GREATER && LOWER_THAN_LOLIPOP) {
Same here

2017-03-09 14:00 UTC, maggieaxway approved these changes
CR FT PASS

2017-03-09 22:45 UTC, ssjsamir commented
@garymathews @maggieaxway,  On the Samsung Galaxy S5 device (Android 4.4.2) and Nexus 4 (4.4.4) (Versions below Lollipop). The Map does not take up the full screen unlike the Google Pixel which is running Android 7.1 but only take up a small section which is barley noticeable at the bottom. 

***Hardware acceleration is disabled**

**Below Lollipop Screenshot:** 
![below lollipop](https://cloud.githubusercontent.com/assets/10993278/23774069/c82c5d94-04d6-11e7-8a7b-691d8209cd96.png)

**7.1 Screenshot:** 
![7 1](https://cloud.githubusercontent.com/assets/10993278/23774075/cf8cca9c-04d6-11e7-9095-3f4a90b5f48b.png)

2017-03-14 14:09 UTC, garymathews commented
@ssjsamir Updated PR

2017-03-15 19:17 UTC, garymathews commented
https://github.com/appcelerator/titanium_mobile/pull/8872 has been reviewed and merged into 6_0_X, merging into master.

2017-03-15 19:17 UTC, merged