TIMOB-16080: Added New sound property for views
appcelerator/titanium_mobile pull request #8852
Opened 2017-02-28 19:44 UTC by antw12

**JIRA:** 
https://jira.appcelerator.org/browse/TIMOB-16080

**Description:**
Added a new property PROPERTY_TOUCH_SOUND_ENABLED allowing a user to set sound effects for views on or off.

Default for property is true

**Test Case**
```
var win = Ti.UI.createWindow({
    backgroundColor: 'black',
});

var view = Ti.UI.createView({
    soundEnabled : false,
    backgroundColor : "Black"
});
win.add(view);
win.open();
```

2017-02-28 23:33 UTC, hansemannn requested changes

2017-02-28 23:33 UTC, hansemannn commented on android/titanium/src/java/org/appcelerator/titanium/TiC.java
> +	public static final String PROPERTY_TOUCH_SOUND_ENABLED = "soundEnabled";
We should name it the same (`soundEffectsEnabled`), which would be mapped to `PROPERTY_SOUND_EFFECTS_ENABLED`.

2017-02-28 23:33 UTC, hansemannn commented on android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
> +		 boolean soundEnabled = TiConvert.toBoolean(proxy.getProperty(TiC.PROPERTY_TOUCH_SOUND_ENABLED), true);
Indentation incorrect.

2017-02-28 23:33 UTC, hansemannn commented on android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
> +			if (!soundEnabled) {
If this is `false` first, setting it to `true` will skip every time. Rather call the setter directly.

2017-02-28 23:41 UTC, antw12 commented on android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
> +			if (!soundEnabled) {
It is set to true as default as that is the native behavior, I tested it and it works so i am not sure, if I am still wrong please let me know

2017-03-01 00:29 UTC, garymathews requested changes

2017-03-01 00:29 UTC, garymathews commented on android/titanium/src/java/org/appcelerator/titanium/view/TiUIView.java
> +		if (proxy.hasProperty(TiC.PROPERTY_SOUND_EFFECTS_ENABLED)) {
```Java
if (proxy.hasProperty(TiC.PROPERTY_SOUND_EFFECTS_ENABLED)) {
	boolean soundEnabled = TiConvert.toBoolean(proxy.getProperty(TiC.PROPERTY_SOUND_EFFECTS_ENABLED), true);
	touchable.setSoundEffectsEnabled(soundEnabled);
}
```

2017-03-01 00:31 UTC, garymathews commented on android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
> +		defaultValues.put(TiC.PROPERTY_SOUND_EFFECTS_ENABLED, true);
This is necessarily needed since it's already enabled by default

2017-03-01 00:48 UTC, antw12 commented
for the PROPERTY_TOUCH_ENABLED should i change it to match, as it is set up the same with default as true?

2017-03-01 15:37 UTC, garymathews commented
@antw12 Yes, as that will not allow you to set `touchEnabled` back to `true`. Nice catch 👍

2017-03-07 14:08 UTC, garymathews commented
CR: **PASS** (note: try not to change the formatting of code you are not changing)
FT: **PASS**

2017-03-07 19:36 UTC, ssjsamir commented
FR Passed, was able to set `soundEffectsEnabled` to `true` or `false` and can confirm if it was set to to `true` sound effects can be heard and if set to `false` sound effects can not be heard. 

Steps I took to test:
+ Copy the code provided in the description
+ Ran the program
+ Was not able to hear the sound effects 
+ Edited the code and set `soundEffectsEnabled` to `true` 
+ Was able to hear the sound effects 

Environment

Appcelerator Command-Line Interface, version 6.1.0
Google Pixel XL (Android 7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 4.6.0
npm: 4.2.8
Xcode: 8.2
Appcelerator Studio: 4.8.1.201612050850

2017-03-07 19:46 UTC, merged