[TIMOB-24479] Android: fix TiUILabel maxLines not working
appcelerator/titanium_mobile pull request #8884
Opened 2017-03-13 19:53 UTC by fmerzadyan

Test Case:
Expect the long string to be in one line meaning no word wraps.
```
var win = Ti.UI.createWindow({
	theme: "Theme.AppCompat.Fullscreen",
	backgroundColor: '#fff'
});
var longString = "Welcome to the Appcelerator Platform! The Appcelerator Platform extends Appcelerator's Titanium platform to help you manage the entire lifecycle of the application with debugging, testing, deployment, crash monitoring and analytic data collection.";
var bigLabel = Ti.UI.createLabel({
	text: longString,
	color: '#4d4d4d',
	width: "90%",
	top: 0,
	maxLines: 1
});
win.add(bigLabel);
win.open();
```
**JIRA:** https://jira.appcelerator.org/browse/[TICKET]

2017-03-13 20:54 UTC, antw12 approved these changes
CR & FT PASS

2017-03-14 06:45 UTC, hansemannn commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUILabel.java
> +
Did you do the backport manually? I don't see this line in the backport, so I was wondering. Try to cherry-pick all changes for consistency.

2017-03-14 14:22 UTC, garymathews commented
@fmerzadyan Do we know what broke this in 6.0.0?

2017-03-14 16:09 UTC, garymathews commented
@fmerzadyan I think the problem is with `wordWrap` defaulting to `true`. So when `maxLines` of `1` is specified, the label enables `wordWrap` **after** setting `maxLines`, causing the line to wrap.

Try moving `maxLines` so it is processed after `wordWrap`

```Java
if (d.containsKey(TiC.PROPERTY_WORD_WRAP)) {
	wordWrap = TiConvert.toBoolean(d, TiC.PROPERTY_WORD_WRAP, true);
	tv.setSingleLine(!wordWrap);
}
if (d.containsKey(TiC.PROPERTY_MAX_LINES)) {
	tv.setMaxLines(TiConvert.toInt(d, TiC.PROPERTY_MAX_LINES));
}
```

2017-03-14 16:10 UTC, garymathews requested changes
@fmerzadyan I think the problem is with `wordWrap` defaulting to `true`. So when `maxLines` of `1` is specified, the label enables `wordWrap` **after** setting `maxLines`, causing the line to wrap.

Try moving `maxLines` so it is processed after `wordWrap`

```Java
if (d.containsKey(TiC.PROPERTY_WORD_WRAP)) {
	wordWrap = TiConvert.toBoolean(d, TiC.PROPERTY_WORD_WRAP, true);
	tv.setSingleLine(!wordWrap);
}
if (d.containsKey(TiC.PROPERTY_MAX_LINES)) {
	tv.setMaxLines(TiConvert.toInt(d, TiC.PROPERTY_MAX_LINES));
}
```

2017-03-14 17:31 UTC, fmerzadyan commented
@garymathews, the problem is that `setSingleLine` resets the `maxLines` property and `setSingleLine` method is used in multiple places in TiUILabel so the fix was to address those situations now rather than have this problem possibly come up in the future. But I'll do it just for the word wrap scenario if you say.

2017-03-14 17:33 UTC, fmerzadyan commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUILabel.java
> +
Yes, I did the backport manually which is linked [here](https://github.com/appcelerator/titanium_mobile/pull/8885).

2017-03-14 18:09 UTC, garymathews commented
@fmerzadyan I think it would be best to just move `maxLines` to be set after all of the properties that use `setSingleLine` and leave a comment to explain why `maxLines` should be processed last.

2017-03-14 18:20 UTC, fmerzadyan commented
@garymathews, No problem 👍

2017-03-14 18:30 UTC, antw12 commented
CR & FT PASS with new changes

2017-03-16 18:37 UTC, ssjsamir commented
FR Passed was able to set a long string to 1 line.

**Steps taken to test**

+ Copied the test case in the description
+ Pasted the code into a titanium project in appcelerator studio
+ Ran the program on device
+ Saw that string was set to one line as part of the string was missing

**Environment**
Appcelerator Command-Line Interface, version 6.1.0
Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 4.6.0
npm: 4.2.8
Xcode: 8.2
Appcelerator Studio: 4.8.1.201612050850

2017-03-17 12:57 UTC, garymathews approved these changes

2017-03-17 12:59 UTC, merged