[TIMOB-24478] Android: Fix postlayout event in TiCompositeLayout
appcelerator/titanium_mobile pull request #8887
Opened 2017-03-14 15:43 UTC by garymathews

- Fire `postlayout` when a change has happened to the underlying view
- `postlayout` event should only fire once after loading application

###### TEST CASE
```Javascript
var win = Ti.UI.createWindow({backgroundColor: 'gray'});
 
win.addEventListener('open', function() {
    Ti.API.info('open event fired.');
});
 
win.addEventListener('postlayout', function() {
    Ti.API.info('postlayout event fired.');
});
 
win.open();
```
```
I/TiAPI:  open event fired.
I/TiAPI:  postlayout event fired.
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24478)

2017-03-14 18:06 UTC, antw12 requested changes
Currently app works however, no events are fired, after debugging it does reach inside the  if check and perform the tasks but no post event or open even is fired/ logged

2017-03-15 14:22 UTC, garymathews commented
@antw12 Could you try again by compiling the SDK and testing? :)

I updated the test case, you should see a green background.

2017-03-16 20:24 UTC, antw12 approved these changes
CR & FR PASS 👍

2017-03-20 22:19 UTC, ssjsamir commented
FR passed, `postlayout` event was fired only once after loading the application. 

**Test steps**
+ Copied the test case in the description 
+ Pasted the code into a titanium project in appcelerator studio
+ Ran the program on device
+ `postlayout` event was fired only once
+ Minimized the application 
+ Re-opened it 
+ `postlayout` event was fired only once

**Environement**
Appcelerator Command-Line Interface, version 6.1.0
Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 4.6.0
npm: 4.2.8
Xcode: 8.2
Appcelerator Studio: 4.8.1.201612050850

2017-03-20 22:19 UTC, merged