[TIMOB-19924]: iOS "onclick" event is not triggered in the WebView if you are listening to multiple "click" events
appcelerator/titanium_mobile pull request #8913
Opened 2017-03-28 05:36 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-19924

2017-04-10 08:10 UTC, hansemannn requested changes

2017-04-10 08:10 UTC, hansemannn commented on iphone/Classes/TiUIView.m
> +    singleTapRecognizer.delegate = self;
Indentation here and all other places where you assign this delegate incorrect, please adjust.

2017-04-11 06:46 UTC, vijaysingh-axway commented on iphone/Classes/TiUIView.m
> +    singleTapRecognizer.delegate = self;
Done.

2017-04-11 07:51 UTC, hansemannn approved these changes

2017-04-11 07:52 UTC, hansemannn commented
PR approved! Please backport to 6_1_X

2017-04-12 14:56 UTC, htbryant94 approved these changes
Approved! "onclick" event now triggers correctly with multiple click events present. Tested for the added event types implemented from UIGestureRecognizer. 
iOS10.2.11 & iOS9.3

2017-04-12 14:56 UTC, merged