[TIMOB-23887]:Attributed string link on a TextArea doesn't fire link event
appcelerator/titanium_mobile pull request #8923
Opened 2017-04-04 05:30 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-23887

2017-04-10 08:34 UTC, hansemannn requested changes

2017-04-10 08:34 UTC, hansemannn commented on iphone/Classes/TiUITextArea.m
> +#import "TiUIAttributedStringProxy.h"
Everything related to other proxies should be wrapped:
```objc
#ifdef USE_TI_UIATTRIBUTEDSTRING
#import "TiUIAttributedStringProxy.h"
#endif
```
See the TiUITextWidget.m implementation for details.

2017-04-10 08:34 UTC, hansemannn commented on iphone/Classes/TiUITextArea.m
> +    BOOL testLink = (textWidgetView != nil) &&([(TiViewProxy*)[self proxy] _hasListeners:@"link" checkParent:NO]);
Missing space in `) &&(`.

2017-04-10 08:34 UTC, hansemannn commented on iphone/Classes/TiUITextArea.m
> +- (NSUInteger)characterIndexAtPoint:(NSAttributedString*)theString atPoint:(CGPoint)point
`NSAttributedString*` `NSAttributedString *`

2017-04-11 05:01 UTC, vijaysingh-axway commented on iphone/Classes/TiUITextArea.m
> +#import "TiUIAttributedStringProxy.h"
Done. Thanks.

2017-05-03 07:30 UTC, hansemannn approved these changes

2017-05-09 18:04 UTC, ewieberappc approved these changes
FR Passed, using:
MacOS 10.12 (16A323)
Studio 4.9.0.201704061825
Ti SDK 6.1.0.v20170503211832
Appc NPM 4.2.9
Appc CLI 6.2.0
Alloy 1.9.11
Xcode 8.3.2 (8E2002)

Attributed strings, inside non-editable text areas, with links now correctly fire the link event when clicked. Tested using the sample code and modified it to fully apply to the test case.

2017-05-10 15:41 UTC, merged