[TIMOB-23313] Disabled Swift settings for main Titanium project, but …
appcelerator/titanium_mobile pull request #8944
Opened 2017-04-07 17:59 UTC by cb1kenobi

[TIMOB-23313] Disabled Swift settings for main Titanium project, but ensure they are enabled in the extension targets.

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23313

2017-04-07 18:43 UTC, hansemannn requested changes

2017-04-07 18:43 UTC, hansemannn commented on iphone/cli/commands/_build.js
> +							extBuildSettings.SWIFT_VERSION = '2.2';
Should be Swift 2.3

2017-04-07 18:43 UTC, hansemannn commented on iphone/cli/commands/_build.js
> +		legacySwift = version.lt(this.xcodeEnv.version, '8.0.0');
Please note that the legacy Swift 2.3 can only be used until Xcode 8.2.1. They removed Swift 2.3 from Xcode 8.3 and later, classic Apple move. We should (very soon) only allow Swift 3.0 and later, so we are ready for Swift 4 already - which will be backwards-compatible to Swift 3.1.

2017-04-07 18:45 UTC, cb1kenobi commented on iphone/cli/commands/_build.js
> +							extBuildSettings.SWIFT_VERSION = '2.2';
Sounds like a different ticket.

2017-04-07 19:04 UTC, hansemannn commented on iphone/cli/commands/_build.js
> +							extBuildSettings.SWIFT_VERSION = '2.2';
Oh boi..okay.

2017-04-07 19:07 UTC, cb1kenobi commented on iphone/cli/commands/_build.js
> +							extBuildSettings.SWIFT_VERSION = '2.2';
I'm not opposed to changing it, but that's outside the scope of TIMOB-23313. I'm also all for dropping Swift 1 and 2.

2017-04-08 09:30 UTC, hansemannn approved these changes

2017-04-08 13:56 UTC, merged