[TIMOB-24565] iOS CLI: Improve the way dist-appstore build works
appcelerator/titanium_mobile pull request #8954
Opened 2017-04-10 21:01 UTC by ulizama

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24565

**Description:**

These changes add some features to the way `dist-appstore` packaging works to make it easier to integrate with other CLI tools such as [TiFastlane](https://github.com/ulizama/TiFastlane). The changes done are:

- When setting the flag `--build-only` XCode Organizer will not be launched after packaging is complete.
- The `method` param is set to `app-store` and included in the plist.
- A new flag `--export-ipa` has been included that makes the CLI generate an *ipa* instead of storing an *xarchive* into the organizer. Following the adhoc build method, the ipa archive is stored in the directory set by `--output-dir`

2017-04-11 03:06 UTC, cb1kenobi requested changes

2017-04-11 03:06 UTC, cb1kenobi commented on iphone/cli/locales/en.js
> +	"for %s builds, exports archive into an ipa and places it on %s": "for %s builds, exports archive into an ipa and places it on %s",
There's no need to update the locale file. It's so out-of-date, it doesn't really matter.

2017-04-11 08:02 UTC, hansemannn commented on iphone/cli/commands/_build.js
> +							desc: __('for %s builds, exports archive into an ipa and places it on %s', 'dist-appstore'.cyan, 'output-dir'.cyan)
Capitalize `For` and use `places it in` instead of `places it on`.

2017-04-11 08:03 UTC, hansemannn commented on iphone/cli/hooks/package.js
> +							logger.warn(__('Invalid %s, skipping packaging', '--output-dir'.cyan));
`Invalid output directory %s`

2017-04-11 14:34 UTC, ulizama commented on iphone/cli/commands/_build.js
> +		plist.method = "app-store";
I'll remove this, we'll be doing this anyway on the new centralized export ipa function that would be used both for ad-hoc and appstore builds.

2017-04-11 15:20 UTC, cb1kenobi commented on iphone/cli/commands/_build.js
> +						'export-ipa': {
Yes and no. Yes to the first part. No to the second part. You need to the xarchive because that's what you're exporting the .ipa from.

2017-04-11 15:35 UTC, ulizama commented on iphone/cli/commands/_build.js
> +						'export-ipa': {
You are right, understood.

2017-04-11 22:47 UTC, ulizama commented
Pushed the changes based on the review ;)

2017-04-11 23:33 UTC, cb1kenobi commented
@ulizama Awesome! Let me re-review as soon as I get a few minutes. After we get this merged, I'll backport it 6_1_X so that it ships sooner. Stay tuned.

2017-04-14 14:56 UTC, cb1kenobi approved these changes

2017-04-14 15:08 UTC, ulizama commented
Thanks for approving!

Question, in what release will this be included?

Looking back I think I might have pushed the PR to the wrong branch and maybe I should have had done it in the `6_0_X` branch, right?

2017-04-14 15:18 UTC, cb1kenobi commented
@ulizama 6_0_X is off limits. It's frozen for the super soon to be released `6.0.4.GA`.

`master` is the correct branch. Once your PR is merged, I'll clean it up and backport to `6_1_X`. Your fix will go with `6.1.0`, which I have no clue when that will ship.

After `6.0.4.GA` is shipped and if we do a `6.0.5.GA`, which I doubt, then I could try to backport this again.

In the meantime, I need to make sure you've signed the contributor license agreement (https://cla.appcelerator.com) and that the merge conflicts have been resolved. As of right this second, it appears you need to pull from master and fix any conflicts. Sound good?

Thanks!

2017-04-14 16:10 UTC, ulizama commented
Hi @cb1kenobi, yes I have signed the license.

@hansemannn You beat me to the punch 😄

2017-04-14 20:59 UTC, cb1kenobi commented
**APPROVED**!

Thanks @ulizama for your contribution! Much appreciated!

2017-04-14 20:59 UTC, merged

2017-04-14 21:28 UTC, ulizama commented
Yey! Now Titanium has a piece of me 😺