[TIMOB-4979] Android: Expose dragstart and dragend on ScrollView
appcelerator/titanium_mobile pull request #8968
Opened 2017-04-17 16:19 UTC by m1ga

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-4979

```javascript
var win = Ti.UI.createWindow({
	backgroundColor: "#fff"
});
var scrollView = Ti.UI.createScrollView({
	height: Ti.UI.FILL,
	width: Ti.UI.FILL,
	contentHeight: 4000,
	scrollType: "vertical"
})

function onScrolling(e) {
	console.log("Scrolling");
}

function onDragstart(e) {
	console.log("---Drag start---");
}

function onDragend(e) {
	console.log("---Drag end---");
}
scrollView.addEventListener("scroll", onScrolling);
scrollView.addEventListener("dragstart", onDragstart);
scrollView.addEventListener("dragend", onDragend);
win.add(scrollView);
win.open();
```

2017-04-19 14:26 UTC, garymathews commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java
```Java
KrollDict data = new KrollDict();
```

2017-04-19 14:35 UTC, garymathews requested changes

2017-04-19 14:35 UTC, garymathews commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java
```Java
KrollDict data = new KrollDict();
```

2017-04-19 14:35 UTC, garymathews commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java
>  			KrollDict data = new KrollDict();
```Java
data = new KrollDict();
```

2017-04-19 14:35 UTC, garymathews commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java
> +				data = new KrollDict();
Remove this line

2017-04-19 14:35 UTC, garymathews commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java
> +			if (event.getAction() == MotionEvent.ACTION_MOVE && !isTouching) {
Should probably put these conditions below:
```Java
if (event.getAction() == MotionEvent.ACTION_MOVE && !mScrollingEnabled) {
```
to not fire when `scrollingEnabled` is false?

2017-04-19 19:53 UTC, m1ga commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIScrollView.java
> +			if (event.getAction() == MotionEvent.ACTION_MOVE && !isTouching) {
sure, makes sense!

2017-04-20 14:28 UTC, garymathews approved these changes

2017-04-20 15:12 UTC, hansemannn commented
@garymathews Can we move on to QE-testing?

2017-04-20 15:23 UTC, garymathews commented
@hansemannn Yes 👍

2017-04-24 22:13 UTC, ssjsamir approved these changes
FR Passed - was able to see `dragstart` and `dragend` on the scroll view from the console. 

**Test Steps**
+ Copied the test case from the description above
+ Tested the test case with the build from this PR
+ Ran the program on android emulator (Nexus 6 running Android 7.0)
+ Scrolled up and down 
+ `dragstart` and `dragend`  was viewable in the console 

**Output from the console:**
```
[INFO] :   ---Drag start---
[INFO] :   Scrolling
[INFO] :   Scrolling
[INFO] :   Scrolling
[INFO] :   Scrolling
[INFO] :   Scrolling
[INFO] :   Scrolling
[INFO] :   Scrolling
[INFO] :   Scrolling
[INFO] :   ---Drag end---
[INFO] :   Scrolling
[INFO] :   Scrolling
[INFO] :   Scrolling
```
**Test environment**
Appcelerator Command-Line Interface, version 6.2.0
Android Emulator (Nexus 6 running android 7.0)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 4.6.0
npm: 4.2.9
Xcode: 8.2
Appcelerator Studio: 4.8.1.201612050850

2017-05-23 17:23 UTC, merged