[TIMOB-24607] Android: stop network connectivity change event firing at start
appcelerator/titanium_mobile pull request #8981
Opened 2017-04-20 18:15 UTC by fmerzadyan

#### Test Case:
Expect to not see `test msg: change event` in log output on application start up. Turn wifi on/off. Expect to see message in logs.
```
Ti.Network.addEventListener("change", function(e) {
	console.log("test msg: change event")
});
```

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24607

2017-04-20 22:05 UTC, jquick-axway approved these changes
Approved

2017-04-20 23:25 UTC, hansemannn requested changes

2017-04-20 23:25 UTC, hansemannn commented on android/modules/network/src/java/ti/modules/titanium/network/TiNetworkListener.java
>              String action = intent.getAction();
Indentation

2017-05-15 18:02 UTC, longton95 approved these changes
FR passed.

Tested using the test case above, the change event is not fired on creation.

ENV
```
SDK Version : Local 6.2.0
Mac OS Version : 10.12.4
Appc CLI : 6.2.1
Appc NPM : 4.2.9
Node : v4.6.0
Device: Nexus 5x(6.0.1) Pixel XL(7.1.2)
Emulator: (6.0), (4.4.2)
```

2017-05-15 18:40 UTC, merged