[AC-4926] Notification wake lock
appcelerator/titanium_mobile pull request #8990
Opened 2017-04-25 18:47 UTC by m1ga

**JIRA:** https://jira.appcelerator.org/browse/AC-4926

2017-04-26 08:04 UTC, hansemannn requested changes

2017-04-26 08:04 UTC, hansemannn commented on apidoc/Titanium/Android/Notification.yml
> +
Replace with:
```yml
summary: |
    Will wake up the device for the given time (in milliseconds) when the notification is shown.
    The application needs to also set the `android.permission.WAKE_LOCK` permission
    in the Android manifest section of the `tiapp.xml` file.
```

2017-04-26 08:04 UTC, hansemannn commented on android/modules/android/src/java/ti/modules/titanium/android/notificationmanager/NotificationManagerModule.java
> +    			wl.acquire(wakeTime);
Indentation in 86 and space in `){`. Maybe rename `MyWakeLock` to `TiWakeLock`.

2017-04-26 10:18 UTC, garymathews commented on android/modules/android/src/java/ti/modules/titanium/android/notificationmanager/NotificationManagerModule.java
> +
Also remove this extra line :)

2017-04-26 10:21 UTC, hansemannn commented on android/modules/android/src/java/ti/modules/titanium/android/notificationmanager/NotificationManagerModule.java
> +			if(isScreenOn==false) {
Same here btw: Spaces spaces spaces 👾

2017-04-26 19:10 UTC, m1ga commented
Change the parameter to accept a HashMap like this: `wakeLock:{time: 1000, flag: Ti.Android.PARTIAL_WAKE_LOCK}` to be more flexible.

2017-04-27 06:27 UTC, hansemannn commented on apidoc/Titanium/Android/Notification.yml
> +    default: Titanium.Android.FULL_WAKE_LOCK | Titanium.Android.ACQUIRE_CAUSES_WAKEUP | Titanium.Android.ON_AFTER_RELEASE
We usually prefix the constants so it's easier to find and group them. For example:
- WAKE_LOCK_PARTIAL
- WAKE_LOCK_FULL
- WAKE_LOCK_SCREEN_DIM

Then you could also also write `constants: [Titanium.Android_WAKE_LOCK_*]`

2017-04-27 16:09 UTC, m1ga commented on apidoc/Titanium/Android/Notification.yml
> +    default: Titanium.Android.FULL_WAKE_LOCK | Titanium.Android.ACQUIRE_CAUSES_WAKEUP | Titanium.Android.ON_AFTER_RELEASE
Ah, nice! I've made the changes.

2017-04-27 16:19 UTC, hansemannn requested changes

2017-04-27 16:19 UTC, hansemannn commented on apidoc/Titanium/Android/Notification.yml
> +    constants: [Titanium.Android_WAKE_LOCK_*]
`Titanium.Android_WAKE_LOCK_*` -> `Titanium.Android.WAKE_LOCK_*`

2017-04-27 16:19 UTC, hansemannn commented on android/modules/android/src/java/ti/modules/titanium/android/AndroidModule.java
> +	@Kroll.constant public static final int WAKE_LOCK_ON_AFTER_RELEASE = PowerManager.ON_AFTER_RELEASE;
Missing docs for the constants?

2017-04-27 16:27 UTC, m1ga commented on android/modules/android/src/java/ti/modules/titanium/android/AndroidModule.java
> +	@Kroll.constant public static final int WAKE_LOCK_ON_AFTER_RELEASE = PowerManager.ON_AFTER_RELEASE;
missing file :-)

2017-04-28 04:59 UTC, hansemannn commented
LGMT! @garymathews for an additional review.

2017-04-28 04:59 UTC, hansemannn approved these changes

2017-05-20 14:24 UTC, hansemannn commented
@m1ga You closed the PR? :(

2017-05-20 14:39 UTC, m1ga commented
oh sorry. closed the wrong branch

2017-08-11 11:02 UTC, garymathews approved these changes
CR: **PASS**

Conflict needs fixing though

2017-08-11 16:37 UTC, hansemannn commented
I think my latest resolve of the merge-conflicts screw up around [here](https://github.com/appcelerator/titanium_mobile/pull/8990/commits/2390370b481cffe295491d0c66f96f3756229d53#diff-ca6cb052e5d20d93fc0baecf77560c3bR128). Also, the backport #9307 has a different number of lines and removed the `dragstart` event-key from the code, no idea why (it was only removed in an earlier commit but restored later). So we need to check those issue first before giving it to QE.

2017-08-22 22:28 UTC, lokeshchdhry commented
@garymathews , @m1ga , 
I am having issues when I try to test. I am checking with the above code.
It works fine with `flags: Ti.Android.PARTIAL_WAKE_LOCK`, but not with any other flag. The screen does not turn on at full brightness or in dim state when the notification arrives. 
Also, for flag `flags: Ti.Android.WAKE_LOCK_ACQUIRE_CAUSES_WAKEUP` I am getting the below errors:
```
[WARN] :   W/System.err: java.lang.IllegalArgumentException: Must specify a valid wake lock level.
[WARN] :   W/System.err: 	at android.os.PowerManager.validateWakeLockParameters(PowerManager.java:517)
[WARN] :   W/System.err: 	at android.os.PowerManager.newWakeLock(PowerManager.java:501)
[WARN] :   W/System.err: 	at ti.modules.titanium.android.notificationmanager.NotificationManagerModule.notify(NotificationManagerModule.java:89)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Function.nativeInvoke(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Function.callSync(V8Function.java:57)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Function.call(V8Function.java:43)
[WARN] :   W/System.err: 	at ti.modules.titanium.TitaniumModule$Timer.run(TitaniumModule.java:147)
[WARN] :   W/System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:148)
[WARN] :   W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[WARN] :   W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] :  TiExceptionHandler: (main) [4352,4352] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,4352] - In /app.js:31,40
[ERROR] :  TiExceptionHandler: (main) [1,4353] - Message: Uncaught Must specify a valid wake lock level.
[ERROR] :  TiExceptionHandler: (main) [0,4353] - Source: 		Titanium.Android.NotificationManager.notify(1, notification);
[ERROR] :  V8Exception: Exception occurred at /app.js:31: Uncaught Must specify a valid wake lock level.
[ERROR] :  V8Exception: Must specify a valid wake lock level.
```

2017-08-22 22:30 UTC, lokeshchdhry commented
Failing FR for now.

2017-08-23 05:54 UTC, m1ga commented
ACQUIRE_CAUSES_WAKEUP and ON_AFTER_RELEASE are flags you can add to the WAKE_LOCK levels. See https://developer.android.com/reference/android/os/PowerManager.html
I'll implement a check so it will show an error instead of the crash

2017-08-23 18:48 UTC, lokeshchdhry commented
@m1ga , Thanks for the link I was using the flags in a wrong way. It works fine. But with flag `WAKE_LOCK_SCREEN_BRIGHT` & `WAKE_LOCK_FULL` the screen turns `ON` but not at the full brightness.

2017-08-23 19:11 UTC, garymathews commented
@lokeshchdhry here's another test case

```JS
var win = Ti.UI.createWindow({
        title: 'TIMOB-24629',
        backgroundColor: 'gray'
    }),
    btn = Ti.UI.createButton({
        title: 'START',
        width: '33%'
    }),
    ntn = Titanium.Android.createNotification({
        contentTitle: 'WAKE-LOCK TEST',
        contentText: 'Do nothing...',
        wakeLock: {
            time: 3000,
            flags: Ti.Android.WAKE_LOCK_FULL | Ti.Android.WAKE_LOCK_ACQUIRE_CAUSES_WAKEUP | Ti.Android.WAKE_LOCK_ON_AFTER_RELEASE
        }
    });

btn.addEventListener('click', function() {
    var i = 4,
        interval = setInterval(function() {
            btn.setTitle('COUNT ' + --i);
            if (i <= 0) {
                Ti.Android.NotificationManager.notify(1, ntn);
                clearInterval(interval);
                btn.setTitle('START');
                btn.setEnabled(true);
            }
        }, 1000);
    btn.setEnabled(false);
    btn.setTitle('COUNT ' + --i);
});

win.add(btn);
win.open();
```

2017-08-23 20:43 UTC, lokeshchdhry commented
Thanks @garymathews , I was using the flags in a wrong way. But, as I have commented above with flag `WAKE_LOCK_SCREEN_BRIGHT` & `WAKE_LOCK_FULL` the screen turns `ON` but not at the full brightness. 
Is this expected ?

2017-08-23 21:33 UTC, garymathews commented
@lokeshchdhry I would say it's expected behaviour since the flags are being set correctly, that behaviour is dictated by Android.

2017-08-23 23:37 UTC, merged