[TIMOB-24664] Update to Android support library 25.3.1
appcelerator/titanium_mobile pull request #9027
Opened 2017-05-08 10:01 UTC by garymathews

- Update Android support libraries to `25.3.1`

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24664)

2017-05-08 11:07 UTC, hansemannn commented on android/modules/cardview/.classpath
> +	<classpathentry exported="true" kind="lib" path="lib/cardview-v7-23.0.1.jar"/>
From 23.4.0 to 23.0.1?

2017-05-08 12:13 UTC, garymathews commented on android/modules/cardview/.classpath
> +	<classpathentry exported="true" kind="lib" path="lib/cardview-v7-23.0.1.jar"/>
Yeah, that's from reverting https://github.com/appcelerator/titanium_mobile/pull/9027/commits/80b4302cbb84690591b32837f5dea9825ac4d4f1, `.classpath` aren't used anymore. They are left-overs from Eclipse.

Also, Jenkins is failing due to Android SDK 25 not being installed.

2017-05-08 14:05 UTC, janvennemann requested changes

2017-05-12 14:39 UTC, garymathews commented
@janvennemann Updated `.classpath` dependencies

2017-05-26 09:48 UTC, janvennemann approved these changes
CR: Pass

Approved!

2017-06-06 13:31 UTC, garymathews commented
@janvennemann I updated this PR to add the `android.support.design` library

2017-06-08 17:37 UTC, janvennemann approved these changes
Looks good! 👍

2017-06-28 15:26 UTC, janvennemann approved these changes

2017-07-20 23:20 UTC, lokeshchdhry commented
@janvennemann , 
 I followed the steps you mentioned in https://jira.appcelerator.org/browse/TIMOB-24446?focusedCommentId=419942&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-419942

But when I build with 6.2.0 SDK it fails to dexer:
```
[ERROR] :  Failed to run dexer:

[ERROR] :  

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/design/internal/package-info;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/design/internal/BaselineLayout;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/design/internal/BottomNavigationAnimationHelperBase;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/design/internal/BottomNavigationAnimationHelperIcs;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/design/internal/BottomNavigationItemView;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/design/internal/BottomNavigationMenu;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/design/internal/BottomNavigationMenuView;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/design/internal/BottomNavigationMenuView$1;

[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/design/internal/BottomNavigationPresenter;

[ERROR] :  

[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:

[ERROR] :  java.lang.RuntimeException: Translation has been interrupted

[ERROR] :  at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)

[ERROR] :  at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)

[ERROR] :  at com.android.dx.command.dexer.Main.runDx(Main.java:289)

[ERROR] :  at com.android.dx.command.dexer.Main.main(Main.java:247)

[ERROR] :  at com.android.dx.command.Main.main(Main.java:94)

[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors

[ERROR] :  at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)

[ERROR] :  ... 4 more
 ```
Am I missing something here ?

2017-07-21 16:26 UTC, lokeshchdhry commented
FR Passed.

Used the test steps here : https://jira.appcelerator.org/browse/TIMOB-24446?focusedCommentId=419942&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-419942

Studio Ver:     4.9.1.201707200100
SDK Ver:        6.2.0.v20170720154351 from  Jenkins in PR
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.2
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        Android 6.0, Android 7.0

2017-07-21 16:29 UTC, merged