[TIMOB-24680] Fixed list of valid provisioning profiles for the given…
appcelerator/titanium_mobile pull request #9056
Opened 2017-05-11 19:20 UTC by cb1kenobi

[TIMOB-24680] Fixed list of valid provisioning profiles for the given build target which is used to validate watch extension provisioning profile uuids.

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24680

2017-05-12 09:51 UTC, hansemannn requested changes

2017-05-12 09:51 UTC, hansemannn commented on iphone/cli/commands/_build.js
> +		}
We use that method too often. Please add this helper to our utils instead of pasting it to every usage.

2017-05-12 13:17 UTC, hansemannn approved these changes

2017-05-12 13:46 UTC, cb1kenobi commented on iphone/cli/commands/_build.js
> +		}
Great idea for the next overhaul.

2017-05-31 15:23 UTC, htbryant94 approved these changes
Approved! Enterprise Adhoc Provisioning Profiles are now validated correctly for Watch Extensions, and build failures no longer occur.

2017-05-31 15:26 UTC, hansemannn commented
@htbryant94 Wait a second, should this go into 6.1.1? Because you just merged into 6_1_X, not master. The ticket says 6.2.0, however, I'd be fine for a 6.1.1 if @eric34 approves.

2017-05-31 20:47 UTC, merged

2017-06-02 14:08 UTC, htbryant94 commented
@hansemannn I asked @eric34 whether to merge the fix into the 6_1_X branch as well as the master, and was confirmed to do so. It would be good to get a second approval just in case, however I do not see any reason why it shouldn't go into 6.1.1