[TIMOB-20037] Android: Wrong Ti.Android.currentActivity in `open` handler
appcelerator/titanium_mobile pull request #9071
Opened 2017-05-19 14:19 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-20037

**Test case:**
```
var window = Ti.UI.createWindow({backgroundColor:'#F00'});

window.addEventListener('open', function (e) {
    Ti.API.debug('Main window opened', e.source.getActivity() === Ti.Android.currentActivity);
});
```

window.open();

**Optional Description:**
Added Kroll property getter in the module.

2017-05-25 15:34 UTC, garymathews requested changes
CR: Fix imports

2017-05-25 15:34 UTC, garymathews commented on android/titanium/src/java/org/appcelerator/titanium/TiApplication.java
> +import org.appcelerator.kroll.*;
Should revert these imports back to not use wildcards

2017-05-25 15:37 UTC, garymathews commented on android/modules/android/src/java/ti/modules/titanium/android/AndroidModule.java
> +		return TiApplication.getAppCurrentActivity().getActivityProxy();
It is possible for `getAppCurrentActivity()` to return `null`, best add a guard.

2017-05-26 08:13 UTC, ypbnv commented
@garymathews Reverted the imports and added a guard and a warning.

2017-05-26 15:25 UTC, garymathews approved these changes
CR: **PASS**

2017-06-08 16:57 UTC, ssjsamir approved these changes
FR passed: currentActivity is now the same as the current window activity. This can be seen by the following output in the console: 
```
[DEBUG] :  Window: Checkpoint: postWindowCreated()
[DEBUG] :  Main window opened true
```
**Test Steps**
+ Downloaded the SDK Build form this PR
+ Created a new Titanium project
+ Copied the the test case from description
+ Ran the application 
+ Saw the above output in the console

**Test Environment**
Appcelerator Command-Line Interface, version 6.2.2
Google Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705251638

2017-06-08 16:57 UTC, merged