[TIMOB-24718]:iOS: Resolve iOS 8 deprecations for UIAlertView and UIActionSheet
appcelerator/titanium_mobile pull request #9079
Opened 2017-05-24 03:54 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-24718

2017-05-24 07:46 UTC, hansemannn requested changes

2017-05-24 07:46 UTC, hansemannn commented on iphone/Classes/TiUIAlertDialogProxy.m
> +        RELEASE_TO_NIL(alertController);
Something went wrong with the indentation starting here, making the remaining part of the PR unreadable.

2017-05-24 10:11 UTC, hansemannn commented on iphone/Classes/TiUIAlertDialogProxy.m
> +        RELEASE_TO_NIL(alertController);
Sorry, it doesn't. The indentation just changed because of the removed if-statement. Continuing review ...

2017-05-24 10:12 UTC, hansemannn commented on iphone/Classes/TiUIAlertDialogProxy.m
>  	}
Indentation looks weird here.

2017-05-24 10:13 UTC, hansemannn commented on iphone/Classes/TiUIOptionDialogProxy.m
> +	if (alertController == nil){
Add space here

2017-05-24 10:14 UTC, hansemannn requested changes
Only one weird indentation issue in [here](https://github.com/appcelerator/titanium_mobile/pull/9079/files#diff-555b954d27366b71baafd59e61898316R184) and minor formatting. Please address those, then we should be good to go.

2017-05-25 04:04 UTC, vijaysingh-axway commented on iphone/Classes/TiUIOptionDialogProxy.m
> +	if (alertController == nil){
Done.

2017-05-26 19:46 UTC, hansemannn approved these changes

2017-06-20 14:54 UTC, htbryant94 approved these changes
Approved! ran test cases for OptionDialog / ActionSheet & AlertDialog / AlertView against iOS8/9/10 with Ti SDK 6.1.0.GA & Master.

2017-06-20 14:58 UTC, merged