[TIMOB-24729]:iOS: Resolve iOS 8 deprecations for ABPeoplePickerNavigationController
appcelerator/titanium_mobile pull request #9080
Opened 2017-05-24 08:01 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-24729

2017-05-24 10:09 UTC, hansemannn requested changes
Minor changes, thx!

2017-05-24 10:09 UTC, hansemannn commented on iphone/Classes/ContactsModule.m
> +        if ([TiUtils isIOS8OrGreater] && (ABAddressBookGetAuthorizationStatus() != kABAuthorizationStatusAuthorized)) {
`[TiUtils isIOS8OrGreater]` should not be required when a) the delegate only fires for iOS8+ and b) we target iOS 8+.

2017-05-24 10:09 UTC, hansemannn commented on iphone/Classes/ContactsModule.m
> +        {
Brackets again :-)

2017-05-24 10:09 UTC, hansemannn commented on iphone/Classes/ContactsModule.m
> +        else if (identifier == kABMultiValueInvalidIdentifier) {
} else if

2017-05-25 03:49 UTC, vijaysingh-axway commented on iphone/Classes/ContactsModule.m
> +        if ([TiUtils isIOS8OrGreater] && (ABAddressBookGetAuthorizationStatus() != kABAuthorizationStatusAuthorized)) {
Done.

2017-05-25 03:49 UTC, vijaysingh-axway commented on iphone/Classes/ContactsModule.m
> +        else if (identifier == kABMultiValueInvalidIdentifier) {
Done. Thanks

2017-05-25 07:25 UTC, hansemannn requested changes

2017-05-25 07:25 UTC, hansemannn commented on iphone/Classes/ContactsModule.m
>  	[picker setPeoplePickerDelegate:self];
Can you fix the indentation here and in line 376/377.

2017-05-25 07:57 UTC, vijaysingh-axway commented on iphone/Classes/ContactsModule.m
>  	[picker setPeoplePickerDelegate:self];
In xcode it was shows proper indentation. Maybe some legacy issue. Done.

2017-05-25 09:21 UTC, hansemannn commented on iphone/Classes/ContactsModule.m
>                      [pickerFields addObject:property];
Close to correct :P

2017-05-26 19:44 UTC, hansemannn approved these changes

2017-06-19 15:16 UTC, htbryant94 approved these changes
Approved! ran test case against iOS8/9/10 with Ti SDK 6.1.0.GA & Master.

2017-06-19 15:18 UTC, merged