[TIMOB-24702] Android: Fix onDestroy dispatchCallback
appcelerator/titanium_mobile pull request #9096
Opened 2017-05-30 11:06 UTC by garymathews

- Fix `TiBaseActivity` `dispatchCallback`
- Fix `TiViewProxy` `MSG_GETSIZE` and `MSG_GETRECT`

```JS
var win = Titanium.UI.createWindow(),
    btn = Ti.UI.createButton({
        title: 'CLOSE'
    });

btn.addEventListener('click', function(e) {
	var activity = Ti.Android.currentActivity;
	if (!activity) {
		return;
	}

	activity.onDestroy = function(e) {
		var size = btn.size;
		var rect = btn.rect;
	};
	activity.finish();
});

win.add(btn);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24702)

2017-05-30 17:46 UTC, jquick-axway commented
@garymathews, you need to check if the getAppRootOrCurrentActivity() or getAppCurrentActivity() methods return null in the handleMessage() method. The reason is because an Android Handler's dispatched/posted message/runnable can still be invoked on the main UI thread even if there is no UI/activity being displayed... and you can't assume a handler's runnable/message has been invoked on-time.

That is, a Handler is not bound to an active activity. You can post a message/runnable via a handler to be invoked say 1 minute later, back out of all activities, and that posted message/runnable will still be received/invoked while the app is in the background without any UI. This is normal behavior on Android.

2017-06-01 15:31 UTC, ypbnv requested changes

2017-06-01 15:31 UTC, ypbnv commented on android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
Guard for null result from getAppRootOrCurrentActivity()

2017-06-01 15:31 UTC, ypbnv commented on android/titanium/src/java/org/appcelerator/titanium/proxy/TiViewProxy.java
Guard for null result from getAppRootOrCurrentActivity()

2017-07-05 12:27 UTC, garymathews commented
@ypbnv Updated PR

2017-07-06 13:35 UTC, ypbnv approved these changes
CR: Pass

2017-07-14 22:12 UTC, ssjsamir approved these changes
**FR Passed** application no longer crashes when accessing 'size' & 'rect' button properties after activity.finish().

**Test Steps**
+ Downloaded the SDK Build from this PR
+ Created a new Titanium project
+ Copied the the test case from description
+ Ran the application 
+ Pressed `Close`
+ Window closed without any issues

**Test Environment**
Appcelerator Command-Line Interface, version 6.2.2
Google Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705251638

2017-07-14 22:14 UTC, merged