(6_1_X) [TIMOB-24796] iOS: Hybrid CommonJS and Native modules don't handl…
appcelerator/titanium_mobile pull request #9132
Opened 2017-06-08 20:19 UTC by sgtcoolguy

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24796

**Optional Description:**
back port of #9131

2017-06-08 20:24 UTC, sgtcoolguy commented
QE/FR steps: https://jira.appcelerator.org/browse/TIMOB-24796?focusedCommentId=421562&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-421562

2017-06-09 15:54 UTC, hansemannn approved these changes
CR looks fine, let's go for it!

2017-06-09 18:00 UTC, hansemannn requested changes

2017-06-09 18:00 UTC, hansemannn commented on iphone/Classes/TiModule.m
> +        if (data != null) {
Use `nil` please

2017-06-12 14:58 UTC, hansemannn approved these changes

2017-06-15 18:27 UTC, mukherjee2 approved these changes
Passed FR! With this environment:
Node Version: 6.10.3
NPM Version: 3.10.10
Mac OS: 10.12.4
Appc CLI: 6.2.2
Appc CLI NPM: 4.2.9
Titanium SDK version: 6.1.1 pr/9132
Appcelerator Studio, build: 4.9.0.201705302345-39
Xcode 8.3.2

I followed the instructions in the ticket to build the module. The module was successfully built. Then I used the module in the demo app. App worked as expected, and no errors were seen.

2017-06-15 18:27 UTC, merged