[TIMOB-24731] : iOS Resolve iOS 8 deprecations for willAnimateRotationToInterfaceOrientation
appcelerator/titanium_mobile pull request #9138
Opened 2017-06-12 04:37 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-24731

2017-06-12 07:35 UTC, hansemannn requested changes
Great job @vijaysingh-axway! Left one note regarding `super` calls (or did you leave them blank intentionally), the rest looks fine. 

We need extensive test-cases for orientation tests of all involved elements (especially top-level-views like tab-group, navigation-window and container-views like tableview and scrollable-view). 

QE will have proper ones I guess!

2017-06-12 07:35 UTC, hansemannn commented on iphone/Classes/TiUIScrollableViewProxy.m
> +}
Super calls?

2017-06-12 08:12 UTC, vijaysingh-axway commented on iphone/Classes/TiUIScrollableViewProxy.m
> +}
This is intentional. No need to call super. These are end calls . These protocols  are implemented here  to play safe. If it get call from somewhere without check, app will ensure to not crash.  Required changes for scrollview is implemented as per previous implementation , in method -
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator>)coordinator

2017-07-04 00:49 UTC, hansemannn approved these changes

2017-08-01 23:16 UTC, mukherjee2 approved these changes
Node Version: 6.10.3
NPM Version: 3.10.10
Mac OS: 10.12.4
Appc CLI: 6.2.2
Appc CLI NPM: 4.2.9
Titanium SDK version: 7.0.0.v20170801101611
Appcelerator Studio, build: 4.9.1.201707200100
Xcode 8.3.2
iOS 9 and 10 Devices, iPhone 6S Plus, iPad Pro 12.9"

I tried all four test cases in the original Jira ticket, and rotating the windows appeared to work correctly. Split window worked correctly on the iPad when rotated.

2017-08-08 21:02 UTC, merged