[TIMOB-24822] Fix TableView issue on Android N
appcelerator/titanium_mobile pull request #9144
Opened 2017-06-14 22:27 UTC by garymathews

- Caused by https://github.com/appcelerator/titanium_mobile/pull/8948
- Created a better fix for TIMOB-24560

###### TEST CASE #1
```JS
var win = Ti.UI.createWindow({
        backgroundColor: 'gray',
        layout: 'vertical'
    }),
    tv = Ti.UI.createTableView({
        headerTitle: 'TableView',
        data: [
            {
                title: 'Apples',
                hasChild: true
            }, {
                title: 'Bananas'
            }
        ],
        height: Ti.UI.SIZE
    }),
    ls = Ti.UI.createListSection({
        headerTitle: 'ListView'
    }),
    lv = Ti.UI.createListView({
        height: Ti.UI.SIZE
    });

ls.setItems([
    {
        properties: {
            title: 'Apples',
            accessoryType: Ti.UI.LIST_ACCESSORY_TYPE_CHECKMARK
        }
    }, {
        properties: {
           title: 'Bananas',
           accessoryType: Ti.UI.LIST_ACCESSORY_TYPE_DETAIL
       }
    }
]);
lv.sections = [ls];

win.add(tv);
win.add(lv);
win.open();
```
###### TEST CASE #2
```JS
var win = Ti.UI.createWindow({
        backgroundColor: 'white',
        layout: 'vertical'
    }),
    tableData = [{
        title: 'Apples',
        color: 'black'
    }, {
        title: 'Bananas',
        color: 'black'
    }, {
        title: 'Carrots',
        color: 'black'
    }, {
        title: 'Potatoes',
        color: 'black'
    }],
    table = Ti.UI.createTableView({
        minRowHeight: 50,
        data: tableData,
        width: Ti.UI.FILL,
        height: Ti.UI.SIZE
    });
table.addEventListener('click', function(e) {
    alert('index: ' + e.index);
});
win.add(table);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24822)

2017-06-20 23:14 UTC, jquick-axway requested changes

2017-06-20 23:14 UTC, jquick-axway commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/tableview/TiTableView.java
> +					if (models.contains(v.getRowData())) {
You should check if "models" is null before using it.
It can be null if TableViewModel.release() gets called.

The rest looks fine. 👍

2017-06-26 16:39 UTC, jquick-axway approved these changes
CR: Pass

2017-06-26 23:29 UTC, ssjsamir commented
FR Passed - 1st Test case no longer crashed and 2nd test case returned the correct index positions.

**Test Steps**
+ Downloaded the SDK Build form this PR
+ Created a new Titanium project
+ Copied the 1st test case from description
+ Ran the application 
+ Saw the TableView and application did not crash
+ Copied the 2nd test case from description
+ Clicked on each item
+ Correct index was returned 

**Test Environment**
Appcelerator Command-Line Interface, version 6.2.2
Google Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705251638

2017-06-26 23:29 UTC, merged