[TIMOB-18914] Android: Mark splitActionBar as removed
appcelerator/titanium_mobile pull request #9156
Opened 2017-06-19 15:11 UTC by ypbnv

Remove from source. Mark in documentation as "removed".

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-18914

2017-06-20 11:18 UTC, ypbnv commented
@hansemannn Reverted the code removal. Added only deprecation tag and some notes. I guess we can link the Ti.UI.Toolbar in the notes once we have it moved on both platforms in the proper module.

2017-08-09 22:52 UTC, lokeshchdhry commented
@ypbnv , can QE do a FR for this ? Is CR pending ?

2017-08-10 07:34 UTC, hansemannn requested changes

2017-08-10 07:34 UTC, hansemannn commented on apidoc/Titanium/UI/Window.yml
> +        notes: Deprecated in AppCompat theme. The same behaviour can be achived by using Toolbar.
So it still work? When you deprecate it, it still has to work. In case it does not anymore, it has to go into a major version (7.0.0).

2017-08-15 12:03 UTC, ypbnv commented on apidoc/Titanium/UI/Window.yml
> +        notes: Deprecated in AppCompat theme. The same behaviour can be achived by using Toolbar.
Yes, it should work. On Titanium SDK less than 4.0.0. Material Theme was added in that version and it does not support this property.

2017-08-17 10:42 UTC, garymathews approved these changes
CR: **PASS**

@ypbnv needs backporting to 6_2_X

2017-08-28 21:26 UTC, mukherjee2 commented
Passes FR.

2017-08-28 21:26 UTC, merged