[TIMOB-24911] Android: Change regular expression to handle platform specific paths.
appcelerator/titanium_mobile pull request #9183
Opened 2017-06-30 11:31 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24911

**Optional Description:**
Regular expression does not match files' path with backslashes, so they are included in the .jar and duplicated.

2017-06-30 16:24 UTC, janvennemann requested changes

2017-06-30 16:24 UTC, janvennemann commented on android/cli/commands/_buildModule.js
> +			var excludeRegex = new RegExp('.*\\' + path.sep + 'R\\\.class$|.*\\' + path.sep + 'R\\\$(.*)\\\.class$', 'i');
The three backslashes as escape characters are unnecessary here, for example `R\\.class$` already results in in the correct regex `R\.class$`

2017-07-03 08:30 UTC, ypbnv commented
@janvennemann Updated.

2017-07-03 16:00 UTC, cb1kenobi approved these changes
CR LGTM.

2017-07-03 17:33 UTC, janvennemann approved these changes

2017-08-31 13:20 UTC, merged

2017-08-31 13:20 UTC, garymathews commented
Merged for parity with `6_1_X` and `6_2_X`