[TIMOB-24912] Android: Running a module after it was built fails on Windows.
appcelerator/titanium_mobile pull request #9184
Opened 2017-06-30 11:59 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24912

Change parameters to work both on OS and Windows.

**Description:**
On Windows Node child processes need to be run in a new console. This changes the command to point to the node executable and adds the old command as a parameter. This way it should work on both operating systems.

2017-07-05 16:05 UTC, cb1kenobi approved these changes
CR'd and FR'd. **APPROVED**

2017-07-05 16:12 UTC, cb1kenobi commented on android/cli/commands/_buildModule.js
> +        // when calling on Windows, we need to escape ampersands in the command
Please fix the indention here. We use tabs, not spaces.

2017-07-05 16:12 UTC, cb1kenobi requested changes
Needs some coding style fixes.

2017-07-06 12:38 UTC, ypbnv commented
@cb1kenobi Updated with proper indentation.

2017-07-06 13:55 UTC, cb1kenobi requested changes

2017-07-06 13:55 UTC, cb1kenobi commented on android/cli/commands/_buildModule.js
> +	function runTiCommand(cmd, args, logger, callback) {
Sorry to knit pick, but you have trailing whitespace.

2017-07-06 14:00 UTC, ypbnv commented on android/cli/commands/_buildModule.js
> +	function runTiCommand(cmd, args, logger, callback) {
I have totally missed that.

2017-07-06 14:00 UTC, ypbnv commented
@cb1kenobi Updated.

2017-07-06 14:02 UTC, cb1kenobi approved these changes
Good to go. **APPROVED**!

2017-07-06 14:02 UTC, merged