Install command patch for Windows platform.
appcelerator/titanium_mobile pull request #9198
Opened 2017-07-06 13:31 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24943

**Description:**
Installing a built from sources SDK fails on Windows. 

Here I am not sure if stripping the 'unizp' command would work fine on OS X.

2017-07-06 14:12 UTC, cb1kenobi requested changes

2017-07-06 14:12 UTC, cb1kenobi commented on build/scons-install.js
> +	exec('unzip -q -o -d "' + dest + '" "' + zipfile + '"', function (err, stdout, stderr) {
`unzip` is not a valid command on Windows. You should use the unzip function in `node-appc`. To do this, first require `node-appc`:

```js
var appc = require('node-appc');
```

Then unzip!

```js
appc.zip.unzip(zipfile, dest, next);
```

2017-07-06 14:52 UTC, ypbnv commented
@cb1kenobi Updated.

2017-07-06 15:32 UTC, cb1kenobi approved these changes
Seems to work as advertised. **APPROVED**.

2017-07-06 15:32 UTC, merged

2017-07-25 09:12 UTC, ypbnv commented
@jquick-axway Checked it - 'cleanbuild' on Windows does have the same problem. Since this PR introduces an issue - should I apply the changes from it for 'cleanbuild'?

2017-07-25 16:42 UTC, jquick-axway commented
@ypbnv, I would say go for it.

And go ahead and implement the work-around I've implemented in my PR #9244. Chris has approved it over e-mail. I'm okay with closing my PR if you implement it in this one.

2017-07-26 13:00 UTC, ypbnv commented
@jquick-axway Here is a combined PR: https://github.com/appcelerator/titanium_mobile/pull/9259