[TIMOB-17493] Android: Default Translucent theme overwrites custom themes.
appcelerator/titanium_mobile pull request #9216
Opened 2017-07-11 14:14 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-17493

**Description:**
The default Translucent theme used for activities with opacity property, modal property and incorrect background color format, overwrites any custom theme's values. 

**Test case:**
Custom theme and case provided in the ticket.

2017-07-11 17:51 UTC, garymathews commented on android/cli/commands/_build.js
> +		var defaultProvidedTheme = '@style/' + flags;
You shouldn't need to change anything in this file

2017-07-11 17:52 UTC, garymathews commented on android/templates/build/theme.xml
> +	<style name="Theme.AppCompat.Translucent.Default" parent="<%- defaultProvidedTheme %>">
Why not remove

```XML
<item name="android:actionBarStyle">@style/Base.Widget.AppCompat.ActionBar.Solid</item>
<item name="actionBarStyle">@style/Base.Widget.AppCompat.ActionBar.Solid</item>
```

from `Theme.AppCompat.Translucent` ?

2017-07-11 17:52 UTC, garymathews requested changes
CR: **SEE COMMENTS**

2017-08-25 08:26 UTC, closed without merging

2017-08-25 08:27 UTC, ypbnv commented
Closed due to being out of sync with latest build and themes changes. Will reopen once I get it back on track or I will create a new one for the issue (if it is still relevant).