[AC-5098] Android: Add Ti.Network.Cookie isValid()
appcelerator/titanium_mobile pull request #9230
Opened 2017-07-20 17:06 UTC by m1ga

**JIRA:** https://jira.appcelerator.org/browse/AC-5098

Parity with iOS

Test code
```
var cookie1 = Ti.Network.createCookie({
	domain: 'example.com',
	name: 'test_cookie',
	value: '12',
	path: '/'
});

var cookie2 = Ti.Network.createCookie({
	name: 'test_cookie',
	value: '12',
	path: '/'
});

console.log("is cookie valid: "+ cookie1.isValid());
console.log("is cookie valid: "+ cookie2.isValid());

```

2017-07-24 12:32 UTC, garymathews requested changes

2017-07-24 12:32 UTC, garymathews commented on android/modules/network/src/java/ti/modules/titanium/network/CookieProxy.java
> +		String name = TiConvert.toString(getProperty(TiC.PROPERTY_NAME), "");
No need to set a default value in this case:
```Java
String name = TiConvert.toString(getProperty(TiC.PROPERTY_NAME));
String value = TiConvert.toString(getProperty(TiC.PROPERTY_VALUE));
String path = TiConvert.toString(getProperty(TiC.PROPERTY_PATH));
String domain = TiConvert.toString(getProperty(TiC.PROPERTY_DOMAIN));
return (name != null && value != null && path != null && domain != null);
```

2017-07-25 16:58 UTC, garymathews reviewed
CR: **PASS**

2017-07-25 16:59 UTC, garymathews approved these changes
CR: **PASS**

2017-07-25 18:31 UTC, hansemannn commented
@m1ga Can you provide a 6_2_X PR as well? Currently this would only go into 7.0.0

2017-07-25 21:23 UTC, lokeshchdhry commented
FR Passed.

`isValid()` works as expected.

Studio Ver:     4.9.1.201707200100
SDK Ver:        7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.2
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        Android 6.0

2017-08-15 22:50 UTC, merged