[AC-5089] Android: requestThumbnailImagesAtTimes causes a crash
appcelerator/titanium_mobile pull request #9245
Opened 2017-07-25 14:42 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/AC-5089

**Description:**
Passing a URI with 'file' scheme causes the ContentResolver's cursor to throw an error.

Handle file resources URI manually.
Change setDataSource method to work with all resource types.

2017-07-25 19:00 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiThumbnailRetriever.java
> +							mMediaMetadataRetriever.setDataSource(TiApplication.getAppRootOrCurrentActivity(),mUri);
formatting, space after `,`

2017-07-26 09:08 UTC, ypbnv commented
@garymathews Fixed formatting. Removed some unused imports.

2017-07-27 09:03 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/VideoPlayerProxy.java
> +			if (url.contains("file://")) {
```Java
url.startsWith("file://")
```

2017-07-27 09:04 UTC, garymathews requested changes
See above

2017-07-27 10:33 UTC, ypbnv commented
@garymathews Updated.

2017-08-03 09:33 UTC, garymathews approved these changes
CR: **PASS**

2017-08-22 21:17 UTC, ssjsamir approved these changes
FR Passed: When using `requestThumbnailImagesAtTimes` application no longer crashes. 


**Test Steps**
+ Downloaded the SDK Build from this PR
+ Created a new Titanium project
+ Used the following test case:
```
var win = Ti.UI.createWindow({
		title: 'test',
		backgroundColor: 'white',
		layout: 'vertical'
});
	
var button = Ti.UI.createButton({
    title: "record"
});
 
button.addEventListener('click', recordVideo);
 
win.add(button);
win.open();
 
function recordVideo() {
    var permissionsToRequest = [];
 
   
 
    var cameraPermission = "android.permission.CAMERA";
    var hasCameraPerm = Ti.Android.hasPermission(cameraPermission);
    if (!hasCameraPerm) {
        permissionsToRequest.push(cameraPermission);
    }
 
    var storagePermission = "android.permission.READ_EXTERNAL_STORAGE";
    var hasStoragePerm = Ti.Android.hasPermission(storagePermission);
    if (!hasStoragePerm) {
        permissionsToRequest.push(storagePermission);
    }
    if(permissionsToRequest.length > 0) {
        Ti.Android.requestPermissions(permissionsToRequest, function (e) {
            if (e.success) {
                showCamera();
            }
        });
    } else {
        showCamera();
    }
}
 
function showCamera() {
    Ti.Media.showCamera({
        autohide: false,
        animated: false,
        allowEditing: false,
        success:function(event) {
            var movie = Titanium.Media.createVideoPlayer({
                url:event.media.nativePath,
                backgroundColor:'#111',
                mediaControlStyle: Titanium.Media.VIDEO_CONTROL_EMBEDDED,
                scalingMode:Titanium.Media.VIDEO_SCALING_ASPECT_FILL,
                width:300,
                height:300,
            });
            win.add(movie);
 
            movie.addEventListener('durationavailable', function() {
                movie.requestThumbnailImagesAtTimes([1], Titanium.Media.VIDEO_TIME_OPTION_NEAREST_KEYFRAME, function(response) {
                    Ti.API.info("Thumbnail callback called, success = " + response.success);
                    console.log(response);
                    if(response.success) {
 
                    }
                });
            });
        },
        cancel:function() {
            console.log("cancel");
        },
        error:function(error) {
            console.log("error");
            console.log(error);
        },
        mediaTypes: [Ti.Media.MEDIA_TYPE_VIDEO],
    });
}
```
+ Ran the application
+ Pressed record
+ Recorded a short video
+ Pressed okay
+ Was able to see the thumbnail from the previous menu 

**Test Environment**
Appcelerator Command-Line Interface, version 6.2.3
Google Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705302345

2017-08-22 21:18 UTC, merged