[TIMOB-25024] iOS: Remove <iphone> from tiapp.xml
appcelerator/titanium_mobile pull request #9257
Opened 2017-07-26 10:51 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25024

2017-07-26 13:01 UTC, cb1kenobi requested changes

2017-07-26 13:01 UTC, cb1kenobi commented on iphone/cli/commands/_build.js
> +		this.logger.log(('           <dict>').grey);
Why do we need the inner parenthesis?

2017-07-26 13:01 UTC, cb1kenobi commented on iphone/cli/commands/_build.js
> +		iphone = this.tiapp.iphone, // deprected in 2.1.0, removed in 7.0.0
Since `iphone` is only used on like 3937 in the `if`, we could save a local variable and just do `if (this.tiapp.iphone) {`.

2017-07-26 14:04 UTC, hansemannn commented on iphone/cli/commands/_build.js
> +		iphone = this.tiapp.iphone, // deprected in 2.1.0, removed in 7.0.0
Yessir!

2017-07-26 14:05 UTC, hansemannn commented on iphone/cli/commands/_build.js
> +		this.logger.log(('           <dict>').grey);
Copy and pasted from the other tiapp-example, will remove :-)

2017-07-26 14:07 UTC, hansemannn commented
@cb1kenobi Addressed

2017-07-26 15:29 UTC, cb1kenobi approved these changes
Works like a champ. **APPROVED**!

2017-08-01 17:03 UTC, ssjsamir approved these changes
**FR Passed:** Application will now throw an error if the <iphone> tag is used. 

**Test Steps**
+ Created a version of the SDK using this PR
+ Created a Titanium project 
+ Added the following in to the `tiapp.xml`
```
<iphone>
<what>ever</what>
</iphone>
```
+ Ran the Titanium application 
+ Saw the following error in the console
```
[ERROR] :  The <iphone> section of the tiapp.xml has been removed in Titanium SDK 7.0.0 and later.
Please use the <ios> section of the tiapp.xml to specify iOS-specific values instead:
<ti:app xmlns:ti="http://ti.appcelerator.org">
    <ios>
        <plist>
            <dict>
                <!-- Enter your Info.plist keys here -->
            </dict>
        </plist>
    </ios>
</ti:app>
```
**Test Environment** 
Iphone 6S(iOS 10.0)
Appcelerator Command-Line Interface, version 6.2.3-21
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705302345

2017-08-01 17:04 UTC, merged