[6_2_X][TIMOB-1028] Android: Implement AudioRecorder (Parity)
appcelerator/titanium_mobile pull request #9268
Opened 2017-08-01 08:45 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-1028

**Description:**
Cherry pick of: https://github.com/appcelerator/titanium_mobile/pull/9067

2017-08-01 13:44 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/AudioRecorderProxy.java
> +		return new TiFileProxy(TiFileFactory.createTitaniumFile(tiAudioRecorder.stopRecording(),false));
space after `,`

2017-08-01 13:44 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/MediaModule.java
> +		return TiApplication.getInstance().getPackageManager().hasSystemFeature( "android.hardware.microphone");
remove whitespace after `(`

2017-08-01 13:45 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +		bufferSize = AudioRecord.getMinBufferSize(RECORDER_SAMPLE_RATE,RECORDER_CHANNELS,RECORDER_AUDIO_ENCODING);
space after `,`

2017-08-01 13:45 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +			tempFileReference =  TiFileHelper.getInstance().getTempFile(AUDIO_RECORDER_TEMP_FILE,true);
space after `,`

2017-08-01 13:45 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +		audioRecord = new AudioRecord(MediaRecorder.AudioSource.MIC,RECORDER_SAMPLE_RATE, RECORDER_CHANNELS,RECORDER_AUDIO_ENCODING, bufferSize*4);
space after `,`

2017-08-01 13:45 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +				resultFile = TiFileHelper.getInstance().getTempFile(AUDIO_RECORDER_FILE_EXT_WAV,true);
space after `,`

2017-08-01 13:46 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +		return resultFile != null ? resultFile.getAbsolutePath():"";
space before and after `:`

2017-08-01 13:46 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +			audioRecord.read(audioData,0,bufferSize);
space after `,`

2017-08-01 13:46 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +			writeWaveFileHeader(out, totalAudioLen, totalDataLen,RECORDER_SAMPLE_RATE, channels, byteRate);
space after `,`

2017-08-01 13:49 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +		header[0] = 'R'; // RIFF/WAVE header
could use an array?

```Java
byte[] header = {
    'R', 'I', 'F'
    ...
};
```

2017-08-01 13:50 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +		out.write(header, 0, 44);
```Java
44 -> header.length
```

2017-08-01 13:51 UTC, garymathews commented on android/modules/media/src/java/ti/modules/titanium/media/TiAudioRecorder.java
> +				audioRecord.read(audioData,0,bufferSize);
space after `,`

2017-08-01 13:51 UTC, garymathews requested changes
See above; these changes should also be pushed to `master`.

2017-08-01 18:43 UTC, lokeshchdhry commented
FR Passed.

With proper permissions, the audio recorder's record, pause, play, stop works as expected.

1. Checked by recording audio, stopping & playing it.
2. Recording audio, pausing , recording again , stopping & playing.

Studio Ver:     4.9.1.201707200100
SDK Ver:        6.2.0.v20170801014621
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.3-21
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.13
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1

2017-08-01 18:45 UTC, lokeshchdhry commented
Will merge when the requested changes are done.

2017-08-02 08:50 UTC, ypbnv commented
@garymathews Updated.

2017-08-02 10:45 UTC, garymathews approved these changes
CR: **PASS**

2017-08-02 18:10 UTC, merged