[TIMOB-20404]: iOS ProgressBar gets clipped in parent with height Ti.UI.SIZE
appcelerator/titanium_mobile pull request #9273
Opened 2017-08-03 06:16 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-20404

2017-08-07 21:35 UTC, hansemannn requested changes

2017-08-07 21:35 UTC, hansemannn commented on iphone/Classes/TiUIProgressBar.m
> +	return fontSize.height + progressSize.height + 5;
Indentation is incorrect. I also feel like this is not the proper way to fix it (by manually setting a constant value of 5 just to unclip it). I need to spend more time reviewing the progress-bar layout-code this week.

2017-08-08 01:51 UTC, vijaysingh-axway commented on iphone/Classes/TiUIProgressBar.m
> +	return fontSize.height + progressSize.height + 5;
@hansemannn,  If you see function -(void)layoutSubviews in same file, there is code snippet -
	float fittingHeight = barSize.height + messageSize.height + 5;

which sets the gap of 5 pixel between message and progress bar. So while calculating height it should also give +5 pixel, if message is there.

2017-08-10 06:40 UTC, hansemannn approved these changes
LGTM! 🚀

2017-10-10 03:51 UTC, build commented
<!--
  0 failure: 
  1 warning:  :microscope: Ther...
  
  
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2017-11-07 21:56 UTC, merged