[TIMOB-24503] Android: Implement notification quick actions
appcelerator/titanium_mobile pull request #9278
Opened 2017-08-04 15:08 UTC by garymathews

###### Requires support library `26.0.0` https://github.com/appcelerator/titanium_mobile/pull/9274

- Implement notification quick actions
- Expose support library `26.0.0` feature `setGroupAlertBehavior()`

###### TEST CASE
```JS
var win = Ti.UI.createWindow({title: 'TIMOB-24503', layout: 'vertical'}),
    btn = Ti.UI.createButton({title: 'CREATE NOTIFICATION', height: 50, width: Ti.UI.FILL}),
    id = 100;

function createNotification() {
        var n = Ti.Android.createNotification({
                icon: Ti.Android.R.drawable.ic_dialog_info,
                contentTitle: 'APPCELERATOR',
                contentText : 'Open Appcelerator web-page.'
            }),
            p = Ti.Android.createPendingIntent({
                intent: Ti.Android.createIntent({
                    action: Ti.Android.ACTION_VIEW,
                    data: 'https://www.appcelerator.com'
                })
            });
        n.addAction(Ti.Android.R.drawable.ic_dialog_email, "OPEN", p);
        Ti.Android.NotificationManager.notify(id, n);
}

btn.addEventListener('click', function() {
    createNotification();
});

win.add([btn]);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24503)

2017-08-04 22:26 UTC, jquick-axway requested changes

2017-08-04 22:26 UTC, jquick-axway commented on apidoc/Titanium/Android/Notification.yml
> +        type: [Number, String]
I think the icons have to use a holo dark theme on Android 4.x and a light material theme on Android 5.0 and above. Which means developers need to provide versioned drawable resources (ie: "drawable-mdpi-v21" for material). Or perhaps those details should go into the notification guide?

2017-08-04 22:26 UTC, jquick-axway commented on android/modules/android/src/java/ti/modules/titanium/android/notificationmanager/NotificationProxy.java
> +		notificationBuilder.addAction(iconId, title, pendingIntent.getPendingIntent());
Perhaps we should do the following if title is null. (I'm thinking icon-only action buttons.)
```java
if (title == null) {
    title = "";
}
```

2017-08-04 22:26 UTC, jquick-axway commented on android/modules/android/src/java/ti/modules/titanium/android/notificationmanager/NotificationProxy.java
> +		notificationBuilder.addAction(iconId, title, pendingIntent.getPendingIntent());
And if "pendingIntent" is null, we should log an error or throw an exception indicating that this argument cannot be null.

2017-08-08 14:59 UTC, garymathews commented
@jquick-axway Updated PR, `title` can be `null` for icon only buttons

2017-08-08 18:25 UTC, jquick-axway approved these changes
CR: Pass

2017-08-21 18:47 UTC, lokeshchdhry commented
FR Passed.

1. Checked with code above.
2. Checked with `data: 'http://maps.google.com/maps?q=loc:37.3906238,-122.0499305,19'` which opens up the maps app.
3. Checked with :
```
intent : Ti.Android.createIntent({
	action: Ti.Android.ACTION_VIEW,
	className: 'com.app.zxyz.ZxyzActivity',
	packageName: 'com.app.zxyx
})
```
4. Checked with `null` argument's for `title` & pending intent`.

Studio Ver:     4.9.1.201707200100
SDK Ver:       7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.3
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.13
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Pixel --- Android 7.1.1

2017-08-21 18:48 UTC, merged