[TIMOB-25045] Android: Implement Ti.Android.NotificationChannel
appcelerator/titanium_mobile pull request #9305
Opened 2017-08-11 14:44 UTC by garymathews

- Implement `Titanium.Android.NotificationChannel`

###### TEST CASE
```JS
var win = Ti.UI.createWindow({title: 'TIMOB-250045', layout: 'vertical'}),
    btn = Ti.UI.createButton({title: 'CREATE NOTIFICATION', height: 50, width: Ti.UI.FILL}),
    id = 100,
    channel = Ti.Android.NotificationManager.createNotificationChannel({
        id: 'my_channel',
        name: 'TEST CHANNEL',
        importance: Ti.Android.IMPORTANCE_DEFAULT
    });

btn.addEventListener('click', function() {
    var n = Ti.Android.createNotification({
            icon: Ti.Android.R.drawable.ic_dialog_info,
            contentTitle: 'TITLE',
            contentText : 'This is a test',
            channelId: channel.getId()
        });
    Ti.Android.NotificationManager.notify(id, n);
});

win.add([btn]);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25045)

2017-08-11 15:27 UTC, hansemannn requested changes
Few docs-questions!

2017-08-11 15:27 UTC, hansemannn commented on apidoc/Titanium/Android/Android.yml
> +
`since: "7.0.0"` for all of these? Or is it scheduled for 6.2.0?

2017-08-11 15:27 UTC, hansemannn commented on apidoc/Titanium/Android/NotificationChannel.yml
> +    type: Array
Array of what?

2017-08-11 15:27 UTC, hansemannn commented on apidoc/Titanium/Android/NotificationManager/NotificationManager.yml
> +    parameters:
Does not need multi-line-wrapping, but it's no big deal.

2017-08-22 08:34 UTC, hansemannn commented
@garymathews Jenkins is failing because of docs-issues:
```
[ERROR] ./Titanium/Android/NotificationChannel.yml
Titanium.Android.NotificationChannel: found 2 error(s)!
	Required property "summary" not found
	properties
		id
			Invalid array element: creation-only; possible values: read-only,write-only,read-write

[ERROR] ./Titanium/Android/NotificationManager/NotificationManager.yml
Titanium.Android.NotificationManager: found 1 error(s)!
	methods
		createNotificationChannel
			Required property "summary" not found

```

2017-08-25 22:44 UTC, jquick-axway requested changes

2017-08-25 22:44 UTC, jquick-axway commented on android/titanium/src/java/org/appcelerator/titanium/TiC.java
> +	public static final String PROPERTY_ENABLE_VIBRATION = "enableVibrations";
The property string is set to "enableVibrations" with an 's', but you document this property without an 's'. This is a typo, right?

2017-08-25 22:44 UTC, jquick-axway commented on apidoc/Titanium/Android/NotificationChannel.yml
> +    summary: user visible description of this channel.
Capitalize "user" in sentence.

2017-08-25 22:44 UTC, jquick-axway commented on apidoc/Titanium/Android/NotificationChannel.yml
> +    summary: The vibration pattern for notifications posted to this channel.
We should document how this array of numbers work. I believe each array element is a duration in milliseconds, right? Where the even indexed elements (ex: 0, 2, 4, 6, etc.) is the vibration time and the odd indexed elements are how long to wait between vibrations.

2017-08-25 22:44 UTC, jquick-axway commented on apidoc/Titanium/Android/NotificationChannel.yml
> +    type: Number
We should define constants for the "lockscreenVisibility" property: 
VISIBILITY_PRIVATE = 0
VISIBILITY_PUBLIC = 1
VISIBILITY_SECRET = -1

2017-08-25 22:44 UTC, jquick-axway commented on apidoc/Titanium/Android/NotificationChannel.yml
> +    type: Number
Or at least document what numbers are supported.

2017-08-25 22:44 UTC, jquick-axway commented on apidoc/Titanium/Android/NotificationChannel.yml
> +    summary: The channel id specified for the notification channel.
Indicate that this is a unique string ID defined by the Titanium developer.

2017-08-25 22:44 UTC, jquick-axway commented on apidoc/Titanium/Android/NotificationManager/NotificationManager.yml
> +        summary: Properties to set on a new object, including any defined by <Titanium.Android.NotificationChannel> except those marked not-creation or read-only.
Document that this function will return null on Android OS version older than Android 8.

2017-09-22 17:32 UTC, garymathews commented
@jquick-axway Updated PR

2017-09-22 17:55 UTC, build commented
<!--
  1 failure:  Tests have failed...
  1 warning:  :microscope: Ther...
  
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code
  </td>
    </tr>
  </tbody>
</table>


### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.Label | border (without width/height) | 3.093 | Failed at line , column  |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2017-09-22 21:08 UTC, jquick-axway approved these changes
CR: Pass

2017-11-15 21:52 UTC, lokeshchdhry commented
FR Passed.

Notification channel works as expected along with its properties.
If ran on below android 8.0 it will throw runtime error which is expected :
```
[ERROR] :  [Nexus 5] TiExceptionHandler: (main) [107728,120517] ----- Titanium Javascript Runtime Error -----
[ERROR] :  [Nexus 5] TiExceptionHandler: (main) [0,120517] - In /app.js:15,32
[ERROR] :  [Nexus 5] TiExceptionHandler: (main) [0,120517] - Message: Uncaught TypeError: Cannot read property 'getId' of null
[ERROR] :  [Nexus 5] TiExceptionHandler: (main) [1,120518] - Source:             channelId: channel.getId()
[ERROR] :  [Nexus 5] V8Exception: Exception occurred at /app.js:15: Uncaught TypeError: Cannot read property 'getId' of null
```
Studio Ver:     4.10.0.201709271713
SDK Ver:        7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.10
Appc CLI:       6.3.0
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.7
Node Ver:       7.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Pixel XL --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1

2017-11-15 23:31 UTC, merged