[TIMOB-25161] (6_2_X) iOS: Add thin, light, ultra-light & semi-bold font-sizes
appcelerator/titanium_mobile pull request #9309
Opened 2017-08-13 19:21 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25161

2017-08-15 04:15 UTC, vijaysingh-axway requested changes

2017-08-15 04:15 UTC, vijaysingh-axway commented on iphone/Classes/WebFont.m
> +                        font = [[UIFont italicSystemFontOfSize:self.size] retain];
Why put this api inside block of iOS 8.2 and greater ?

2017-08-15 04:15 UTC, vijaysingh-axway commented on iphone/Classes/WebFont.m
> +    	self.isSemiboldWeight = YES;
fix indentation .

2017-08-15 10:34 UTC, hansemannn commented
@vijaysingh-axway Addressed comments!

2017-08-16 08:49 UTC, vijaysingh-axway approved these changes
CR passed.

2017-08-16 15:16 UTC, ewieberappc approved these changes
FR Passed.
New font weights are available and usable without issue.

2017-08-16 15:16 UTC, merged