[TIMOB-25029] Removed generation of legacy launch images for iOS 6.
appcelerator/titanium_mobile pull request #9314
Opened 2017-08-14 16:26 UTC by cb1kenobi

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25029

2017-08-14 17:00 UTC, hansemannn requested changes

2017-08-14 17:00 UTC, hansemannn commented on iphone/cli/commands/_build.js
> -					'Default-Landscape-736h@3x.png': { idiom: 'iphone', extent: 'full-screen', minSysVer: '8.0', orientation: 'landscape', width: 2208, height: 1242, scale: 3, subtype: '736h' },
These ones are for iOS 8/9 and are used on the iPhone 6 / iPhone 6S / iPhone 7. Did you test the changes? I highly doubt these are the correct ones to remove.

2017-08-15 15:44 UTC, cb1kenobi commented on iphone/cli/commands/_build.js
> -					'Default-Landscape-736h@3x.png': { idiom: 'iphone', extent: 'full-screen', minSysVer: '8.0', orientation: 'landscape', width: 2208, height: 1242, scale: 3, subtype: '736h' },
Yes, I tested it. I know. Doesn't make sense, but those 3 are the culprit.

2017-08-15 15:54 UTC, hansemannn commented on iphone/cli/commands/_build.js
> -					'Default-Landscape-736h@3x.png': { idiom: 'iphone', extent: 'full-screen', minSysVer: '8.0', orientation: 'landscape', width: 2208, height: 1242, scale: 3, subtype: '736h' },
Has to be an Xcode issue then. Those are the most recent launch-screens introduced by Apple, all newer devices would not have a proper launch-screen and scale-up the other ones. Need to dive more into this.

2017-10-11 13:26 UTC, hansemannn commented
PR **rejected**, it removes required launch-images for the iPhone 6 / 7 and iPhone 6 Plus / 7 Plus. The initial warning from the linked ticket has to be an Xcode false-positive and will be tracked with Apple.

2017-10-11 13:26 UTC, closed without merging