[TIMOB-19154]: iOS9 Deprecate NSURLConnection and replace with NSURLSession API
appcelerator/titanium_mobile pull request #9366
Opened 2017-08-29 06:47 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-19154

2017-10-31 04:10 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/vijaysingh-axway/titanium_mobile/blob/TIMOB-19154/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2017-11-22 21:06 UTC, sgtcoolguy commented
@hansemannn This now has a conflict due to the PR #9619 - not sure if that means some of this fix has already been "snuck in"? This ticket was marked 7.0.0...

2017-11-22 21:07 UTC, sgtcoolguy commented
The APS PR: appcelerator/APSHTTPClient#40

2017-11-22 21:08 UTC, sgtcoolguy commented
appcelerator.https module PR: appcelerator-modules/appcelerator.https#46

2017-11-23 06:26 UTC, hansemannn commented
@sgtcoolguy We decided to move it out of 7.0.0 due to other fixes being prioritized. The merge-conflict comes from #9612, so I just need to rebase using that revision.

2017-12-14 17:51 UTC, sgtcoolguy commented
@hansemannn ping again 😄

2017-12-15 09:03 UTC, hansemannn commented
@sgtcoolguy I talked to Vijay last week. It needs passing unit-tests before going further in the review.

2017-12-15 09:13 UTC, hansemannn requested changes

2017-12-15 09:13 UTC, hansemannn commented on iphone/Classes/APSHTTPClient/APSHTTPRequest.h
>  -(BOOL)willHandleChallenge:(NSURLAuthenticationChallenge *)challenge forConnection:(NSURLConnection *)connection;
This should not be required anymore. Also delegates like `NSURLConnectionDelegate` should be replaced. Please make sure to test all `Ti.Network.HTTPClient` API's in your unit-tests and ensure the old ones work without adjustments.

2017-12-27 06:00 UTC, vijaysingh-axway commented
Test Case -
`var win = Ti.UI.createWindow({
                             title : 'HTTPClient Test - TIMOB-19154',
                             backgroundColor: 'black'
                             });
var textColor = 'black';
var plainTemplate = {
childTemplates: [
                 {
                 type: 'Ti.UI.Label', // Use a label
                 bindId: 'rowtitle',  // Bind ID for this label
                 properties: {        // Sets the Label.left property
                 left: '10dp',
                 color: textColor
                 }
                 },
                 {
                 type: 'Ti.UI.Label',   // Use an image view
                 bindId: 'statusLabel', // Bind ID for this label
                 id: 'statusLabel',
                 properties: {          // Sets the label property
                 title: 'Status: ',
                 color: textColor
                 }
                 },
                 {
                 type: 'Ti.UI.Button',   // Use a button
                 bindId: 'button',       // Bind ID for this button
                 properties: {           // Sets several button properties
                 width: '80dp',
                 right: '10dp',
                 title: 'Press'
                 },
                 events: { click : report }  // Binds a callback to the button's click event
                 }
                 ]
};

function report(e) {
  Ti.API.info(e.type);
  Ti.API.info(e.itemIndex);
  testFunction(e);
}

var listView = Ti.UI.createListView({
                                    // Maps the plainTemplate object to the 'plain' style name
                                    templates: { 'plain': plainTemplate },
                                    // Use the plain template, that is, the plainTemplate object defined earlier
                                    // for all data list items in this list view
                                    defaultItemTemplate: 'plain'
                                    });


var tests = [
             // case 0
             {  name: 'Post - Image to Imgur',
             description: 'Posts an Image to Imgur. Will return a reply with url link of image posted. You can see the progress of the Upload in the logcat/Ti.API.info'
             },
             // case 1
             {
             name: 'Get - Website',
             description: 'Do a simple Get request to Appcelerator website. This will return the website.'
             },
             // case 2. Getting tests from https://github.com/appcelerator/titanium_mobile/blob/17dc8754653daaff170ea0c18f74218168a5633e/support/anvil/configSet/Resources/suites/network_httpclient.js
             {
             name: 'Get - Headers',
             description: 'This test sets 2 headers and clears 1 header. This will do a get request at http://httpbin.org/headers that returns the headers used by the HTTPClient.'
             },
             // case 3
             {
             name: 'Get - Gzip-encoded',
             description: 'Get - Returns gzip-encoded data that is readable. Compare this when you run on a terminal `curl http://httpbin.org/gzip`. The curl will reply human unreadble information.'
             },
             // case 4
             {
             name: 'Get - UTF-8 data',
             description: 'Get - Returns page containing UTF-8 data. The data should be readable.'
             },
             // case 5
             {
             name: 'Get - Redirects',
             description: 'Get - 302 Redirects to the Appcelerator URL. There will be a redirect to Appcelerator website.'
             },
             // case 6
             {
             name: 'Get - No Redirects',
             description: 'HTTPClient autoRedirect is set to false. The link will redirect to Appcelerator website. The HTTPClient will not follow the redirect and hence return null.'
             },
             // case 7
             {
             name: 'Get - 3 Redirects',
             description: 'Get - Follow redirects 3 times. This link will redirect 3 times before going to the Appcelerator website.'
             },
             // case 8
             {
             name: 'Get - XML',
             description: 'Get - Returns XML. This will return an XML document. This will parse the document and show same information from the XML'
             },
             // case 9
             {
             name: 'Get - PNG',
             description: 'Get - Returns PNG. This will download a PNG and show it in an Alert.'
             },
             // case 10
             {
             name: 'No Cert Validation',
             description: 'Get - without Validating TIMOB-19196. HTTPClient is set to not validate certificates. The link is a website with a certificate that is not validated. This will return the website as it is set to non-validating.'
             },
             // case 11
             {
             name: 'Get - Cookies',
             description: 'Get - Check the cookies being sent at http://httpbin.org/cookies'
             },
             // case 12
             {
             name: 'Add a cookie',
             description: 'Add a cookie for http://httpbin.org/cookies to see. Used in the item above.'
             },
             // case 13
             {
             name: 'Remove all Cookies',
             description: 'Remove all Cookies. Used in the item above.'
             },
             // case 14 [TIMOB-17891]
             {
             name: 'TLS v1.2',
             description: 'Get - TLS Version, set to 1.2'
             },
             // case 15 [TIMOB-17891]
             {
             name: 'Default TLS',
             description: 'Get - TLS Version, using Default'
             },
             // case 16
             {
             name: 'Basic Auth Success',
             description: 'This is to test the success of Basic-Auth of the HTTPClient at http://httpbin.org/basic-auth/user/passwd'
             },
             // case 17
             {
             name: 'Basic Auth Failure',
             description: 'This is to test the Basic-Auth of the HTTPClient at http://httpbin.org/basic-auth/user/passwd'
             },
             // case 18
             {
             name: 'Forward Geocoder',
             description: 'Geolocation test forwardGeocoder. Geolocation module Apache HTTPClient has been replaced with HttpURLConnection. This needs to be tested too.'
             },
             // case 19
             {
             name: 'Reverse Geocoder',
             description: 'Geolocation test reverseGeocoder. Geolocation module Apache HTTPClient has been replaced with HttpURLConnection. This needs to be tested too.'
             },
             // case 20
             {
             name: 'Image View',
             description: 'ImageView uses Apache HTTPClient. This has been replaced with HttpURLConnection. Set a URL for ImageView to load an image from.'
             },
             // case 21
             {
             name: 'Save to Gallery',
             description: 'Save an Image from HTTPClient to photo gallery'
             },
             // case 22 https://jira.appcelerator.org/browse/TIMOB-18861
             {
             name: 'SNI TIMOB-18861',
             description: 'Test for SNI. https://jira.appcelerator.org/browse/TIMOB-18861 (DEVOPS-4514)'
             },
             // case 23
             {
             name: 'Get gzipped error',
             description: 'Titanium Android: HTTPClient doesnt decompress gzipped data for error responses. https://jira.appcelerator.org/browse/TIMOB-17612'
             },
             // case 24
             {
             name: 'TIMOB-17585',
             description: 'Crash was happening when getting Headers from HTTPClient. -> Android: HTTPClient: Invalid Status Codes returned in 3.3.0.GA SDK https://jira.appcelerator.org/browse/TIMOB-17585'
             },
             // case 25
             {
             name: 'TIMOB-15380 [...]

2018-01-29 13:05 UTC, hansemannn approved these changes
CR + FT **approved**! See the 30 test-cases in JIRA.

2018-02-22 21:10 UTC, ewieberappc commented
FR Passed. Tested using all of the sample and referenced tickets in the issue ticket as well as the module examples and http test suite

2018-02-23 04:47 UTC, merged