[TIMOB-25241] Android: Do not throw exception on HTTP 400 codes
appcelerator/titanium_mobile pull request #9411
Opened 2017-09-07 15:18 UTC by garymathews

- Prevent an exception being thrown on _400_ response codes

###### TEST CASE
```JS
var request = Ti.Network.createHTTPClient({
	onload: function() {
		console.log('onload: ');
		console.log('readyState: ' + getReadyStateNameFrom(request));
	},
	onerror: function(e) {
		console.log('onerror: ', e);
		console.log('readyState: ' + getReadyStateNameFrom(request));
	}
});
request.open('GET', 'http://www.appcelerator.com/test.js');
request.send();

function getReadyStateNameFrom(httpClient) {
	switch (httpClient.readyState) {
		case httpClient.UNSENT: return 'UNSENT';
		case httpClient.OPENED: return 'OPENED';
		case httpClient.HEADERS_RECEIVED: return 'HEADERS_RECEIVED';
		case httpClient.LOADING: return 'LOADING';
		case httpClient.DONE: return 'DONE';
	}
	return 'UNKNOWN';
}
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25241)

2017-09-07 18:05 UTC, jquick-axway requested changes
@garymathews, HTTP responses having status codes >= 400 are supposed to invoke the onerror() listener. This is how we document it (link below) and how it works on iOS (see iOS log output in JIRA case).
http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Network.HTTPClient-property-onerror

So, we may want to do the following in the Java setReadyState() method...

```java
public void setReadyState(int readyState)
{
	Log.d(TAG, "Setting ready state to " + readyState, Log.DEBUG_MODE);
	this.readyState = readyState;
	KrollDict data = new KrollDict();
	data.put("readyState", Integer.valueOf(readyState));
	dispatchCallback(TiC.PROPERTY_ONREADYSTATECHANGE, data);

	if (readyState == READY_STATE_DONE) {
		KrollDict data1 = new KrollDict();
		if (getStatus() >= 400) {
			if (getStatusText == null) {
				setStatusText("");
			}
			data1.putCodeAndMessage(getStatus(), getStatus() + " : " + getStatusText());
			dispatchCallback(TiC.PROPERTY_ONERROR, data1);
		} else {
			data1.putCodeAndMessage(TiC.ERROR_CODE_NO_ERROR, null);
			dispatchCallback(TiC.PROPERTY_ONLOAD, data1);
		}
	}
}
```

Personally, I would prefer onload to be invoked for HTTP errors responses too (like you're doing it) and only invoke onerror for socket errors, timeouts, and SSL errors... but that's not how it's documented/designed.

2017-09-07 19:19 UTC, jquick-axway approved these changes
CR: Pass

2017-10-09 14:52 UTC, build commented
<!--
  1 failure:  Tests have failed...
  1 warning:  :microscope: Ther...
  
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code
  </td>
    </tr>
  </tbody>
</table>


### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| ios.Titanium.UI.Window | window_navigation | 5.075 | file:///Users/build/Libra |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2017-11-15 01:34 UTC, mukherjee2 approved these changes
Passed FR with this environment:
Node Version: 6.11.5
NPM Version: 3.10.10
Mac OS: 10.13
Appc CLI: 7.0.0-master.8
Appc CLI NPM: 4.2.11-2
Titanium SDK version: 7.0.0 locally built
Appcelerator Studio vers 4.10.0
Android 7.1.2

2017-11-15 04:23 UTC, merged