[TIMOB-24042] iOS / Android: Refactor calendar module
appcelerator/titanium_mobile pull request #9558
Opened 2017-10-26 13:55 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24042

Cherry-picked from #8016.

2017-10-26 14:37 UTC, hansemannn commented on iphone/Classes/TiCalendarRecurrenceRule.m
> +    }
@kopiro Hey Flavio, quick question on this one: What happens if the `EKRecurrenceEnd` has both `occurrenceCount` and `endDate`? Won't the `endDate` get lost with this change? Maybe add an `if`-statement to check for both to retain the old behavior as well, adding the partial constructions as well?

2017-10-26 20:10 UTC, jquick-axway requested changes

2017-10-26 20:10 UTC, jquick-axway commented on apidoc/Titanium/Calendar/Event.yml
> +  - name: rrule
The `rrule` property is not defined in the Android `EventProxy`.

2017-10-26 20:10 UTC, jquick-axway commented on apidoc/Titanium/Calendar/Event.yml
> +  - name: rrule
Also, iOS' `recurrenceRules` property appears to be "RFC 2445" as well. I think we should dump this property and try to make it portable with the existing rules property for portability.

2017-10-26 20:18 UTC, jquick-axway commented
@hansemannn, perhaps we should split this PR into two since the creatCalendar() handling needs more work on the Android side and due to the looming 7.0.0 release date.

We can move the date deprecation handling to a PR for 7.0.0. The rest of the changes are features that we can add later to 7.1.0 (they don't appear to be breaking changes). What do you think?

2017-10-27 15:26 UTC, hansemannn commented
Thanks for the review @jquick-axway, really appreciate it! If you want, we can split it up, although I am unsure how to retain the cherry-picked commits for that case.

2017-10-27 19:04 UTC, kopiro commented
Maybe we have to squash commits :)

2017-10-27 20:15 UTC, jquick-axway commented
@hansemannn, @kopiro, how about we hold on to this PR for 7.1.0. We can make a separate/simpler PR with the deprecations for 7.0.0 and cite the source in code comments.

Oh and I'm only recommending that we split the PR because we're supposed to release 7.0.0 by mid-November and that release date is non-negotiable. We have way to much stuff trying to get added into 7.0.0 at the moment and we want to minimize the risk of bugs/issues.

2017-11-13 17:38 UTC, mukherjee2 commented
@hansemannn is there any resolution on this? Currently it's not passing CR. Is this being moved to 7.1.0?

2017-11-13 18:14 UTC, jquick-axway commented
@mukherjee2, this PR is being pushed out to 7.10.

We created new PR #9589 for 7.0.0 which contains this PR's deprecation warnings.

2018-05-04 19:46 UTC, hansemannn commented
@ypbnv I just rebased the PR with master and had to solve a few critical merge conflicts that overlapped with #9558. Would you mind checking if the Android side is still valid? The major differences were in the content resolvers and properties that are set to the native event (using the cursor). I will continue finishing this PR afterwards. Thank you!

2018-05-04 19:46 UTC, build commented
<!--
  2 failure:  :disappointed_rel..., :microscope: Ther...
  0 warning: 
  1 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/hansemannn/titanium_mobile/blob/TIMOB-24042/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.2.0 test /Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9558-IFK6P7T7BHB2PPWXKKDUXJBPONY5Y5AEE22JUH76UL4KEETZAJNQ
> grunt

Running "appcJs:src:lintOnly" (appcJs) task

Running "eslint:src" (eslint) task

/Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9558-IFK6P7T7BHB2PPWXKKDUXJBPONY5Y5AEE22JUH76UL4KEETZAJNQ/tests/Resources/ti.xml.addontest.js
  17:8  warning  'xml' is assigned a value but never used  no-unused-vars

✖ 1 problem (0 errors, 1 warning)


Running "checkFormat:ios" (checkFormat) task
Fatal error: Error: Formatting incorrect on "iphone/Classes/TiCalendarEvent.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='8376' length='6'>&#10;&#10;  </replacement>
<replacement offset='8538' length='6'>&#10;&#10;  </replacement>
<replacement offset='18297' length='3'>&#10;&#10;</replacement>
<replacement offset='18522' length='6'>&#10;&#10;  </replacement>
<replacement offset='18765' length='6'>&#10;&#10;  </replacement>
<replacement offset='18942' length='6'>&#10;&#10;  </replacement>
<replacement offset='19116' length='6'>&#10;&#10;  </replacement>
<replacement offset='19486' length='6'>&#10;&#10;  </replacement>
<replacement offset='19592' length='10'>&#10;&#10;    </replacement>
<replacement offset='19727' length='14'>&#10;&#10;      </replacement>
<replacement offset='20193' length='10'>&#10;&#10;    </replacement>
<replacement offset='20331' length='10'>&#10;&#10;    </replacement>
<replacement offset='20664' length='18'>&#10;&#10;        </replacement>
<replacement offset='21601' length='18'>&#10;&#10;        </replacement>
<replacement offset='21725' length='10'>&#10;&#10;    </replacement>
<replacement offset='22092' length='10'>&#10;&#10;    </replacement>
<replacement offset='22467' length='10'>&#10;&#10;    </replacement>
<replacement offset='22836' length='10'>&#10;&#10;    </replacement>
<replacement offset='23199' length='10'>&#10;&#10;    </replacement>
<replacement offset='23576' length='10'>&#10;&#10;    </replacement>
<replacement offset='24042' length='6'>&#10;&#10;  </replacement>
<replacement offset='25098' length='6'>&#10;&#10;  </replacement>
</replacements>

Error: Formatting incorrect on "iphone/Classes/TiCalendarCalendar.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='5290' length='6'>&#10;&#10;  </replacement>
</replacements>

npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-09-28 08:29 UTC, build commented
<!--
  2 failure:  :disappointed_rel..., :microscope: Ther...
  0 warning: 
  1 messages
  
  DangerID: danger-id-default;
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/hansemannn/titanium_mobile/blob/TIMOB-24042/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.5.0 test /Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9558-IFK6P7T7BHB2PPWXKKDUXJBPONY5Y5AEE22JUH76UL4KEETZAJNQ
> grunt

Running "appcJs:src:lintOnly" (appcJs) task

Running "eslint:src" (eslint) task

Running "checkFormat:ios" (checkFormat) task

Running "checkFormat:android" (checkFormat) task
Fatal error: Error: Formatting incorrect on "android/modules/calendar/src/java/ti/modules/titanium/calendar/CalendarModule.java", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='6818' length='3'>&#10;	</replacement>
<replacement offset='6921' length='1'>&#10;	</replacement>
<replacement offset='6962' length='1'>&#10;			</replacement>
<replacement offset='7092' length='7'>&#10;&#10;		</replacement>
</replacements>

Error: Formatting incorrect on "android/modules/calendar/src/java/ti/modules/titanium/calendar/CalendarProxy.java", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='1849' length='1'>&#10;	</replacement>
<replacement offset='7495' length='3'>&#10;	</replacement>
<replacement offset='8070' length='1'>&#10;						   </replacement>
<replacement offset='8255' length='1'>&#10;						   </replacement>
<replacement offset='8906' length='3'>&#10;	</replacement>
<replacement offset='9438' length='1'>&#10;			</replacement>
<replacement offset='9530' length='0'> </replacement>
</replacements>

Error: Formatting incorrect on "android/modules/calendar/src/java/ti/modules/titanium/calendar/EventProxy.java", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='2289' length='0'> </replacement>
<replacement offset='2584' length='3'> </replacement>
<replacement offset='2825' length='0'> </replacement>
<replacement offset='2944' length='3'> </replacement>
<replacement offset='3004' length='4'> </replacement>
<replacement offset='3038' length='0'> </replacement>
<replacement offset='3040' length='0'> </replacement>
<replacement offset='3041' length='0'> </replacement>
<replacement offset='3075' length='4'> </replacement>
<replacement offset='3134' length='4'> </replacement>
<replacement offset='3193' length='4'> </replacement>
<replacement offset='3254' length='4'> </replacement>
<replacement offset='3315' length='4'> </replacement>
<replacement offset='3373' length='4'> </replacement>
<replacement offset='3383' length='4'> </replacement>
<replacement offset='3430' length='1'></replacement>
<replacement offset='3489' length='1'>&#10;												   </replacement>
<replacement offset='3565' length='1'>&#10;			</replacement>
<replacement offset='3572' length='1'>&#10;			</replacement>
<replacement offset='3578' length='0'> </replacement>
<replacement offset='3579' length='0'> </replacement>
<replacement offset='3581' length='0'> </replacement>
<replacement offset='3582' length='0'> </replacement>
<replacement offset='3584' length='0'> </replacement>
<replacement offset='3585' length='0'> </replacement>
<replacement offset='3587' length='0'> </replacement>
<replacement offset='3588' length='0'> </replacement>
<replacement offset='3594' length='4'> </replacement>
<replacement offset='3603' length='0'> </replacement>
<replacement offset='3604' length='0'> </replacement>
<replacement offset='3606' length='0'> </replacement>
<replacement offset='3607' length='0'> </replacement>
<replacement offset='3609' length='0'> </replacement>
<replacement offset='3610' length='0'> </replacement>
<replacement offset='3615' length='4'> </replacement>
<replacement offset='3624' length='0'> </replacement>
<replacement offset='3625' length='0'> </replacement>
<replacement offset='3627' length='0'> </replacement>
<replacement offset='3628' length='0'> </replacement>
<replacement offset='3634' length='4'> </replacement>
<replacement offset='3643' length='0'> </replacement>
<replacement offset='3644' length='0'> </replacement>
<replacement offset='3652' length='4'> </replacement>
<replacement offset='6083' length='3'>&#10;																</replacement>
<replacement offset='6174' length='4'>&#10;&#10;		</replacement>
<replacement offset='6191' length='2'>&#10;		</replacement>
<replacement offset='6211' length='2'>&#10;		</replacement>
<replacement offset='6214' length='3'>&#10;			</replacement>
<replacement offset='6264' length='3'>&#10;			</replacement>
<replacement offset='6286' length='4'> </replacement>
<replacement offset='6372' length='0'>&#10;									</replacement>
<replacement offset='6395' length='3'>&#10;			</replacement>
<replacement offset='6448' length='3'>&#10;			</replacement>
<replacement offset='6495' length='3'>&#10;			</replacement>
<replacement offset='6581' length='3'>&#10;			</replacement>
<replacement offset='6589' length='4'>&#10;				</replacement>
<replacement offset='6691' length='3'>&#10;			</replacement>
<replacement offset='6732' length='4'>&#10;				</replacement>
<replacement offset='6781' length='3'>&#10;			</replacement>
<replacement offset='6785' length='2'>&#10;		</replacement>
<replacement offset='6788' length='3'>&#10;&#10;		</replacement>
<replacement offset='6897' length='2'>&#10;		</replacement>
<replacement offset='6900' length='3'>&#10;			</replacement>
<replacement offset='6962' length='3'>&#10;			</replacement>
<replacement offset='7011' length='4'>&#10;				</replacement>
<replacement offset='7029' length='3'>&#10;			</replacement>
<replacement offset='7033' length='4'>&#10;&#10;			</replacement>
<replacement offset='7120' length='4'>&#10;&#10;			</replacement>
<replacement offset='7167' length='0'>&#10;				</replacement>
<replacement offset='7171' length='16'>&#10;				</replacement>
<replacement offset='7249' length='19'> </replacement>
<replacement offset='7309' length='19'>&#10;							   </replacement>
<replacement offset='7381' length='16'>&#10;				</replacement>
<replacement offset='7424' length='4'>&#10;&#10;			</replacement>
<replacement offset='7462' length='4'>&#10;				</replacement>
<replacement offset='7502' length='4'>&#10;				</replacement>
<replacement offset='7542' length='4'>&#10;				</replacement>
<replacement offset='7585' length='4'>&#10;				</replacement>
<replacement offset='7634' length='4'>&#10;				</replacement>
<replacement offset='7680' length='4'>&#10;				</replacement>
<replacement offset='7731' length='4'>&#10;				</replacement>
<replacement offset='7780' length='4'>&#10;				</replacement>
<replacement offset='7837' length='4'>&#10;				</replacement>
<replacement offset='7896' length='4'>&#10;				</replacement>
<replacement offset='7937' length='4'>&#10;				</replacement>
<replacement offset='7983' length='4'>&#10;				</replacement>
<replacement offset='8056' length='4'>&#10;				</replacement>
<replacement offset='8100' length='4'>&#10;				</replacement>
<replacement offset='8149' length='4'>&#10;				</replacement>
<replacement offset='8201' length='5'>&#10;&#10;				</replacement>
<re [...]

2021-03-13 17:29 UTC, closed without merging