[TIMOB-24000] Module build should error if the apiversion in manifest…
appcelerator/titanium_mobile pull request #9563
Opened 2017-10-27 16:20 UTC by feons

… does not match the SDKs apiversion

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24000

2017-10-27 16:25 UTC, cb1kenobi commented
I thought we discussed that the apiversion should be dictated by the module build for the selected SDK version. No?

2017-10-27 16:34 UTC, feons commented
then {{minsdk}} should also be updated, but do we have a record of the exact min sdk version for a given apiversion?

2017-10-27 17:24 UTC, cb1kenobi commented
I'm not sure. If we don't, then it might be a good idea to start a wiki page (or section of existing page) documenting the min sdk info.

2017-10-27 18:31 UTC, sgtcoolguy commented
We do not have an exact record of the sdk versions that bumped the module api versions, but we should.

The apiversion mismatch is a good time to alert the user to update both that and the minSDK. We could just ignore the user-supplied apiversion and stick the current one into the built manifest, but it means the minSDK has to be updated as well.

We could stick a JSON file into the SDK to map from apiversion to sdk version and insert both (or tell the user what they should be)...

2017-11-06 15:46 UTC, sgtcoolguy commented on android/cli/commands/_buildModule.js
> +			logger.error(__('Please update module manifest apiversion to match Titanium SDK module apiversion.'));
It'd be good to also alert them that they likely need to update the minSDK value too.

2017-11-06 15:46 UTC, sgtcoolguy commented on iphone/cli/commands/_buildModule.js
> +		logger.error(__('Please update module manifest apiversion to match Titanium SDK module apiversion.'));
alert about minSDK too.

2017-11-06 15:48 UTC, sgtcoolguy requested changes
So at a bare minimum we should alert about minSDK too. Ideally we'd be able to tell them the minSDK version to use by adding some JSON file into our SDK (or maybe add to the package.json files) the mapping of apiversion -> minSDK.

If we had that data, we could potentially just inject the apiversion and minSDK for them - though I would assume we should at least alert them that we overrode the values or something.

2017-11-13 18:55 UTC, mukherjee2 approved these changes
Passed FR with this environment:
Node Version: 6.11.5
NPM Version: 3.10.10
Mac OS: 10.13
Windows OS 10.0.14393
Appc CLI: 7.0.0-master.6
Appc CLI NPM: 4.2.11-2
Ti SDK version 7.0.0

2017-11-13 21:58 UTC, merged