[TIMOB-17340] Android: Implement Ti.UI.ATTRIBUTE_BASELINE_OFFSET
appcelerator/titanium_mobile pull request #9564
Opened 2017-10-27 17:19 UTC by garymathews

- Implement `Titanium.UI.ATTRIBUTE_BASELINE_OFFSET` for Android for parity with iOS

###### TEST CASE
```JS
var win = Ti.UI.createWindow({backgroundColor: 'gray'}),
    text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lobortis laoreet nibh in tempor. Mauris justo nibh, suscipit ut venenatis id, vehicula quis arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    atr = Ti.UI.createAttributedString({
        text: text,
        attributes: [{
            type: Ti.UI.ATTRIBUTE_BASELINE_OFFSET,
            value: 50,
            range: [0, text.length]
        }]
    }),
    lbl = Ti.UI.createLabel({
        top: 5,
        left: 5,
        width: Ti.UI.FILL,
        height: Ti.UI.SIZE,
        attributedString: atr
    });

win.add(lbl);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-17340)

2017-11-06 23:47 UTC, jquick-axway requested changes
The following document needs to be updated to indicate Android support. It should be moved from the "iOS Attributes" section to the "Types of Attributes" section.
http://docs.appcelerator.com/platform/latest/#!/guide/Attributed_Strings-section-src-37538231_AttributedStrings-Baseline

We may want to use the above doc's code example for this PR's test case instead since it shows a picture of the result on iOS.

2017-11-07 23:36 UTC, garymathews commented
@jquick-axway ah, those docs don't live in this repo; they are on our wiki. I won't update them yet until this PR has passed FR/CR and has been merged (to be sure this will be in 7.0.0) since I believe the changes to those docs would go live.

2017-11-08 00:31 UTC, jquick-axway approved these changes
CR: Pass

2017-11-13 19:57 UTC, lokeshchdhry commented
FR Passed.

Property `Ti.UI.ATTRIBUTE_BASELINE_OFFSET` works as expected:
1. Checked it with `label`.
2. Checked it with `TextField`.
3. Checked it with `TextArea`.

Studio Ver:     4.10.0.201709271713
SDK Ver:        7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.10
Appc CLI:       6.3.0
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.7
Node Ver:       7.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Nexus 6P --- Android 8.0.0

2017-11-13 23:52 UTC, merged

2018-12-07 01:47 UTC, joshualambert commented
This PR just saved my bacon. Thanks y'all!