[TIMOB-11709] Android: String.formatTime causes app crash when date i…
appcelerator/titanium_mobile pull request #9572
Opened 2017-10-31 13:35 UTC by maggieaxway

…s string

Update TitaniumModule.java

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-11709

````js

var win = Ti.UI.createWindow({
--
backgroundColor:'white'
});
win.addEventListener('click', function() {
 
var date = "GIBBERISH";
//var date = new Date();
alert( String.formatTime(date) );
 
 
});
 
win.open();

2017-10-31 13:56 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/maggieaxway/titanium_mobile/blob/TIMOB-11709/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2017-11-06 23:24 UTC, jquick-axway requested changes
@maggieaxway, fixing this on the Java side is definitely simpler. I'm just requesting a couple minor changes.

2017-11-06 23:24 UTC, jquick-axway commented on android/titanium/src/java/ti/modules/titanium/TitaniumModule.java
> +		if (time != null && time instanceof Date) {
You don't need to do a `null` check. It's safe to pass a `null` reference to `instanceof` and it'll return false in that case. So, change to this...

```java
if (time instanceof Date) {
```

2017-11-06 23:24 UTC, jquick-axway commented on android/titanium/src/java/ti/modules/titanium/TitaniumModule.java
> +			Log.e(TAG, "Error occurred while formatting time please provide a Date()");
Let's change this error message from...

```java
Log.e(TAG, "Error occurred while formatting time please provide a Date()");
```

...to...

```java
Log.e(TAG, "The string.formatTime() function was given an invalid argument. Must be of type 'Date'.");
```

2017-11-07 18:12 UTC, jquick-axway approved these changes
CR: Pass

2017-11-14 01:51 UTC, lokeshchdhry commented
FR Passed.

`String.formatTime("String")` & `String.formatDate("String")` throws error : 
`[ERROR] :  [Nexus 6P] TitaniumModule: (main) [2678,2678] The string.formatTime() function was given an invalid argument. Must be of type 'Date'.
[ERROR] :  [Nexus 6P] TitaniumModule: (main) [38,2716] The string.formatDate() function was given an invalid argument. Must be of type 'Date'.`

No app crash seen.

Studio Ver:     4.10.0.201709271713
SDK Ver:        7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.10
Appc CLI:       6.3.0
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.7
Node Ver:       7.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Nexus 6P --- Android 8.0.0

2017-11-14 21:15 UTC, merged