[TIMOB-20522] Use FusedLocationProviderClient for Ti.Geolocation
appcelerator/titanium_mobile pull request #9634
Opened 2017-11-28 23:59 UTC by garymathews

- Use `FusedLocationProviderClient` when `ti.playservices` module is included in `tiapp.xml`, falling back to previous behavior if not available

###### TEST CASE
```JS
var win = Ti.UI.createWindow({backgroundColor: 'gray'}),
	listView = Ti.UI.createListView(),
	count = 1;

Ti.Geolocation.accuracy = Ti.Geolocation.ACCURACY_HIGH;

function getLocation() {
	Ti.Geolocation.addEventListener('location', function(e) {
		var section = Ti.UI.createListSection({
			headerTitle: '#' + count++
		});
		if (e.code === 0) {
			section.setItems([
				{properties: {title: 'LOCATION:\n' + e.latitude + ', ' + e.longitude, color: 'orange'}},
				{properties: {title: 'ALTITUDE:\n' + e.altitude, color: 'orange'}},
				{properties: {title: 'ACCURACY:\n' + e.accuracy, color: 'orange'}}
			]);
		} else {
			section.setItems([
				{properties: {title: 'ERROR:\n' + e.error, color: 'red'}}
			]);
		}
	    listView.appendSection(section);
	});
}

win.addEventListener('open', function(){
	if(Ti.Geolocation.hasLocationPermissions()){
		getLocation();
	}else{
		Ti.Geolocation.requestLocationPermissions(Ti.Geolocation.AUTHORIZATION_ALWAYS, function(e){
			if (e.success) {
				getLocation();
			} else {
				alert('could not obtain location permissions');
			}
		});
	}
});

win.add(listView);
win.open();
```

NOTE: The play services libraries for the Geolocation module are only required to compile the SDK. They are not included with the SDK and won't cause conflicts with `ti.playservices`. However, they will need updating if the Google API changes.

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20522)

2017-11-29 07:53 UTC, hansemannn commented
@garymathews Does this also affect https://github.com/appcelerator/titanium_mobile/pull/9633?

2017-11-29 17:08 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  1 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/garymathews/titanium_mobile/blob/TIMOB-20522/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9634/5//artifact/dist/dist/mobilesdk-7.0.0.v20171129084644-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2017-11-29 19:15 UTC, garymathews commented
@hansemannn https://github.com/appcelerator/titanium_mobile/pull/9633 is not affected by this

2017-11-29 20:11 UTC, hansemannn commented on apidoc/Titanium/Geolocation/Geolocation.yml
> +        since: "2.0.0"
I don't think they are deprecated for iOS. Maybe only deprecate and remove for Android?

2018-02-15 20:28 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9634/39/artifact/dist/mobilesdk-7.2.0.v20180215121535-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-02-16 22:27 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9634/41/artifact/dist/mobilesdk-7.2.0.v20180216141433-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-02-16 22:58 UTC, lokeshchdhry commented
FR Passed.
`FusedLocationProviderClient` works as expected when `ti.playservices` module is included in the project & falls back to old behaviour if not.

Also, No crash is seen if wrong accuracy  like `Ti.Geolocation.ACCURACY_BEST_FOR_NAVIGATION` is provided which is not meant for Android.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.2.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.2
Appc NPM:       4.2.12
Appc CLI:       7.0.2
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.11.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 6P --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1

2018-02-16 23:40 UTC, jquick-axway commented
@lokeshchdhry, can you also try testing this with the `ti.playservices` module included on an Android emulator that does **NOT** have Google Play on it please?

The reason is Google Play Services is an APK that is installed on the device. It's a background process that the `ti.playservices` communicates with to acquire location data from. So, it's a 3rd test case. In this case, it should still fallback to using the old behavior.

2018-02-16 23:57 UTC, lokeshchdhry commented
@jquick-axway , Sure thanks for the suggestion.

2018-02-17 00:17 UTC, lokeshchdhry commented
@garymathews , On a genymotion emulator with no playservices I don't see any location events. I think its not falling back to old behaviour.

2018-02-17 00:31 UTC, jquick-axway requested changes

2018-02-17 00:31 UTC, jquick-axway commented on android/modules/geolocation/src/java/ti/modules/titanium/geolocation/android/FusedLocationProvider.java
> +		return PlayServices.validVersion();
We should also check if `isGooglePlayServicesAvailable()` returns `SUCCESS` in the `hasPlayServices()` method.

This is to handle the case where `ti.playservices` module is included, but we're running on a device/emulator that doesn't have Google Play Services installed, is disabled, or is too old.

2018-02-21 00:58 UTC, build commented
<!--
  1 failure:  :disappointed_rel...
  0 warning: 
  1 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.2.0 test /Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9634-6XW6WCHHZQKTMX7AJOVQZFAFYRCDAXXTW4JHBFBMRXGRJRWMXZUQ
> grunt

Running "appcJs:src" (appcJs) task

Running "eslint:src" (eslint) task

/Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9634-6XW6WCHHZQKTMX7AJOVQZFAFYRCDAXXTW4JHBFBMRXGRJRWMXZUQ/android/cli/commands/_buildModule.js
  554:18  warning  Found non-literal argument to RegExp Constructor  security/detect-non-literal-regexp

✖ 1 problem (0 errors, 1 warning)


Running "continue:on" task

Running "retire:js" (retire) task
Ignoring {"paths":["growl"],"descriptors":[]}
Downloading https://raw.github.com/RetireJS/retire.js/master/repository/jsrepository.json ...
(node:48779) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Checking: dangerfile.js
Checking: Gruntfile.js
Checking: apidoc/docgen.js
Checking: apidoc/lib/addon_generator.js
Checking: apidoc/lib/changes_generator.js
Checking: apidoc/lib/common.js
Checking: apidoc/lib/html_generator.js
Checking: apidoc/lib/jsca_generator.js
Checking: apidoc/lib/jsduck_generator.js
Checking: apidoc/lib/json_generator.js
Checking: apidoc/lib/modulehtml_generator.js
Checking: apidoc/lib/parity_generator.js
Checking: apidoc/lib/solr_generator.js
Checking: apidoc/validate.js
Checking: build/android.js
Checking: build/androidsdk.js
Checking: build/ant.js
Checking: build/docs.js
Checking: build/git.js
Checking: build/ios.js
Checking: build/packager.js
Checking: build/scons-build.js
Checking: build/scons-clean.js
Checking: build/scons-cleanbuild.js
Checking: build/scons-install.js
Checking: build/scons-modules-integrity.js
Checking: build/scons-package.js
Checking: build/scons-ssri.js
Checking: build/scons-test.js
Checking: build/scons-update-node-deps.js
Checking: build/scons.js
Checking: build/titanium-sdk/lib/titanium.js
Checking: build/utils.js
Checking: build/windows.js
Checking: cli/commands/build.js
Checking: cli/commands/clean.js
Checking: cli/commands/create.js
Checking: cli/commands/project.js
Checking: cli/hooks/hyperloop-fix.js
Checking: cli/lib/creator.js
Checking: cli/lib/creators/app.js
Checking: cli/lib/creators/applewatch.js
Checking: cli/lib/creators/module.js
Checking: cli/lib/info.js
Checking: android/cli/commands/_build.js
Checking: android/cli/commands/_buildModule.js
Checking: android/cli/hooks/aar-transform.js
Checking: android/cli/hooks/package.js
Checking: android/cli/hooks/run.js
Checking: android/cli/lib/AndroidManifest.js
Checking: android/cli/lib/base-builder.js
Checking: android/cli/lib/detect.js
Checking: android/cli/lib/info.js
Checking: android/cli/tests/run.js
Checking: android/cli/tests/test-androidmanifest.js
Checking: iphone/cli/commands/_build.js
Checking: iphone/cli/commands/_buildModule.js
Checking: iphone/cli/hooks/frameworks.js
Checking: iphone/cli/hooks/hyperloop.js
Checking: iphone/cli/hooks/install.js
Checking: iphone/cli/hooks/package.js
Checking: iphone/cli/hooks/run.js
Checking: iphone/cli/lib/info.js
Checking: tests/Resources/ti.example.addontest.js
No vulnerabilities found.

Running "retire:node" (retire) task
Ignoring {"paths":["growl"],"descriptors":[]}
Downloading https://raw.github.com/RetireJS/retire.js/master/repository/npmrepository.json ...
(node:48779) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Checking: .
Missing version for babel-eslint. Need to run npm install ?
Missing version for eslint-plugin-jsx-a11y. Need to run npm install ?
Missing version for eslint-plugin-react. Need to run npm install ?
Missing version for babel-eslint. Need to run npm install ?
Missing version for eslint-plugin-jsx-a11y. Need to run npm install ?
Missing version for eslint-plugin-react. Need to run npm install ?
No vulnerabilities found.

Running "continue:off" task

Running "ios_format:src" (ios_format) task

Running "android_format:src" (android_format) task
Fatal error: Error: Formatting incorrect on "android/modules/geolocation/src/java/ti/modules/titanium/geolocation/android/LocationProviderProxy.java", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='4291' length='1'>&#10;			</replacement>
</replacements>

npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-02-21 19:09 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9634/50/artifact/dist/mobilesdk-7.2.0.v20180221105029-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-02-21 21:17 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9634/52/artifact/dist/mobilesdk-7.2.0.v20180221130004-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-02-21 21:22 UTC, merged

2018-02-21 21:24 UTC, lokeshchdhry commented
Oops forgot to comment before merging.

Checked the changes & geolocation works as expected in emulator without google playservices.

Studio Ver: 5.0.0.201712081732
SDK Ver: 7.2.0 local build
OS Ver: 10.13.2
Xcode Ver: Xcode 9.2
Appc NPM: 4.2.12
Appc CLI: 7.0.2
Daemon Ver: 1.0.1
Ti CLI Ver: 5.0.14
Alloy Ver: 1.11.0
Node Ver: 8.9.1
NPM Ver: 5.5.1
Java Ver: 1.8.0_101
Devices: ⇨ google Nexus 6P --- Android 8.0.0
⇨ google Nexus 5 --- Android 6.0.1