[TIMOB-25572] Android: Provide Toolbar customization through DrawerLayout
appcelerator/titanium_mobile pull request #9646
Opened 2017-12-01 16:51 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25572

**Description:**
Add `customToolbar` creationOnly property to DrawerLayout which expects an instance of Ti.UI.Toolbar.
It would replace the embedded Toolbar and provide access to a greater customization.
This property is **_MUST_** be used together with `toolbarEnabled = false` in the creation dictionary to have an effect.

**Test case:**
app.js
```
var win = Ti.UI.createWindow({ theme: "Theme.AppCompat.NoTitleBar" });
    toolbar = Ti.UI.createToolbar({titleTextColor: 'red',
                                   backgroundColor: 'cyan'}),
    leftView = Ti.UI.createView({backgroundColor:'white'}),
    centerView = Ti.UI.createView({backgroundColor:'gray'}),
    drawer = Ti.UI.Android.createDrawerLayout({ toolbarEnabled: false,
                                                customToolbar: toolbar,
                                                leftView: leftView,
                                                centerView: centerView });
win.add(drawer);
win.open();
```

2017-12-01 17:11 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  1 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/ypbnv/titanium_mobile/blob/TIMOB-25572/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9646/1//artifact/dist/dist/mobilesdk-7.1.0.v20171201085415-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2017-12-01 18:12 UTC, garymathews requested changes
I think it would be better to have `toolbarEnabled == true` to enable either custom or default toolbar.

- If `toolbarEnabled == true` enable default toolbar unless `customToolbar` has been defined, then enable that instead.
- Minor, but maybe rename `customToolbar` into `toolbar`?

2017-12-01 18:12 UTC, garymathews commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIDrawerLayout.java
> +import java.util.HashMap;
Is this used?

2017-12-01 18:12 UTC, garymathews commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIDrawerLayout.java
> +				if (((AppCompatActivity) proxy.getActivity()).getSupportActionBar() == null && (proxy.getActivity()).getActionBar() == null) {
Maybe define `activity` to improve readability:
```Java
AppCompatActivity activity = (AppCompatActivity) proxy.getActivity();

if (activity.getSupportActionBar() == null && activity.getActionBar() == null) {
	View customToolbarInstance = ((ToolbarProxy) d.get(TiC.PROPERTY_CUSTOM_TOOLBAR)).getToolbarInstance();
	activity.setSupportActionBar((Toolbar) customToolbarInstance);
	RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
	((RelativeLayout) layout.findViewById(id_drawer_layout_container)).addView(customToolbarInstance, layoutParams);
}
```

2017-12-04 12:20 UTC, ypbnv commented
@garymathews Updated code and test case. I noticed that setting `toolbarEnabled=true` and using a theme with default ActionBar results in double toolbars. Would we want to prevent this in the Android side -  for instance ignoring the property when we have a default ActionBar?

2017-12-04 20:52 UTC, garymathews reviewed
@ypbnv Yes we would want to prevent that; could you update the PR for that scenario?

2017-12-05 14:37 UTC, ypbnv commented
@garymathews Updated the PR.

2017-12-05 18:20 UTC, garymathews commented
@ypbnv Looks good, docs?

2017-12-06 15:29 UTC, ypbnv commented
@garymathews Updated PR. BTW do we support DrawerLayout through Alloy? It would be nice to add this there as well if we do.

2017-12-13 19:37 UTC, lokeshchdhry commented
FR Passed.

The `toolBar` property for `DrawerLayout` shows the toolbar & the `toolbarEnabled` property works as expected.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.1.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.11
Appc CLI:       7.0.0
Daemon Ver:     1.0.0
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.10
Node Ver:       8.9.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Pixel --- Android 7.1.1

2017-12-15 16:49 UTC, lokeshchdhry commented
@ypbnv , Can you please resolve the conflicts.

2017-12-20 17:56 UTC, lokeshchdhry commented
@ypbnv , Can you please resolve the conflicts so that the PR can be merged.

2018-01-09 22:20 UTC, lokeshchdhry commented
@ypbnv , can you please look at the unit test failures.

2018-01-10 16:28 UTC, merged

2018-01-17 16:35 UTC, TylerZubke commented
Is the hamburger icon supposed to work correctly if I use a toolbar like this? I'm using a toolbar because I need the drawer to open above the actionbar (and as far as I know this is the only way), but the arrow always shows regardless of whether the drawer is open or not. Here's my app.js

`var win = Ti.UI.createWindow({theme: "Theme.AppCompat.NoTitleBar"});
toolbar = Ti.UI.createToolbar({titleTextColor: 'white',
    backgroundColor: 'black'}),
    leftView = Ti.UI.createView({backgroundColor:'white', opacity: 0.2}),
    centerView = Ti.UI.createView({backgroundColor:'gray'}),
    drawer = Ti.UI.Android.createDrawerLayout({ toolbarEnabled: true,
        toolbar: toolbar,
        leftView: leftView,
        centerView: centerView}),


    win.addEventListener("open", function() {
        win.activity.actionBar.displayHomeAsUp = true;
        win.activity.actionBar.onHomeIconItemSelected = function() {

            drawer.toggleLeft();
        }
    })


win.add(drawer);
win.open();
`