[TIMOB-25599] Android: Fix Java object referencing
appcelerator/titanium_mobile pull request #9675
Opened 2017-12-12 00:59 UTC by garymathews

- Maintain a strong Java object reference to allow JVM to manage our Java objects

###### TEST CASE
- Select a couple of large images
- Repeatedly view each image until crash
```JS
var window = Ti.UI.createWindow();
var tableView = Ti.UI.createTableView(
{
	width: Ti.UI.FILL,
	height: Ti.UI.FILL,
});
window.add(tableView);
var addButton = Ti.UI.createButton(
{
	title: "Add",
	left: "10dp",
	bottom: "10dp",
});
addButton.addEventListener("click", function(e) {
	var dialog = Ti.UI.createAlertDialog(
	{
		message: "Which media type do you want to open?",
		buttonNames: ["Photo", "Video", "Both"],
	});
	dialog.addEventListener("click", function(e) {
		var mediaTypes;
		if (e.index === 0) {
			mediaTypes = [Ti.Media.MEDIA_TYPE_PHOTO];
		} else if (e.index === 1) {
			mediaTypes = [Ti.Media.MEDIA_TYPE_VIDEO];
		} else if (e.index === 2) {
			mediaTypes = [Ti.Media.MEDIA_TYPE_PHOTO, Ti.Media.MEDIA_TYPE_VIDEO];
		} else {
			Ti.API.info("@@@ Alert was canceled.");
			return;
		}
		Ti.Media.openPhotoGallery(
		{
			allowMultiple: true,
			allowEditing: false,
			autohide: true,
			mediaTypes: mediaTypes,
			success: function(e) {
				Ti.API.info("@@@ success() e: " + JSON.stringify(e));
				var createRowFrom = function(selectionEvent) {
					if (!selectionEvent || !selectionEvent.media) {
						selectionEvent =
						{
							mediaType: "null",
							media:
							{
								file:
								{
									name: "null",
									nativePath: "null"
								},
							},
						};
					}
					var fileName = null;
					if (selectionEvent.media.file) {
						fileName = selectionEvent.media.file.name;
					}
					if (!fileName) {
						if (selectionEvent.mediaType === Ti.Media.MEDIA_TYPE_VIDEO) {
							fileName = "Unknown Video Name";
						} else {
							fileName = "Unknown Image Name";
						}
					}
					var row = Ti.UI.createTableViewRow({ title: fileName });
					row.addEventListener("click", function(e) {
						switch (selectionEvent.mediaType) {
							case Ti.Media.MEDIA_TYPE_PHOTO:
							case Ti.Media.MEDIA_TYPE_LIVEPHOTO:
								var childWindow = Ti.UI.createWindow();
								childWindow.add(Ti.UI.createImageView(
								{
									image: selectionEvent.media,
									width: Ti.UI.FILL,
									height: Ti.UI.FILL,
								}));
								childWindow.open();
								break;
							case Ti.Media.MEDIA_TYPE_VIDEO:
								var childWindow = Ti.UI.createWindow();
								childWindow.add(Ti.Media.createVideoPlayer(
								{
									url: selectionEvent.media.nativePath,
									autoplay: true,
									mediaControlStyle: Ti.Media.VIDEO_CONTROL_DEFAULT,
									scalingMode: Ti.Media.VIDEO_SCALING_ASPECT_FIT,
									width: Ti.UI.FILL,
									height: Ti.UI.FILL,
								}));
								childWindow.open();
								break;
							default:
								alert("Unknown media type selected.");
								break;
						}
					});
					return row;
				};
				if (e.images) {
					for (var index = 0; index < e.images.length; index++) {
						tableView.appendRow(createRowFrom(e.images[index]));
					}
				}
				if (e.videos) {
					for (var index = 0; index < e.videos.length; index++) {
						tableView.appendRow(createRowFrom(e.videos[index]));
					}
				}
			},
			cancel: function() {
				Ti.API.info("@@@ Photo gallery selection canceled.");
			},
			error: function() {
				Ti.API.info("@@@ Photo gallery selection error.");
			},
		});
	});
	dialog.show();
});
window.add(addButton);
var clearButton = Ti.UI.createButton(
{
	title: "Clear",
	right: "10dp",
	bottom: "10dp",
});
clearButton.addEventListener("click", function(e) {
	tableView.data = [];
});
window.add(clearButton);
window.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25599)

2017-12-12 01:19 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9675/1/artifact/dist/mobilesdk-7.1.0.v20171211170159-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2017-12-12 15:57 UTC, sgtcoolguy commented on android/runtime/v8/src/native/JavaObject.cpp
> +			} else {
So this fix should definitely be applied. I assume if the store ref is NULL, trying to delete the local ref will be very bad.

2017-12-12 16:02 UTC, sgtcoolguy commented on android/runtime/v8/src/native/JavaObject.cpp
> +	if (!isDetached()) {
So if you're using this quard, it's specifically checking isWeakRef_ is true, which only happens if #MakeJavaWeak() was called (and you've commented that call out from #detach() now). So I'm not sure this guard will ever be false now.

2017-12-12 16:15 UTC, sgtcoolguy requested changes
So I think the last else block is correct and will avoid some crashes, but I still think this points to a memory management issue.

Ideally we should never reach a state where the JS side is "weak" and the Java side has been GC'd but suddenly the JS side is re-referenced.

The memory lifecycle here is that we basically wrap the Java object and tie it to a JS object and then explicitly tell V8 that the JS object is "independent" and to let us know when it thinks it can be GC'd because there's no more references. When we get that notification we basically stop the GC call and make the Java side weak. So at that point V8 thinks it no longer needs it and Java can try and clean it up at any point.

It's here that somehow our C++ code is trying to call getJavaObject() to resurrect the references and the Java side was already GC'd (if you're seeing that log message). So it looks like we have a reference issue on the C++ lifecycle.

2017-12-12 16:39 UTC, sgtcoolguy commented
Looking at the ticket, it's actually crashing in MakeJSWeak() so it's likely that the JS object already got GC'd.

So from the logging you noted and the crash location in this ticket, it would appear that both/either Java/JS sides are getting GC'd before we've expected them to, so somehow/where we're not properly tracking references in our C++ code, I believe.

2017-12-13 00:11 UTC, garymathews commented
@sgtcoolguy So I added the ability to create soft references to our Java objects. This also fixes the issue and makes GC less inclined to collect objects that are still in use, but still allows them to be collected when under memory constrains.

Also, `isDetached` can still return `true` even if `isWeakRef_` is `false`. I added this condition to prevent the hard crash if the Java object had already been collected.

2017-12-13 19:20 UTC, sgtcoolguy approved these changes

2017-12-13 19:44 UTC, sgtcoolguy commented
Any chance we can automate this test by just repeatedly opening/closing image views on some large image file in the test app?

2017-12-19 18:34 UTC, garymathews commented
I don't think we can create a test case for this, I wasn't able to reproduce this through automation and it's very temperamental

2018-01-08 23:42 UTC, lokeshchdhry commented
FR Passed.

Used the test above & opened large images ~4.5MB (7 images) randomly multiple times. & did not see any V8 crash.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.1.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.11
Appc CLI:       7.0.1
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.10
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Pixel --- Android 7.1.1
                ⇨ google Nexus 5 --- Android 6.0.1

2018-01-25 17:34 UTC, lokeshchdhry commented
@garymathews , I still see a crash with your latest fixes but this time it took more try's:
https://gist.github.com/lokeshchdhry/0b21e9fbb04b9acfc89ebebcdc49afe5

2018-02-08 19:56 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9675/12/artifact/dist/mobilesdk-7.1.0.v20180208114212-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-02-24 01:04 UTC, merged

2018-02-24 01:07 UTC, lokeshchdhry commented
Forgot to comment.

FR passed.

No app crash seen.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.2.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.2
Appc NPM:       4.2.12
Appc CLI:       7.0.2
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.11.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Nexus 6P --- Android 8.0.0