[TIMOB-25672] iOS: Fix all core-SDK warnings
appcelerator/titanium_mobile pull request #9733
Opened 2018-01-14 15:36 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25672

2018-01-14 15:39 UTC, build commented
<!--
  1 failure:  :disappointed_rel...
  0 warning: 
  2 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :thumbsup: Hey!, You deleted more code than you added. That's awesome!
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.1.0 test /Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9733-AEEWUM3L3O7WGZBFVVNEDBGDX5NFCRPNWZ5X3NSLR5WS4LERY7VA
> grunt

Running "appcJs:src" (appcJs) task

Running "eslint:src" (eslint) task

/Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9733-AEEWUM3L3O7WGZBFVVNEDBGDX5NFCRPNWZ5X3NSLR5WS4LERY7VA/dangerfile.js
   1:50  warning  'schedule' is defined but never used              no-unused-vars
  26:7   warning  'CURRENT_DIR' is assigned a value but never used  no-unused-vars

/Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9733-AEEWUM3L3O7WGZBFVVNEDBGDX5NFCRPNWZ5X3NSLR5WS4LERY7VA/android/cli/commands/_build.js
  1635:9  warning  Blocks are nested too deeply (6)  max-depth

/Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9733-AEEWUM3L3O7WGZBFVVNEDBGDX5NFCRPNWZ5X3NSLR5WS4LERY7VA/android/cli/commands/_buildModule.js
  554:18  warning  Found non-literal argument to RegExp Constructor  security/detect-non-literal-regexp

✖ 4 problems (0 errors, 4 warnings)


Running "continue:on" task

Running "retire:js" (retire) task
Ignoring {"paths":["growl"],"descriptors":[]}
Loading from cache: https://raw.github.com/RetireJS/retire.js/master/repository/jsrepository.json
Reading /var/folders/zn/rs3xbfz54xdf16gmx0hwvtmr0000gm/T/.retire-cache/1515943921416.json ...
Checking: dangerfile.js
Checking: Gruntfile.js
Checking: apidoc/docgen.js
Checking: apidoc/lib/addon_generator.js
Checking: apidoc/lib/changes_generator.js
Checking: apidoc/lib/common.js
Checking: apidoc/lib/html_generator.js
Checking: apidoc/lib/jsca_generator.js
Checking: apidoc/lib/jsduck_generator.js
Checking: apidoc/lib/json_generator.js
Checking: apidoc/lib/modulehtml_generator.js
Checking: apidoc/lib/parity_generator.js
Checking: apidoc/lib/solr_generator.js
Checking: apidoc/validate.js
Checking: build/android.js
Checking: build/androidsdk.js
Checking: build/ant.js
Checking: build/docs.js
Checking: build/git.js
Checking: build/ios.js
Checking: build/packager.js
Checking: build/scons-build.js
Checking: build/scons-clean.js
Checking: build/scons-cleanbuild.js
Checking: build/scons-install.js
Checking: build/scons-package.js
Checking: build/scons-test.js
Checking: build/scons-update-node-deps.js
Checking: build/scons.js
Checking: build/titanium-sdk/lib/titanium.js
Checking: build/utils.js
Checking: build/windows.js
Checking: cli/commands/build.js
Checking: cli/commands/clean.js
Checking: cli/commands/create.js
Checking: cli/commands/project.js
Checking: cli/hooks/hyperloop-fix.js
Checking: cli/lib/creator.js
Checking: cli/lib/creators/app.js
Checking: cli/lib/creators/applewatch.js
Checking: cli/lib/creators/module.js
Checking: cli/lib/info.js
Checking: android/cli/commands/_build.js
Checking: android/cli/commands/_buildModule.js
Checking: android/cli/hooks/aar-transform.js
Checking: android/cli/hooks/package.js
Checking: android/cli/hooks/run.js
Checking: android/cli/lib/AndroidManifest.js
Checking: android/cli/lib/base-builder.js
Checking: android/cli/lib/detect.js
Checking: android/cli/lib/info.js
Checking: android/cli/tests/run.js
Checking: android/cli/tests/test-androidmanifest.js
Checking: iphone/cli/commands/_build.js
Checking: iphone/cli/commands/_buildModule.js
Checking: iphone/cli/hooks/frameworks.js
Checking: iphone/cli/hooks/hyperloop.js
Checking: iphone/cli/hooks/install.js
Checking: iphone/cli/hooks/package.js
Checking: iphone/cli/hooks/run.js
Checking: iphone/cli/lib/info.js
No vulnerabilities found.

Running "retire:node" (retire) task
Ignoring {"paths":["growl"],"descriptors":[]}
Loading from cache: https://raw.github.com/RetireJS/retire.js/master/repository/npmrepository.json
Reading /var/folders/zn/rs3xbfz54xdf16gmx0hwvtmr0000gm/T/.retire-cache/1515943921790.json ...
Checking: .
Missing version for babel-eslint. Need to run npm install ?
Missing version for eslint-plugin-jsx-a11y. Need to run npm install ?
Missing version for eslint-plugin-react. Need to run npm install ?
Missing version for babel-eslint. Need to run npm install ?
Missing version for eslint-plugin-jsx-a11y. Need to run npm install ?
Missing version for eslint-plugin-react. Need to run npm install ?
No vulnerabilities found.

Running "continue:off" task

Running "ios_format:src" (ios_format) task
Fatal error: Error: Formatting incorrect on "iphone/Classes/MediaModule.m", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='2005' length='1'> </replacement>
</replacements>

npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-01-17 09:29 UTC, vijaysingh-axway requested changes
@hansemannn Can you look in the issue? Thanks!

2018-01-17 11:26 UTC, hansemannn commented on iphone/Classes/TiMediaVideoPlayerProxy.m
> -  [self removeNotificationObserver];
Jenkins actually passes the tests, but fails later. Which test did it mention?

2018-01-17 11:30 UTC, hansemannn commented on iphone/Classes/TiMediaVideoPlayerProxy.m
> -  [self removeNotificationObserver];
Just reproduced it, adding a test-case for it in my test-suite as well.

2018-01-17 14:19 UTC, hansemannn commented on iphone/Classes/TiMediaVideoPlayerProxy.m
> -  [self removeNotificationObserver];
Fixed as part of https://github.com/appcelerator/titanium_mobile/pull/9733/commits/31182c65d25b6a7d134790aa5571912c1ad5983d

2018-01-18 09:37 UTC, vijaysingh-axway approved these changes
CR passed.

2018-01-23 00:49 UTC, mukherjee2 commented
Passed FR using this environment:
Node Version: 8.9.1
NPM Version: 5.5.1
Mac OS: 10.13.1
Appc CLI: 7.0.1
Appc CLI NPM: 4.2.11
Titanium SDK version: 7.0.2 (artifacts from this PR)
Appcelerator Studio vers 5.0.0
iOS 11.1

Validated by building and launching app on device. I observed no warnings or memory leaks using Instruments.

2018-01-23 00:49 UTC, mukherjee2 approved these changes
Passed FR. See comments.

2018-01-23 01:04 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  2 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :thumbsup: Hey!, You deleted more code than you added. That's awesome!
  </td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9733/13/artifact/dist/mobilesdk-7.1.0.v20180122164742-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.WebView | userAgent | 11.454 | Error: timeout of 10000ms exceeded |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-01-23 17:54 UTC, merged