[TIMOB-10368] iOS: Expose "color" and "hintTextColor" to Ti.UI.SearchBar
appcelerator/titanium_mobile pull request #9772
Opened 2018-01-26 14:41 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-10368

2018-01-26 14:56 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9772/1/artifact/dist/mobilesdk-7.1.0.v20180126064230-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-01-27 02:26 UTC, jquick-axway requested changes

2018-01-27 02:26 UTC, jquick-axway commented on apidoc/Titanium/UI/SearchBar.yml
> +    platforms: [iphone, ipad]
Android already supports this, just wasn't documented. Would you mind adding "android" to the supported platform list please?

2018-01-27 02:26 UTC, jquick-axway commented on apidoc/Titanium/UI/SearchBar.yml
> +    platforms: [iphone, ipad]
Android already supports this property too.

2018-01-27 02:26 UTC, jquick-axway commented on tests/Resources/ti.ui.searchbar.addontest.js
> +	it.ios('.hintTextColor', function () {
Android can run this unit test too.
Change to `it.windowsMissing`?

2018-01-27 02:26 UTC, jquick-axway commented on tests/Resources/ti.ui.searchbar.addontest.js
> +	it.ios('.color', function () {
Android can run this unit test.
Change to `it.windowsMissing`?

2018-01-29 07:21 UTC, vijaysingh-axway approved these changes
CR passed.

2018-01-29 07:39 UTC, hansemannn commented
@jquick-axway Can you update your review?

2018-01-29 10:10 UTC, build commented
<!--
  1 failure:  Test suite crashe...
  0 warning: 
  
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Test suite crashed on iOS simulator. Please see <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9772/5/artifact/mocha_2018-01-28-203704_Ginsu-macOS03.crash">the crash log</a> for more details.
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-01-29 18:00 UTC, jquick-axway approved these changes
CR: Pass

2018-02-26 22:55 UTC, ewieberappc commented
FR Passed. Tested with 7_1_X branch PR

2018-02-26 23:38 UTC, merged