[TIMOB-24206] iOS: Fix image leaks on JSCore
appcelerator/titanium_mobile pull request #9850
Opened 2018-02-16 19:26 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24206

2018-02-16 19:43 UTC, build commented
<!--
  1 failure:  :microscope: Ther...
  0 warning: 
  1 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/hansemannn/titanium_mobile/blob/TIMOB-24206/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9850/1/artifact/dist/mobilesdk-7.2.0.v20180216112826-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-02-22 03:30 UTC, vijaysingh-axway requested changes
On iOS 11, it is crashing after selecting 30 pics/approx 3 mints.

2018-03-18 10:11 UTC, hansemannn commented
@vijaysingh-axway PR updated with the regards to the discussion on Teams. We have to extremely sensitive tests to ensure the JSGarbageCollect plays nice.

2018-03-19 09:59 UTC, vijaysingh-axway commented on iphone/Classes/TiUIView.m
> +    RELEASE_TO_NIL([self backgroundImageLayer].contents);
This line is causing crash. If I remove this line, JSGarbageCollect is working nice. I'll do more testing.

2018-03-21 05:44 UTC, vijaysingh-axway approved these changes
CR passed.

2018-05-23 08:38 UTC, merged