[TIMOB-25566] iOS: Fix setting "showControls" on videoplayer when URL is changed after creation
appcelerator/titanium_mobile pull request #9852
Opened 2018-02-16 19:59 UTC by hansemannn

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25566

2018-02-16 20:14 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9852/1/artifact/dist/mobilesdk-7.2.0.v20180216120150-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-02-16 21:43 UTC, jquick-axway commented
**Note to everyone:**
I've already written a "showsControls" unit test in PR #9770, which is merged in. So, the unit test is already covered. 👍

2018-03-12 08:03 UTC, vijaysingh-axway requested changes

2018-03-12 08:03 UTC, vijaysingh-axway commented on iphone/Classes/TiMediaVideoPlayerProxy.m
> +  id showControls = [self valueForKey:@"showControls"];
Property name is "showsControls". Please update.

2018-03-12 08:03 UTC, vijaysingh-axway commented on iphone/Classes/TiMediaVideoPlayerProxy.m
> +  [self replaceValue:value forKey:@"showControls" notification:NO];
Same as above. Property name is wrong.

2018-03-13 08:03 UTC, vijaysingh-axway requested changes
Still issue is there. Controls are not hiding.

2018-03-14 12:33 UTC, hansemannn commented
@vijaysingh-axway Not sure why I worked before, but I adjusted it to store it in the `loadProperties` which is even more clean :-).

2018-03-16 07:59 UTC, vijaysingh-axway commented
@hansemannn  Changes looks good. I guess you can add unit test for this. This is more to setting property showsControls than UI.

2018-05-03 13:42 UTC, hansemannn commented
@vijaysingh-axway Added

2018-05-07 03:22 UTC, vijaysingh-axway approved these changes
CR passed.

2018-05-23 08:56 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  1 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9852/15/artifact/dist/mobilesdk-7.3.0.v20180523014202-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| ios.Titanium.Media.VideoPlayer | showsControls | 0.001 | file:///Users/build/Library/ |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-23 09:11 UTC, merged