(7_1_X) [TIMOB-25766][TIMOB-25727] Android: Ti.Utils.base64encode fixes
appcelerator/titanium_mobile pull request #9886
Opened 2018-02-26 15:32 UTC by sgtcoolguy

**JIRA:** 
- https://jira.appcelerator.org/browse/TIMOB-25766
- https://jira.appcelerator.org/browse/TIMOB-25727

**Description:**

This is a fix for both listed tickets. Our previous "fix" was to revert the changes to avoid a regression caused by the fix to the other ticket. But then we never re-opened the original ticket when it was reverted.

This fix attempts to add more comprehensive Ti.Utils tests and fix both cases properly.

- Add more comprehensive unit tests around base64encode
- Avoid regression while still adding support for Ti.Filesystem.File argument on Android
- Remove no longer used Ti.Blob type STREAM_BASE64 code.
- Fix stream content type sniffing to only happen when the stream supports mark/reset, actually properly reset, and only sniff number of bytes we actually look at
* Remove reference to unused TiBlob type
* Add tests for hashing/encoding binary data. Update Utils module to support that and clean up the code.
* Fix iOS to support sha256/sha1 of Ti.Blob with binary data.
* Refactor code for turning args into NSData for Utils

2018-02-26 15:35 UTC, build commented
<!--
  1 failure:  :disappointed_rel...
  0 warning: 
  1 messages
  
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :disappointed_relieved: `npm test` failed. See below for details.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  ```
> titanium-mobile@7.1.0 test /Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9886-RI6CKFWLHYPQLNN2ZH5E4V25Q5CABFOBL3P2NRICCRMQYJSPF6EA
> grunt

Running "appcJs:src" (appcJs) task

Running "eslint:src" (eslint) task

/Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9886-RI6CKFWLHYPQLNN2ZH5E4V25Q5CABFOBL3P2NRICCRMQYJSPF6EA/android/cli/commands/_buildModule.js
  554:18  warning  Found non-literal argument to RegExp Constructor  security/detect-non-literal-regexp

/Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9886-RI6CKFWLHYPQLNN2ZH5E4V25Q5CABFOBL3P2NRICCRMQYJSPF6EA/tests/Resources/ti.ui.picker.addontest.js
   85:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  122:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  123:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  171:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  172:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  175:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  176:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  245:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  246:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  252:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  253:5  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions

✖ 12 problems (0 errors, 12 warnings)


Running "continue:on" task

Running "retire:js" (retire) task
Ignoring {"paths":["growl"],"descriptors":[]}
Downloading https://raw.github.com/RetireJS/retire.js/master/repository/jsrepository.json ...
(node:3032) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Checking: dangerfile.js
Checking: Gruntfile.js
Checking: apidoc/docgen.js
Checking: apidoc/lib/addon_generator.js
Checking: apidoc/lib/changes_generator.js
Checking: apidoc/lib/common.js
Checking: apidoc/lib/html_generator.js
Checking: apidoc/lib/jsca_generator.js
Checking: apidoc/lib/jsduck_generator.js
Checking: apidoc/lib/json_generator.js
Checking: apidoc/lib/modulehtml_generator.js
Checking: apidoc/lib/parity_generator.js
Checking: apidoc/lib/solr_generator.js
Checking: apidoc/validate.js
Checking: build/android.js
Checking: build/androidsdk.js
Checking: build/ant.js
Checking: build/docs.js
Checking: build/git.js
Checking: build/ios.js
Checking: build/packager.js
Checking: build/scons-build.js
Checking: build/scons-clean.js
Checking: build/scons-cleanbuild.js
Checking: build/scons-install.js
Checking: build/scons-modules-integrity.js
Checking: build/scons-package.js
Checking: build/scons-ssri.js
Checking: build/scons-test.js
Checking: build/scons-update-node-deps.js
Checking: build/scons.js
Checking: build/titanium-sdk/lib/titanium.js
Checking: build/utils.js
Checking: build/windows.js
Checking: cli/commands/build.js
Checking: cli/commands/clean.js
Checking: cli/commands/create.js
Checking: cli/commands/project.js
Checking: cli/hooks/hyperloop-fix.js
Checking: cli/lib/creator.js
Checking: cli/lib/creators/app.js
Checking: cli/lib/creators/applewatch.js
Checking: cli/lib/creators/module.js
Checking: cli/lib/info.js
Checking: android/cli/commands/_build.js
Checking: android/cli/commands/_buildModule.js
Checking: android/cli/hooks/aar-transform.js
Checking: android/cli/hooks/package.js
Checking: android/cli/hooks/run.js
Checking: android/cli/lib/AndroidManifest.js
Checking: android/cli/lib/base-builder.js
Checking: android/cli/lib/detect.js
Checking: android/cli/lib/info.js
Checking: android/cli/tests/run.js
Checking: android/cli/tests/test-androidmanifest.js
Checking: iphone/cli/commands/_build.js
Checking: iphone/cli/commands/_buildModule.js
Checking: iphone/cli/hooks/frameworks.js
Checking: iphone/cli/hooks/hyperloop.js
Checking: iphone/cli/hooks/install.js
Checking: iphone/cli/hooks/package.js
Checking: iphone/cli/hooks/run.js
Checking: iphone/cli/lib/info.js
Checking: tests/Resources/ti.api.addontest.js
Checking: tests/Resources/ti.example.addontest.js
Checking: tests/Resources/ti.network.httpclient.addontest.js
Checking: tests/Resources/ti.ui.picker.addontest.js
Checking: tests/Resources/ti.ui.tableview.addontest.js
Checking: tests/Resources/ti.utils.test.js
No vulnerabilities found.

Running "retire:node" (retire) task
Ignoring {"paths":["growl"],"descriptors":[]}
Downloading https://raw.github.com/RetireJS/retire.js/master/repository/npmrepository.json ...
(node:3032) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Checking: .
Missing version for babel-eslint. Need to run npm install ?
Missing version for eslint-plugin-jsx-a11y. Need to run npm install ?
Missing version for eslint-plugin-react. Need to run npm install ?
Missing version for babel-eslint. Need to run npm install ?
Missing version for eslint-plugin-jsx-a11y. Need to run npm install ?
Missing version for eslint-plugin-react. Need to run npm install ?
No vulnerabilities found.

Running "continue:off" task

Running "ios_format:src" (ios_format) task

Running "android_format:src" (android_format) task
Fatal error: Error: Formatting incorrect on "android/titanium/src/java/org/appcelerator/titanium/TiBlob.java", proposed changes: <?xml version='1.0'?>
<replacements xml:space='preserve' incomplete_format='false'>
<replacement offset='9868' length='0'> </replacement>
<replacement offset='10162' length='4'>&#10;				</replacement>
<replacement offset='10171' length='5'>&#10;					</replacement>
<replacement offset='10196' length='0'> </replacement>
<replacement offset='10219' length='4'>&#10;				</replacement>
<replacement offset='10248' length='5'>&#10;					</replacement>
<replacement offset='10283' length='5'>&#10;					</replacement>
<replacement offset='10300' length='4'>&#10;				</replacement>
</replacements>

npm ERR! Test failed.  See above for more details.

```
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-02-26 15:52 UTC, hansemannn requested changes
Please lint the Android source

*EDIT*: Looks okay now.

2018-02-27 17:26 UTC, hansemannn approved these changes

2018-02-28 19:48 UTC, mukherjee2 approved these changes
Passed FR with this environment:
Node Version: 8.9.1
NPM Version: 5.5.1
Mac OS: 10.13.1
Appc CLI: 7.0.2
Appc CLI NPM: 4.2.12
Titanium SDK version: 7.1.0.v20180226081834
Appcelerator Studio vers 5.0.0
Android 7.1

I tested the PR against the test cases in both JIRA tickets mentioned in the PR. No errors were seen, and expected outputs were observed.

2018-02-28 21:15 UTC, merged