Fixed deprecated since values for Geolocation.yml
appcelerator/titanium_mobile pull request #9914
Opened 2018-03-06 22:00 UTC by jawa9000

At this time, the docgen script cannot handle objects passed as values in deprecated since. Please don't pass {<platform>: <version>} as a value for the since property.

See https://jira.appcelerator.org/browse/TIDOC-3124 for details.

2018-03-06 22:28 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9914/1/artifact/dist/mobilesdk-7.1.0.v20180306140742-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-03-06 22:31 UTC, hansemannn requested changes
Missing explanation about the Android specific deprecation, please address that. Also file against master and from your fork if possible.

2018-03-06 22:58 UTC, jquick-axway commented
The descriptions for these Android "deprecated" constants already state that they're not recommended to be used. Perhaps we should just remove the "deprecation" fields since they're not deprecated on the iOS side.

On Android, you can still use these constants. The issue is we don't have equivalent settings in Google's FusedLocation provider which match these constants. So, instead, we end up enabling high power/accuracy mode for short distance constants and low power/accuracy mode for long distance constants.

2018-03-07 16:32 UTC, hansemannn commented
@jquick-axway Thats right, but doing this change, we will in fact deprecate it for all platforms. Writing that it's not recommended doesn't mean we deprecate it IMHO. But feel free to merge if you are okay with it.

2018-03-07 19:36 UTC, jquick-axway commented
I think we should just remove the deprecation fields and call it a day.

2018-03-07 20:03 UTC, hansemannn commented
Agree

2018-03-09 10:42 UTC, hansemannn commented
Closing PR as it needs to be reopened against `master` first. Also, see the above discussion for details on the proposed changes.

2018-03-09 10:42 UTC, closed without merging