[TIMOB-25850] : iOS SearchBar doesn't show Bookmark button when set on creation in TableView
appcelerator/titanium_mobile pull request #9932
Opened 2018-03-13 07:11 UTC by vijaysingh-axway

https://jira.appcelerator.org/browse/TIMOB-25850

2018-03-13 07:30 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9932/1/artifact/dist/mobilesdk-7.2.0.v20180313001315-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-03-13 08:57 UTC, hansemannn requested changes
Please loop through the proxy keys instead of checking all manually.

2018-03-14 09:46 UTC, hansemannn commented on iphone/Classes/TiUISearchBarProxy.m
> +  for (NSString *key in properties.allKeys) {
I assume `[self allProperties]` (`dynprops`) cannot be `nil`, otherwise the app could crash here.

2018-03-14 09:46 UTC, hansemannn approved these changes

2018-03-14 09:47 UTC, hansemannn commented
@vijaysingh-axway Do we have tests for all properties of the search-bar already? If not, please add them. We should get too easy with setting the `no tests` label, otherwise it might get removed again.

2018-03-14 10:08 UTC, vijaysingh-axway commented
@hansemannn In TIUISearchBar, getter is not implemented properly. It simply returns the value which is set in proxy. Ideally it should return value by fetching from searchbar. Currently whatever you set the value of property, it will return same even though that value is not passed to searhbar. So I am thinking to create a ticket for that, in which we can add all these property in unit tests as well. Thats why I have not added unit test in this ticket. Lets discuss on this.

2018-03-14 10:12 UTC, hansemannn commented
Like it, please do so! Maybe for the 7.3.0 timeline then.

2018-03-20 08:39 UTC, hansemannn commented
Closing in favor of #9947

2018-03-20 08:39 UTC, closed without merging