[TIMOB-25864] Android: Set default notification channel
appcelerator/titanium_mobile pull request #9945
Opened 2018-03-19 19:57 UTC by garymathews

- Set default notification channel to `NotificationChannel.DEFAULT_CHANNEL_ID` -> `"miscellaneous"`

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25864)

2018-03-19 20:14 UTC, build commented
<!--
  2 failure:  :microscope: Ther..., Tests have failed...
  0 warning: 
  1 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :microscope: There are library changes, but no changes to the unit tests. That's OK as long as you're refactoring existing code, but will require an admin to merge this PR. Please see <a href="https://github.com/garymathews/titanium_mobile/blob/TIMOB-25864/README.md#unit-tests">README.md#unit-tests</a> for docs on unit testing.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9945/1/artifact/dist/mobilesdk-7.2.0.v20180319125933-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.WebView | userAgent | 10.024 | Error: timeout of 10000ms exceeded |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-03-20 17:31 UTC, jquick-axway approved these changes
CR: Pass

2018-03-20 17:35 UTC, jquick-axway commented
**Note to QE:**
This needs to be tested on Android 8.x and an older OS version, such as Android 4.x.

2018-05-22 18:45 UTC, jquick-axway commented
@lokeshchdhry, did you change "tiapp.xml" to target API Level 26 or higher?

2018-05-22 19:05 UTC, lokeshchdhry commented
@jquick-axway , Yes I did set it to 26. 
Also setting it to 25 works fine.

2018-05-22 19:34 UTC, jquick-axway commented
After chatting with @lokeshchdhry, this PR fails to post local notifications on all Android OS versions when targeting API Level 26. It works on all Android OS versions when targeting API Level 25.

This is odd because we're using the same solution we used for push notifications. Lokesh is going to re-test push notifications from what's currently on "master" to see if it still works or not.

2018-05-25 08:39 UTC, hansemannn commented
@garymathews I've added https://github.com/appcelerator/titanium_mobile/pull/9945/commits/db6d91878ce41a049dd27da7265bbca7fd7c0f51 so Jenkins can build it.

2018-05-25 08:55 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9945/8/artifact/dist/mobilesdk-7.3.0.v20180525014009-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-05-26 00:45 UTC, jquick-axway requested changes

2018-05-26 00:45 UTC, jquick-axway commented on android/modules/android/src/java/ti/modules/titanium/android/notificationmanager/NotificationManagerModule.java
> +		if (notification.getChannelId() == DEFAULT_CHANNEL_ID) {
The `notification.getChannelId()` method call is API Level 26 only. We need to do an API Level check or else it'll crash on older Android OS versions.

2018-05-29 17:49 UTC, jquick-axway approved these changes
CR: Pass

2018-05-30 00:47 UTC, jquick-axway commented on android/modules/android/src/java/ti/modules/titanium/android/notificationmanager/NotificationManagerModule.java
> +	public static final String DEFAULT_CHANNEL_ID = "defaultChannel";
Do you think maybe we should use a prefixing notation to help avoid name collision?
Something like: `"ti_default_channel"`
(Kind of like how it's done with resources.)

2018-06-04 22:18 UTC, lokeshchdhry commented
FR Passed.

Local notifications work fine on API 26 & above.

Studio Ver:     5.1.0.201805300954
SDK Ver:        7.3.0 local build
OS Ver:         10.13.4
Xcode Ver:      Xcode 9.4
Appc NPM:       4.2.13
Appc CLI:       7.0.4-master.2
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.0
Alloy Ver:      1.12.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Nexus 6P --- Android 8.1.0

2018-06-04 22:18 UTC, lokeshchdhry commented
Waiting for suggested changes to be done to the PR.

2018-06-04 22:51 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  1 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9945/21/artifact/dist/mobilesdk-7.3.0.v20180604153944-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.TableView | appendSection and appendRow (TIMOB-25936) | 5.287 | Error: timeout of 5000ms exceeded |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-05 00:09 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9945/25/artifact/dist/mobilesdk-7.3.0.v20180604165240-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-06-05 00:14 UTC, merged