Prevent double onActionEditor call from simulated enter key.
appcelerator/titanium_mobile pull request #9948
Opened 2018-03-20 15:22 UTC by ypbnv

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25882

**NOTE:** This PR relies on https://github.com/appcelerator/titanium_mobile/pull/9933 to be merged first.

**Description:**
As far as I understood/researched and tested the scanner simulates a keyboard for the input and sends an enter key pressed event. `onActionEditor` is called with actionID equal to `TYPE_NULL` and once for every keyEvent action - ACTION_UP and ACTION_DOWN. If the first call is marked as not consumed (the method call returns false) the second one is not triggered. I am not certain why it is handled that way and most likely it is bubbled up to something that prevents the second call. This seems to be the case regardless of the IME_ACTION for the TextField. I was not able to think of a cleaner solution that would cover the cases.

I don't think should be labeled as a bug or improvement, because it has the same behavior in native Android as well. We are doing some of the filtering of the events under the hood.

2018-03-20 15:37 UTC, build commented
<!--
  1 failure:  Tests have failed...
  0 warning: 
  1 messages
  1 markdown notices
-->

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Tests have failed, see below for more information.
  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9948/1/artifact/dist/mobilesdk-7.2.0.v20180320082416-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>

### Tests: 

| Classname | Name | Time | Error |
| --- | --- | --- | --- |
| android.Titanium.UI.WebView | userAgent | 10.009 | Error: timeout of 10000ms exceeded |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-03-21 02:19 UTC, jquick-axway commented
I'm not sure if I understand.

Do you mean actual scanning software that reads texts via the mobile device's camera and outputs it to the app's TextField? And this issue only happens with Motorola Symbol phones? If so, then I would assume its simulating key events via software.

How were you able to test this?

2018-03-21 13:55 UTC, ypbnv commented
I was not able to test the exact scenario as the one described in the ticket's comment.

Apparently these devices have an embedded scanner that can be set up by third party software.
https://developer.zebra.com/thread/31628
I assumed that from the link above.
What I tested was sending keyevents through `adb` and by setting an emulator to take advantage of the hardware keyboard. By doing so I got the reported behavior in versions 6.3.0.GA through 7.1.0.GA. I combined this with the code we had in 6.3.0.GA (reported by the user to work for them)
https://github.com/appcelerator/titanium_mobile/blob/6_3_X/android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java#L473
and the following changes which "broke" that. This is the closest I could get to the actual scenario, bearing in mind that I have no clue what the actual events thrown by the scanner are.

I don't like what I did in this PR and IMO this is something that is hard to be universally solved, because different configuration of such scanners' input may result in different events and their handling. A better approach for me would be to propagate whatever the Android triggers to the JS, but that will most likely cause disparity for the event and we don't want that.

2018-03-21 20:16 UTC, jquick-axway commented
Thanks for the explanation. It looks like PR #9652 is the one that changed this behavior. Can you do a quick test with that PR's code as well? If it passes, then yeah,  let's go with your change.

2018-03-22 13:19 UTC, ypbnv commented
@jquick-axway Tried the test case from https://github.com/appcelerator/titanium_mobile/pull/9652 with software kyeboard and bluetooth keyboard both on landscape and portrait modes - the event is fired only once as expected.

2018-03-23 18:18 UTC, jquick-axway requested changes

2018-03-23 18:18 UTC, jquick-axway commented on android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java
> +		if (tv.getMaxLines() == 1) {
This should use the `this.field` property like in the other PR.
The rest looks fine.

2018-03-26 09:47 UTC, ypbnv commented
@jquick-axway Updated.

2018-03-26 21:16 UTC, jquick-axway approved these changes
CR: Pass

2018-04-04 17:36 UTC, lokeshchdhry commented
FR Passed.

Studio Ver:     5.1.0
SDK Ver:        7.2.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.3
Appc NPM:       4.2.12
Appc CLI:       7.0.3-master.27
Daemon Ver:     1.0.1
Ti CLI Ver:     5.1.0
Alloy Ver:      1.11.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       9.0.4
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Nexus 6P --- Android 8.0.0

2018-04-06 02:25 UTC, build commented
<!--
  0 failure: 
  0 warning: 
  1 messages
  
-->



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  :floppy_disk: <a href="https://jenkins.appcelerator.org/job/titanium-sdk/job/titanium_mobile/job/PR-9948/6/artifact/dist/mobilesdk-7.2.0.v20180405191040-osx.zip">Here's the generated SDK zipfile</a>.
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

2018-04-06 09:06 UTC, merged